### ISSUE TITLE
Can't enter Aether, portal does not teleport. 

### ISSUE THREAD

**Issue by Seegras** [TheLimePixel/Modern-Skyblock-3#100]
The portal spawns, but upon entering, only the vision gets blurry, the teleport never happens. the long you wait, the longer it just takes until the vision normalizes.

**Comment by TheLimePixel** [comment]
You need to have it unlocked.

**Comment by Seegras** [comment]
the quest is marked red, so I guess I should be able to do it? I can't see in what it would depend.

**Comment by TheLimePixel** [comment]
Well, if you had it unlocked before updating to 3.1.3, if you read the changelog, you'd know that you need to do /gamestage add @p oa
