### ISSUE TITLE
Rare Valkyrie Lance

### ISSUE THREAD

**Issue by iasazo** [TheLimePixel/Modern-Skyblock-3#108]
In gate mode to unlock the Twilight Forest Chapter you need the Valkyrie Lance.  

It has no crafting recipe and has a 0.75% chance to drop from the slider boss.  The slider boss dungeons seem quite rare making this a boring fight against RNG.

I think I got one from a loot bag (doesn't show in NEI) or loot chest early on but unfortunately tossed it.

**Comment by TheLimePixel** [comment]
Well, it's all up to RNG there.
