### ISSUE TITLE
quest book glitch

### ISSUE THREAD

**Issue by LividJaffas** [TheLimePixel/Modern-Skyblock-3#110]
when joining a world it automatically completed all of the quests and it also happens with other worlds created

**Comment by progheal** [comment]
There's another report of a similar case a while ago (#37), but it is once labeled by author as unreproducable, but then have a comment of "Yeah, revert to a backup. This can happen." Judging by this, I think this problem may be a random thing, and if you are lucky the set of automatically completed quests won't affect your quest line, if you are not then your quest book will be messed up.

**Comment by TheLimePixel** [comment]
Yup. Although quests messing up in new worlds does not make sense and you should usually be fine just reverting to a backup, it's a really weird bug.
