### ISSUE TITLE
[3.1.3.2] Crafting huge amount lag the server

### ISSUE THREAD

**Issue by Gayanfalor** [TheLimePixel/Modern-Skyblock-3#112]
Hello there, i dont know if its a server bug or from the pack but i'll ask here maybe you'll have an answer.

I'm playing with my friend on his server, we are only  two playing on for now but each time we craft huge amouht of things like a stack of compressed cobble or another thing, the server lag as hell and yesterday each time my friend was crafting stack i got a timed out.

For my self i'm using the crafting table on a stick from AA to craft i dont know if my friend using it too, maybe its coming from it i havent tested with the regular crafting table or the tinkers one.

My friend is also using spongeforge on his server maybe it could come from it too.

Well i've said everything i think, waiting for advice thanks

**Comment by TheLimePixel** [comment]
It's an MC 1.12 issue.

**Comment by Gayanfalor** [comment]
ok thanks
