### ISSUE TITLE
Digital Storage quest icon not displaying when channels are disabled

### ISSUE THREAD

**Issue by andremiller** [TheLimePixel/Modern-Skyblock-3#114]
When disabling channels, as suggested on MSB3 vs MSB3 Page on CurseForge, the Digital Storage quest icon is a red question mark because the controller block is removed when channels are disabled.
Version: 3.1.3.2

**Comment by TheLimePixel** [comment]
I guess the only temporary fix is enabling channels, crafting it and then disabling them.
