### ISSUE TITLE
Reliquary problems

### ISSUE THREAD

**Issue by KingSmedi** [TheLimePixel/Modern-Skyblock-3#121]
since the new pack update, Monsters drop many reliquary items at the time.
for example: i kill a skeleton  and it drops like 33 rib bone's.
please fix.

**Comment by RustyXXL** [comment]
Sure you don't have an item with luck from mega loot like the viking helmet?

**Comment by KingSmedi** [comment]
Ok that explains a LOT because i've got the viking helmet recently.
Thanks!

Am 17.02.2018 18:34 schrieb "RustyXXL" <notifications@github.com>:
