### ISSUE TITLE
[3.1.3.3] OreExcavation does not drop all items when used.

### ISSUE THREAD

**Issue by CrypticDivide** [TheLimePixel/Modern-Skyblock-3#122]
When using OreExcavator, it only gives you items back as if you only broke one block. This is not the case for all tools, though. We found that if you use silk touch, this issue does not apply, and if you use Tinkers' tools that can mine items in a 3x3 area, then it does the same thing, only it gives you items back as if you broke a 3x3 area of blocks. 

I have linked a video demonstrating this issue. In the video, the order of events are as follows.
- I mine one block of dirt with a Tinkers' shovel without OreExcavator.
- I mine the rest of the row of dirt with the same Tinkers' shovel using OreExcavator.
- I mine one block of cobblestone with a Tinkers' pickaxe without OreExcavator.
- I mine the rest of the row of cobblestone with the same Tinkers' pickaxe using OreExcavator.
- I mine a block of dark oak using a Tinkers' axe without using OreExcavator.
- I mine a portion of the rest of the dark oak tree with the same Tinkers' axe using OreExcavator.
- I mine a 3x3 area of dirt using a Tinkers' excavator without OreExcavator.
- I mine the rest of the 3x3 rows of dirt with the same Tinkers' excavator using OreExcavator.
- I mine a 3x3 area of cobblestone using a Tinkers' hammer without OreExcavator.
- I mine the rest of the 3x3 rows of cobblestone with the same Tinkers' hammer using OreExcavator.
- I mine the dark oak tree with a Tinkers' lumberaxe without using OreExcavator.

[Video Removed]
Please note that once this issue is resolved, the video will be taken down.

Thank you! CrypticDivide

**Comment by TheLimePixel** [comment]
SP or MP. If MP, do you have sponge?

**Comment by CrypticDivide** [comment]
It is in multiplayer with spongeforge-1.12.2-2611-7.1.0-BETA-2918.

We have the following plugins installed on the server.
- CatClearLag-0.8.2
- CustomRestartMessage-1.0
- holograms-3.1
- LuckPerms-Sponge-4.0.139
- MagiBridge-API7-2.4.4.1
- MMCRules-1.2.1-API7
- Nucleus-1.3.1-S7.0
