### ISSUE TITLE
Fishing Bugged

### ISSUE THREAD

**Issue by RR3XBX** [TheLimePixel/Modern-Skyblock-3#126]
Okay, using the Survivalist Fishing Rod, I can't fish for any items.
It bobs, a fish bites, then nothing when i pull it back, but this doesn't happen when I use a normal fishing rod.

**Comment by RustyXXL** [comment]
This happened to me while wearing the viking helmet with luck from mega loot...taking the helmet of fixed it for me.

**Comment by ghost** [comment]
Thank you Rusty! That is it :) I can reproduce the issue with my MegaLoot helmet that has luck as well

**Comment by RR3XBX** [comment]
It works now. I had the Samurai helmet on from Mega Loot, i took it off and now i can fish
