### ISSUE TITLE
Crushing table recipe

### ISSUE THREAD

**Issue by UberZogster** [TheLimePixel/Modern-Skyblock-3#128]
The crushing table requires forestry wood which is more advanced than the quest "Lemme Smash" on "Basic Resources" tab suggests it should be. 

Or a better way of putting it. The quest Lemme Smash isn't doable at the stage of quest completion that it is placed due to advanced materials needed to make the crushing table.

**Comment by TheLimePixel** [comment]
It requires any wood.
