### ISSUE TITLE
[Question] Plans for RefinedStorage

### ISSUE THREAD

**Issue by accessdenied0** [TheLimePixel/Modern-Skyblock-3#129]
Hey @EmosewaPixel,

I have a question if it is ever planed to Add RefinedStorage to MS3. I know you did add it to MS2, (even with Storage Reborn, I like it!), but I miss it in MS3. Even AE2 is not that bad, I prefer the good old AE style made by RS alot.

Are there plans, you might add it as alternative (or maybe "upgrade" to AE2) to MS3?

access_denied

**Comment by TheLimePixel** [comment]
Nope.

**Comment by accessdenied0** [comment]
Interesting, can I ask why, just out of interest?

**Comment by TheLimePixel** [comment]
Well, having 2 different storage mods didn't go too well last time in terms of quests and creative item recipes. Having people go through 2 similar mods can be annoying for them.

**Comment by accessdenied0** [comment]
Well, even if it disappoint me a bit, I thank you for your time explaining that.
