### ISSUE TITLE
[Suggestion]Crash with TipTheScales and Optifine

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#13]
TipTheScales and OptiFine are not doing very well. Should both mods be included in the pack and you try, e.g. to open the video settings, there is a crash.

Most people use optifine. therefore I would recommend to remove tipthescales from the pack.

This mod itself contains nothing special and is in my opinion unnecessary.

**Comment by TheLimePixel** [comment]
So far, I've seen many people use OptiFine and no one's had this issue. Yet, it's best not to use OptiFine with modded anyways.
