### ISSUE TITLE
bedpatch v2.1 preventing sponge from loading

### ISSUE THREAD

**Issue by colinrgodsey** [TheLimePixel/Modern-Skyblock-3#130]
New version of bedpatch (2.1) in v3.1.3.4 is preventing sponge from loading. 

https://github.com/Mordenkainen/BedPatch/issues/3

**Comment by TheLimePixel** [comment]
Sponge doesn't work well with modded MC in the first place. All I can say is don't use it. :P

**Comment by colinrgodsey** [comment]
or we can just fix the issue: https://github.com/Mordenkainen/BedPatch/pull/4

Would be a damn shame to cut out sponge just because 1/300 mods has issues with it ;)
