### ISSUE TITLE
Quark crashing with Spongeserver

### ISSUE THREAD

**Issue by ChuckNoxis** [TheLimePixel/Modern-Skyblock-3#134]
Hello,

I'm actually running Spongeforge in a docker container for a private server with a friend.
I'm on Sponge 1.12.2-2611-7.1.0-BETA-2927 with Forge 1.12.2-14.23.2.2611. We are playing actually on 3.1.3.2 version of the modpack, when I tried to update in 3.1.3.4, the server don't start because Quark loads a class before Sponge does. 
[Here is a link to the gist logs](https://gist.github.com/ChuckNoxis/abc8fabfbb34fe9f939e2c0391744603)
I didn't tried yet the 3.1.3.3 version of the modpack but I suppose it should start normally as you didn't have updated Quark in the 3.1.3.3

**Comment by colinrgodsey** [comment]
@ChuckNoxis it's not Quark, it's actually bedpatch: https://github.com/Mordenkainen/BedPatch/pull/4

Should be fixed in the next version.

**Comment by colinrgodsey** [comment]
The new version is out with the fix, should be able to just updated it on your server: https://minecraft.curseforge.com/projects/bed-patch/files
