### ISSUE TITLE
Survival Fishing Rod not working

### ISSUE THREAD

**Issue by sparkeredhut** [TheLimePixel/Modern-Skyblock-3#135]
I had started the mod pack in staged mode and was going through the quests in the first section and I made the survival fishing rod. I started fishing I had played the mod pack in previous versions and when you are fishing you see the partical effects for water and you pull the fishing rod in. I had been doing this for several minutes and each time I pulled it in I got nothing and it didn't just happen to me my friend was playing the mod pack and reported the same issue. Thank You for listening I hope you can fix this issue soon

**Comment by TheLimePixel** [comment]
Removing any armor piece that has luck.
