### ISSUE TITLE
No heat sources category.

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#139]
Whilst looking for a way to melt stuff faster, I started checking to see if there is something better than lava. 

Lava has no heat sources category whatsoever. 
Torch has one, but it only shows a bugged image for the torch with the line "1 heat"
And despite what the guide under 'G' says, there is no listing for any other item.

**Comment by TheLimePixel** [comment]
So you go on the uses of the Torch, go to the Heat Sources page and press on the title of it.
