### ISSUE TITLE
Restricted items aren't actually restricted?

### ISSUE THREAD

**Issue by bricky1** [TheLimePixel/Modern-Skyblock-3#14]
Latest version: 3.0.0.4

Item tested: @ActuallyAdditions Wood Casing (required for Small Storage Crate)

The item is labeled as "Restricted item", instead of "Wood Casing", but I am able to craft it and use it in additional recipes. This is the only item I've tried, as it's easily craftable within minutes of starting a new world. Tried both Staged and Gated modes via quest book quest completion. The item is also not listed in JEI, but the recipe is still viewable via looking at other recipes.

What does restricting even do? Are you meant to just avoid crafting these items on purpose, or have I messed up a setting somewhere?

**Comment by TheLimePixel** [comment]
Fixed in version 3.0.0.5.
