### ISSUE TITLE
mod immersive engineering

### ISSUE THREAD

**Issue by JJusola** [TheLimePixel/Modern-Skyblock-3#141]
Using the immersive engineering guide/book. Crashes the game.
[crash-2018-02-17_02.00.04-client.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1738961/crash-2018-02-17_02.00.04-client.txt)

**Comment by TheLimePixel** [comment]
Change your MC launcher to use a newer Java version.
