### ISSUE TITLE
bog earth not registered on crafting list in forestry worktable

### ISSUE THREAD

**Issue by Gayanfalor** [TheLimePixel/Modern-Skyblock-3#143]
Triedd to craft bog earth with bucket of water sand and dirt in forestry worktable when crafted its not going on the remember list on the right and rollback the craft.

Maybe it could beter to post this on the forestry github isnt it ?

i found another small bug too.

i had like 5-6 empty iron bucket but only 3 free space in my inventory, i filled them all with right click on a pitcher plant that fill bucket with right click. i filled the 6 bucket but only could got 3 in my inv so i touhgt other was on the ground but no they just disapeared.

**Comment by Gayanfalor** [comment]
hmm thats strange then, its not restricted item its unlocked, sorry for that then ^^

**Comment by TheLimePixel** [comment]
Yeah, you can't craft items that are by default restricted in the Workbench.

**Comment by Gayanfalor** [comment]
Ahh ok thanks, and for the other bug with the flower and bucket its from randomn things ?

**Comment by TheLimePixel** [comment]
Yup.
