### ISSUE TITLE
Wooden gear

### ISSUE THREAD

**Issue by B013040034** [TheLimePixel/Modern-Skyblock-3#144]
So how could I get casing in version 3.1.3.4
the 4 sticks to wood gear has been removed
but the logwood I don't know how to get it 
plz fix the problem
 by player from Taiwan

**Comment by B013040034** [comment]
sorry can you tell me how to get casing
I'm confusing and can't continue the game QQ

**Comment by TheLimePixel** [comment]
Well, there is a recipe with a Stick in the middle surrounded by Planks.

**Comment by B013040034** [comment]
but the planks should be fireproof
in the earlier of game can't get the fireproof plank

**Comment by TheLimePixel** [comment]
No they don't, it's any plank (if you hover over the planks in the recipe it says plankWood on the bottom of the tooltip)

**Comment by B013040034** [comment]
3Q for your answer

**Comment by jellonek** [comment]
But still there is a recipe with four sticks, which can be perfectly used on tinkers or plain table what leads to creation of item without any icon and "This is disabled item" description (type: appliedenergistics2:material).

So it IS a bug in item crafting disabling...

**Comment by TheLimePixel** [comment]
Update.

**Comment by jellonek** [comment]
I can confirm - after update recipe with sticks is not working. Thanks!
