### ISSUE TITLE
Silent gems aquamarine in starlight infuser

### ISSUE THREAD

**Issue by jellonek** [TheLimePixel/Modern-Skyblock-3#145]
I have aquamarine only in form of item from silent gems, acquirable from cleaning dirt one in crucible.
It works perfectly for most things in `Astral Sorcery`, but it can not be infused in `Starlight Infuser`.

To be sure that `Starlight Infuser` is made correctly I tried to infuse glass pane in it - and that works perfectly, so looks like that's an issue with aquamarine. If it's desired that there could be infused only `Astral Sorcery` one made with it's sand generator - it should be noted somewhere in questbook, as `Resonating Gem` can be done only in `Starlight Infuser` (there is no other recipe for it) and it's required for `Iridescent Altar` which is one of steps in `The Power Of Stars` questline.

**Comment by TheLimePixel** [comment]
Hence there is an Atomic Reconstructor recipe to turn it into the Astral Sorcery one.

**Comment by jellonek** [comment]
Just tested infuser with Astral Sorcery one - same effect - it does not work.

**Comment by jellonek** [comment]
Can you verify that on your side and at last reopen the issue?

**Comment by EmosewaPixel** [comment]
Yes, for it to work it needs to be night time and there mustn't be anything above the Lightwell.

**Comment by TheLimePixel** [comment]
Did you use a Resonating Wand on it?

**Comment by jellonek** [comment]
Yes. Of course - i tried resonating wand at night time.
lightwell? wait a moment - i'm trying to turn aquamarine to resonating gem using the recipe, which is precisely pointing me to do that on starlight infuser.

**Comment by TheLimePixel** [comment]
Yeah, I thought you were talking about the Lightwell for a moment, hence I deleted that afterwards.

**Comment by jellonek** [comment]
Ok, so i'll repeat - this starlight infuser is working for me when i'm trying to turn glass pane into glass lens, but in the same time, with same procedure it does not turn aquamarine to resonating gem (no matter if it's from silent gems or from astral sorcery, i tested that with both of them) using resonating wand during night time on starlight infuser.

Same procedure on direwolf20 modpack works ok.

[edited]ups, i typed "wirefolf20" instead direwolf20 :D - fabulous typo[/edited]
