### ISSUE TITLE
Placeholder ID in loot chest

### ISSUE THREAD

**Issue by crusender** [TheLimePixel/Modern-Skyblock-3#150]
<img width="1920" alt="bug" src="https://user-images.githubusercontent.com/8825886/36464646-f4d39f58-169e-11e8-9bd2-68e9391f95a1.png">

when i open a loot box there what i got

**Comment by jellonek** [comment]
Did you reloaded loot table after modpack update?
Hint: in questbook you have a reload option on first page.
