### ISSUE TITLE
(BUG) Compressed Sand + Autosmelt shovel = 36 Bricks

### ISSUE THREAD

**Issue by Cr1t1calReaper** [TheLimePixel/Modern-Skyblock-3#151]
I found this bug in version 3.1.3.2 and I have also just tested it 3.1.3.4 where it also works.
Basically, when mining a block of compressed sand (Has to be the one from Sky Compression) with an autosmelt shovel, it will drop 36 Bricks...

Links show pictures of my shovel, in case that matters for some reason. The Cobalt head was added later, it started with a Stone head.
https://gyazo.com/cd7b1a92a4ad2ce4362f4d14b92a290f
https://gyazo.com/74d7343454b432ae33730430ba59e3a5

Best regards
Cr1t1cal

**Comment by TheLimePixel** [comment]
I tried with the exact same shovel and both types of compressed sand and it did not work.

**Comment by TheLimePixel** [comment]
Oh... apparently it was fixed in 3.1.4.
