### ISSUE TITLE
Can't Open the Guide

### ISSUE THREAD

**Issue by itspascaltv** [TheLimePixel/Modern-Skyblock-3#152]
i can't open the guide with "G" anymore

**Comment by Fababfan** [comment]
Have you checked if there are some conflicts with other mods that use the same key?

**Comment by itspascaltv** [comment]
Yes only the Sky Ressource Guide use the G

**Comment by itspascaltv** [comment]
Its fixed. The ExtraPlanet Mod used the same Key :)
