### ISSUE TITLE
Crash on search

### ISSUE THREAD

**Issue by Silly26** [TheLimePixel/Modern-Skyblock-3#159]
After trying to reproduce this crash, I've finally narrowed it down to one particular item. Utilizing the search function in Quark (I believe, it's the box marked in red, between inventory and chest) the game will crash to launcher/desktop. 

https://imgur.com/a/Povj8

The item in question is a Diamond Chestplate, enchanted with Last Stand II as well as Mending. 

Searching 'D' works, however when you add the 'i' it will crash. So far this has been reproducible every time. I can fetch a crash log if necessary. I'm running version 3.1.5, however this issue has been present since as far as 3.1.3.1.

**Comment by TheLimePixel** [comment]
I tried it with the same chestplate and it works fine for me.
