### ISSUE TITLE
Improved Blast Furnace not producing steel

### ISSUE THREAD

**Issue by moetrix** [TheLimePixel/Modern-Skyblock-3#161]
I don't know why but i upgraded my blast furnace to the improved one along with two preheaters and now it just burns through fuel but doesn't convert the iron to steel

**Comment by b0bst3r** [comment]
In version 3.1.5 Immersive Engineering was updated and a bug was found that the blast furnace does not work.  IE team have fixed it but as yet there's no release of the mod.
