### ISSUE TITLE
Lost Connection to server error

### ISSUE THREAD

**Issue by LucasErG** [TheLimePixel/Modern-Skyblock-3#162]
Often when entering the nether the lost connection to server error happens, this causes on reloading the world for the player to be falling endlessly in the nether and the kill command wont work. editing the worlds nbt data is the only way i have found to get out of the nether when this happens.

**Comment by Aerandros** [comment]
I had the same thing happen. Opened to LAN activated cheats and rebuilt a nether portal using angel blcok to get a starting point. When reentering the portal from the nether side I respawned on a newly spawned portal in the overworld. Got the travelling over 7km Achievement actually went over 7 km in both x and z directions.
Trying to go back to the Nether seems to be impossible, only getting swirly particles, no actual travel. Even breaking all portals in the overworld does not fix this.

This should be the log where the crash happened: [2018-02-24-2.log.gz](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1754733/2018-02-24-2.log.gz) (Sorry, dont know how to make it readable for pastebin or similar)

Edit. I was able to go to the Nether after dying once.
