### ISSUE TITLE
Starmetal Ore

### ISSUE THREAD

**Issue by moetrix** [TheLimePixel/Modern-Skyblock-3#164]
I can't get the creation of starmetal with a floating crystal to work in survival.
I tried it in a creative test world and there it worked.

**Comment by TheLimePixel** [comment]
Do you have it unlocked in the Journal?

**Comment by moetrix** [comment]
Yes i do

**Comment by moetrix** [comment]
It should be unlocked after upgrading to the starlight crafting altar right?

**Comment by SystemCollapse** [comment]
Log out and Log back in, fixed it for me.
