### ISSUE TITLE
Can't Progress Without Dandelions

### ISSUE THREAD

**Issue by RR3XBX** [TheLimePixel/Modern-Skyblock-3#165]
Okay, I can't spawn any other flowers when bonemeal'ing grass, other than grass and the blue one, so i can't make floral fertiliser without Dandelions.
Is there something i can change to increase the spawn chance, or is it mod related?

**Comment by TheLimePixel** [comment]
That's because of your biome. Floral Fertilizer can be made with Floral Powder, which you can make with a Mortar And Pestle and any flower.
