### ISSUE TITLE
Fence Overhaul causing game to crash on startup

### ISSUE THREAD

**Issue by fluffe9911** [TheLimePixel/Modern-Skyblock-3#17]
When ever I try to launch this modpack at the very end of loading it crashes and I get this error 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fence Overhaul (fenceoverhaul)

It seems removing the mod in question fixes the crash any ideas?

**Comment by TheLimePixel** [comment]
Well, there are some mods that when launching the pack will crash you for no reason and stop doing that after restarting your computer. Otherwise, this is unreproducable.
