### ISSUE TITLE
Connection timeouts affecting many users

### ISSUE THREAD

**Issue by malakai97** [TheLimePixel/Modern-Skyblock-3#170]
```
[02:23:39] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null
[02:23:39] [Server thread/INFO]: foouser lost connection: Timed out
[02:23:39] [Server thread/INFO]: foouser left the game
```

I've been troubleshooting this for a while. I've verified that it isn't the network connection or firewall. Server and client are both running 6GB ram. Users have reported seeing the same issue with 10GB+ of ram for server and client.  Setting fml.readTimeout or fm.loginTimeout do nothing. Even rebuilding forge to push the hard-coded timeout in NetHandlerPlayServer doesn't affect the issue.  I've tested with forge versions 2611+.

It may just be an artifact of the size of the pack, but in that case I would expect pushing these timeouts back to work. Does it really need to be larger than AllTheMods?

**Comment by TheLimePixel** [comment]
Well, with the pack already having Random Patches that increases the timeout timer to 5min, there is nothing I can do.

**Comment by malakai97** [comment]
I did some messing around with RandomPatches and I've determined something important:

The issue will occur regardless of the timeout duration; that is, something hangs forever.  

I'm not seeing anything useful in any of the logs after the connection begins, but i'm not even sure if debug output is properly enabled. Let me know if there's any other info that would be worth collecting.
