### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Skriton** [TheLimePixel/Modern-Skyblock-3#172]
So after playing for about 5-10 min the game crashes. I really don't know how to read crash reports. Any help would be greatly appreciated. 

https://pastebin.com/JFs3xuRJ

**Comment by Skriton** [comment]
Update, I believe it has something to do with looking through the Immersive Engineering Manual.

**Comment by EmosewaPixel** [comment]
Change the java version your MC launcher uses.

**Comment by TheLimePixel** [comment]
Actually, it seems to be related to the questbook.

**Comment by b0bst3r** [comment]
Java Version: 1.8.0_25

Update this should be on 1.8.0_151 at the very least

**Comment by Skriton** [comment]
Thank you very much

**Comment by BladeCrimson** [comment]
I know this issue is closed, but I'm having the same issue right now.
Can you tell me what fixed it for you? I have the latest version of Java, did an update but it didnt fix the crash

**Comment by Skriton** [comment]
I seemed to be the Bibliocraft fancy lantern, once I took those down, i have had no further problems.
