### ISSUE TITLE
Crafting with Refined Storage Issues and RFTools Crafters (Sort of Dupe of #35 and 54)

### ISSUE THREAD

**Issue by dragonreborn614** [TheLimePixel/Modern-Skyblock-3#174]
I have added Refined Storage to the pack as I enjoy playing with that better than AE2. I am in Kitchensink mode. When trying to use RS crafting or patterns, it will display the correct recipe but won't craft or let me pull out the item. Crafting in a vanilla crafting table works just fine. This seems to be an issue with the items that are restricted in Gated or Staged modes. I looked through past issues and saw this was resolved with AE2. 

I know RS isn't a part of the pack, so I know this probably can't be fixed. But I figured I would try.

*update*
I tried using the RFTools Crafters to get around this. They also have the same problem. I have tried non gated recipes and they work just fine. The gated ones just sit in the crafter not working.

**Comment by dragonreborn614** [comment]
The RFTools Crafter is park of the pack. Is that an issue that can be fixed? Or is this an issue with both Refined Storage and RFTools?

**Comment by TheLimePixel** [comment]
The Crafters from RFTools are fake players, hence they don't work. For crafting items that used to be reastricted, with Refined Storage, it needs to be whitelisted.

**Comment by dragonreborn614** [comment]
Thanks for taking the time to respond. The RFTools crafters make sense now.
As I have not been able to find out how to, how would I go about whitelisting RS?
Again, thanks for the help.
