### ISSUE TITLE
Hopping Bonsia and multiple drops

### ISSUE THREAD

**Issue by LovelyBirch** [TheLimePixel/Modern-Skyblock-3#176]
Hi there,

I am on latest release and when I kill mobs I get loads of reliquary drops and my hopping bonsais will not accept any sapling any help will be appreciated. this is also single player no op.

**Comment by TheLimePixel** [comment]
The first one is not an issue and update (for the second one).

**Comment by LovelyBirch** [comment]
I am on the latest version though aren't I with version 3.1.5

**Comment by LovelyBirch** [comment]
Just found Beta on twitch NVM will test this :)
