### ISSUE TITLE
Whitelisting Refined Storage (related to #174)

### ISSUE THREAD

**Issue by AnthonyH260** [TheLimePixel/Modern-Skyblock-3#177]
I saw in a previous post that someone was having issues with Refined Storage. I'm having the same thing happen.

How does one go about whitelisting Refined Storage to fix the issue?

Thanks.

**Comment by TheLimePixel** [comment]
As it's not a mod in the pack, I will not try to find the backage name.

**Comment by AnthonyH260** [comment]
Ok.

If anyone else figures this out, I would love to know the answer. If I figure it out, I will return.

**Comment by AnthonyH260** [comment]
I have found a solution which has worked for now.

Go into the Scripts folder. Delete the stages.zs. I assume this will only work if you playing in Kitchensink mode as it is messing with the item stages with the quests.
