### ISSUE TITLE
can't craft resonating wand

### ISSUE THREAD

**Issue by sreekrishn** [TheLimePixel/Modern-Skyblock-3#182]
can't craft resonating wand and luminous crafting table

**Comment by sreekrishn** [comment]
![2018-02-25_13 48 24](https://user-images.githubusercontent.com/36627174/36639441-f12fc718-1a32-11e8-8d50-d07145e7440c.png)
![2018-02-25_13 48 36](https://user-images.githubusercontent.com/36627174/36639442-f3fdde30-1a32-11e8-95e5-85b45ecd6a08.png)
![2018-02-25_13 48 42](https://user-images.githubusercontent.com/36627174/36639443-f602d08c-1a32-11e8-850e-16eb40c7b356.png)
![2018-02-25_13 52 26](https://user-images.githubusercontent.com/36627174/36639455-29d7f6d0-1a33-11e8-9e31-5215a5f54e61.png)

**Comment by b0bst3r** [comment]
I'd put money on FastWorkbench-1.12.2-1.0.1 that's broken this as it replaces (stealthly) the vanilla crafting table with its own.  Could you remove the mod and retry?

**Comment by DexTrraNox** [comment]
Yup,
Its the FastWorkbench , after removing it works fine
