### ISSUE TITLE
Condenser bug

### ISSUE THREAD

**Issue by neacetea** [TheLimePixel/Modern-Skyblock-3#184]
Condenser start to produce iron, but when completed, nothing work, we need to destroy and replace condenser. In multiplayer.

**Comment by b0bst3r** [comment]
Which condenser?
What other blocks make up the multipart?
Which version of the pack?
Server running Sponge?

**Comment by neacetea** [comment]
Stone condenser with Stone casing, Stone multipart, 2 dropper above it, with a crucible, all working well with the first powder, but when the second powder need to start, nothing work, it stay at 0%.

I don't know if the server running Sponge, it's not mine.

Sorry for my bad english.

**Comment by neacetea** [comment]
Ok i know the issue, dropper above the condenser must be full each time ...
