### ISSUE TITLE
Modern Skyblock v3.1.3.4 JEI/Questing bug

### ISSUE THREAD

**Issue by Fadirstave** [TheLimePixel/Modern-Skyblock-3#188]
Maybe a bit long, let me try to explain this the best I can. Started on a server with friends, I selected the wrong quest line Kitchen SInk Played for a good hour when I realized my mistake. I contacted the admin 
who ran this console command to reset my questing book so that I could play in gated mode. "bq_admin reset 
all bigdrewskii"

I played for a couple days until I realized, I could craft and see ALL items in my JEI. Items that my 
friends, who were playing in gated mode from the start had not unlocked yet.

Anyone know how we can alleviate this issue? I don't want to continue playing as it is breaking my 
experience, I feel like I am cheating haha

Thanks!!

**Comment by TheLimePixel** [comment]
Your server owner needs to do /gamestage remove 'your username' 'stage name' The names of the stages are the initials of the quest pages, besides for ee being for Equivalence. Of course, don't have the stages for unlocked pages be removed.
