### ISSUE TITLE
Cannot connect to official server

### ISSUE THREAD

**Issue by NiSiSuinegEht** [TheLimePixel/Modern-Skyblock-3#19]
![2018-02-01_20 55 25](https://user-images.githubusercontent.com/22671678/35713934-fbe4da16-0797-11e8-9d9d-d81f1509d84f.png)

Using modpack version 3.0.1

**Comment by TheLimePixel** [comment]
Yeah, it's not available yet. However, there are a few people that have public servers for it, which you can find in the Discord for the pack. But I guess the real issue here is me keeping that button there.
