### ISSUE TITLE
Cant Discover Planets with Telescope

### ISSUE THREAD

**Issue by Peacie** [TheLimePixel/Modern-Skyblock-3#190]
Discorer with the telescope dont work, if you are playing in German
Example:
Got the Paper for Moon from the Controller, telescope cand find. Same for Neptun.
Uranus and Saturn works.
Research Name: Moon Translated Name: Mond -> Doesnt discover
Research Name: Neptun Translated Name: Neptune -> Doesnt discover
Research Name: Uranus Translated Name: Uranus -> **discover**
Research Name: Saturn Translated Name: Saturn -> **discover**

[edit]
After switching language to eng it discovers all. So ist an issue with the Translation
[/edit]

**Comment by b0bst3r** [comment]
This is fixed in PlanetProgression-1.12.2-0.1.8.jar which didn't make it into 3.1.5.2 of the pack so will be update after that.  Meanwhile you could always update it yourself if playing in single player.

**Comment by Peacie** [comment]
Thanks alot for your great work here.
