### ISSUE TITLE
Whenever I press a media key, an uncloseable galacticraft screen pops up.

### ISSUE THREAD

**Issue by ericBG** [TheLimePixel/Modern-Skyblock-3#191]
I'm nowhere near that far into the pack but whenever I press the keys on my keyboard to fast forward a song, it does that, but also brings up a screen with our planet and the prompt to build a space station. I can't close this, which resigns me to a 15 minute restart loop (including a forced crash) with my SSD...

**Comment by TheLimePixel** [comment]
You could just change the key.

**Comment by ericBG** [comment]
It's not on the key bindings menu at all
