### ISSUE TITLE
Not detecting Naphtha and Refined Fuel

### ISSUE THREAD

**Issue by hossumquat** [TheLimePixel/Modern-Skyblock-3#192]
Part of the Thermal Expansion quests for the Fractionating Still.  I am assuming a bucket of each should detect but they don't.  Tried the Jerrycan as well.  If it's supposed to detect the 1000mb some other way, I have no idea what that other way would be (i.e. is not obvious).

**Comment by hossumquat** [comment]
Ok wait, now it's detecting.  I think maybe both buckets need to be in your inventory and then it detects both?  Having only one or the other doesn't detect but having both suddenly detects both.

**Comment by b0bst3r** [comment]
Yeah that's how Better Questing works for the most part.
