### ISSUE TITLE
quest: Tier 3 rocket requiring wrong key

### ISSUE THREAD

**Issue by DoomSquirter** [TheLimePixel/Modern-Skyblock-3#196]
MSB-3.1.5.1
you want the Nasa workbench tier 3 rocket 
but also the tier 3 key which is not the key you open that chest with.  that is tier 2.

**Comment by b0bst3r** [comment]
Rockets require Keys ????

**Comment by b0bst3r** [comment]
Chapter: To Space and Beyond
Quest: Tier 3 Rocket

Requires: NASA Workbench Schematic (this is correct)
Requires: Tier 3 Dungeon Key (this should be Tier 2 key as the Tier 3 schematic is in a tier 2 dungeon chest)
Requires: Tier 3 Rocket (this is correct)

**Comment by TheLimePixel** [comment]
Oh, I didn't fix this.
