### ISSUE TITLE
Twilight forest portal not working

### ISSUE THREAD

**Issue by hossumquat** [TheLimePixel/Modern-Skyblock-3#197]
I can create the portal.  Everything works up to the point of jumping in it.  I can stand in the pool for hours and get really bored but that's all that happens.

**Comment by TheLimePixel** [comment]
You need to unlock it.

**Comment by hossumquat** [comment]
Ya, the thing is, I have unlocked it.  After finishing up the "using blood" quests it opened up, so I unlocked it on the first tab, and now I try and do the first quest in this new tab but I can't progress.  Can I unlock it some other way manually?
