### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by geogeo12** [TheLimePixel/Modern-Skyblock-3#199]
Hello. I have a problem with the arguments. Everytime i start the game i have to change then amount of ram the launcher can use. By default is 256mb and something.. I have to manually change everytime to 8gb-12gb. Any solutions?

**Comment by b0bst3r** [comment]
Which launcher?

**Comment by geogeo12** [comment]
I using the twitch/curse one

**Comment by TheLimePixel** [comment]
Click on the lines in the top left corner of the Twitch launcher, File>Settings>Minecraft and set it in Java Settings.
