### ISSUE TITLE
squid not spawning

### ISSUE THREAD

**Issue by hqpwca** [TheLimePixel/Modern-Skyblock-3#20]
![2018-02-02_11 43 49](https://user-images.githubusercontent.com/14214536/35715596-76b4a71e-080e-11e8-9b80-5f3d209e7eb0.png)
#
In survival mode, when I follow the quest to build a squid farm, I found squids weren't spawning in the flowing water farm, which worked well in other modpacks, and I test in an test world as above, make the squid spawning area between y-level 63 and 60, and the squid never appears. 

After I tried for about 10 minutes, the squids suddenly spawn one time, but never spawn again.

**Comment by iridium22** [comment]
try floating water down

**Comment by hqpwca** [comment]
my farm is using floating water down to level 1 to make the squid take fall damage, but it doesn't work in my world.

**Comment by iridium22** [comment]
:/ it working for my

**Comment by Fababfan** [comment]
Well, if you just need some ink, you can also use the survivalist's fishing rod. It gives you sometimes 10 inks in one go.
