### ISSUE TITLE
Chisel no longer connected texturing

### ISSUE THREAD

**Issue by jamzam90** [TheLimePixel/Modern-Skyblock-3#201]
![2018-02-28_02 58 39](https://user-images.githubusercontent.com/4957600/36784184-5cd07c86-1c33-11e8-8dd8-45ee513aeece.png)
The 3.1.5.2 update caused any chisel blocks to no longer use their connected textures and also ones that were in the world, had a weird graphical glitch.

**Comment by b0bst3r** [comment]
Are you using Optifine?

**Comment by jamzam90** [comment]
Im not using it.
