### ISSUE TITLE
Nether Portal Won't Teleport

### ISSUE THREAD

**Issue by coledracon** [TheLimePixel/Modern-Skyblock-3#205]
When entering the nether portal the animation occurs, but it won't teleport anywhere. Tried to build a second portal to get back to overworld and it does the same thing.

**Comment by Jakrippr** [comment]
i am having the same issue in my gated play thru and have been trying to figure it out. have even started a second world to try and replicate it


Edit: I am not sure what is causing it but try killing yourself my portals started working again. Maybe FTB utilities chunk loading

**Comment by coledracon** [comment]
I just did the spawn command and flew back to my base.....I will try some other things tonight to see if I can narrow down the issue.

**Comment by coledracon** [comment]
Just realized there was an update with a patch, I will update and see if that fixes the issue.

**Comment by mckulich** [comment]
if it will not fix your problem, i had same issue and i just killed myself and it fix it for me :D
