### ISSUE TITLE
Twilight forest portal non functional

### ISSUE THREAD

**Issue by hossumquat** [TheLimePixel/Modern-Skyblock-3#206]
I completed the blood quests and unlocked the twilight forest quest line, so I went to the first tab and claimed that quest.  First quest in the twilight forest quest line is to create a portal, so I did as described in the text of the quest book.  Everything works up to the point of jumping in it.  Nothing interesting occurs.  I just stand there.  Waila (or whatever it is) shows it as a twilight portal, even though it looks more like a nether portal (sounds like one too).

**Comment by b0bst3r** [comment]
What version and what are you throwing in the water to activate it?

**Comment by hossumquat** [comment]
version 3.1.5.2, and I'm throwing in a dragon stone to activate it.

**Comment by b0bst3r** [comment]
Tested in 3.1.5.2 SMP and it's working fine can you give me more information please.

Server or Single Player?
Any mods added or removed?
Did you make the portal before an update or after you updated?
If you destroy the portal and remake does it work or not?

**Comment by hossumquat** [comment]
Single Player.  I'm playing 3.1.5.2 default as installed via the twitch launcher.  So no mods added or removed.  I had made this portal with a previous version of the pack (3.1.2 maybe?).  Destroying and remaking the portal still doesn't fix.  Same problem.  I could record a little video to demonstrate if you really wanted, but I doubt that would really be very helpful.

**Comment by hossumquat** [comment]
So could I issue a console command or something to get it working?

**Comment by TheLimePixel** [comment]
Killing yourself should fix it.

**Comment by hossumquat** [comment]
Awesome, thanks.  That did work. :)
