### ISSUE TITLE
Cooking for blockheads Crash/Freeze

### ISSUE THREAD

**Issue by Zepic** [TheLimePixel/Modern-Skyblock-3#207]
So i just got the Cooking for blockheads 1 then i smelted it to a cooking for blockheads recipe book thing.
So naturally i open it to check what i can make and i see ambrosia, and from loot-bags i've found out its really good stuff.
So clicking it results in the game freezing then shutting down internal server and sending me to the multiplayer tab. Keep in mind i'm playing on singleplayer and it does not close the game.
This is a gif of what happends when i click it in the book. [https://gyazo.com/c51c9ad8e57cd6beb2f4afb2fcdb8fe3](url)

**Comment by b0bst3r** [comment]
link is a 404

**Comment by Zepic** [comment]
Github url function worked in preview. i guess not in the post.
https://gyazo.com/c51c9ad8e57cd6beb2f4afb2fcdb8fe3

**Comment by TheLimePixel** [comment]
It's non-fixable mod interaction. Just don't do that.
