### ISSUE TITLE
Accidentally unlocked everything

### ISSUE THREAD

**Issue by Vesmiros** [TheLimePixel/Modern-Skyblock-3#209]
Hi, I'm playing Staged Mode on single player.
Doing quests from these chapters:
Mystical Flowers
Basic Farming and Automation
Better Storage

I've just finished the last quest from Better Storage so I got new stages unlocked, BUT i clicked the RELOAD QUESTBOOK and EVERYTHING unlocked... I know it says I should back my saves up... well I didn't. Is there a way to completely reset my quest and stage progress? I'm ok with redoing all the quests if only it means I won't loose my world.

Thank you,
Miroslav

**Comment by TheLimePixel** [comment]
Revert to a backup. Twitch backs up your worlds after you update.
