### ISSUE TITLE
Osmiridium - mistake or intended ? (Iridium)

### ISSUE THREAD

**Issue by mckulich** [TheLimePixel/Modern-Skyblock-3#211]
So i am playing last version of pack - gated. I am in stage where i have opened embers and tinkers and to move on to thermal i have to make 64x manyullyn, 64x aluminiumbrass, 32x osmiridium and 16 flame barrier. But i have problem with osmiridium, bcs iridium is gated behind advanced resources (need ar stage first), to make iridium alchemical dust i need some black ball but it is restricted item, so i cant create iridium this way, another way would be uu-matter, but come on to make 32x osmiridium ingot i would need 16x iridium ore and it is a massive amount of energy to create uu-matter (80x uu-matter = 5160 scrap which will be need to create that amount of uu-matter and then 16 iridium ore , So my question is.... is it intended like this? Or am i missing something and there is another way how to create iridium, so i can move on ?

**Comment by b0bst3r** [comment]
Intended and you can get iridium by washing stone, yes it's rare but it's doable (I did it this way) and you only need 16 dust to make 32 Osmiridium.
