### ISSUE TITLE
quest book broken

### ISSUE THREAD

**Issue by BudderEFS** [TheLimePixel/Modern-Skyblock-3#212]
my quest book doesnt have any quests and has the default minecraft background, it was working last night what happened

**Comment by SamboyCoding** [comment]
Read the "Notes on Better Questing" in the pack description visible [here](https://minecraft.curseforge.com/projects/modern-skyblock-3-departed)

**Comment by TheLimePixel** [comment]
If it doesn't have any quests /bq_admin default load should work.
