### ISSUE TITLE
Evilcraft <-> Colossal Chest Bug

### ISSUE THREAD

**Issue by SamboyCoding** [TheLimePixel/Modern-Skyblock-3#217]
If mobs die from falling on top of a colossal chest, then evilcraft spawns a blood block on it and everything in the chest is lost.

We lost about 4 stacks of every mob drop to this in our mob trap.

**Comment by TheLimePixel** [comment]
That's just how those 2 things work. You shouldn't put a colossal chest below a mob trap, especially not the core.

**Comment by SamboyCoding** [comment]
It wasn't the core, just one of the wall blocks.
