### ISSUE TITLE
MegaLoot Samurai Helmet Provides 909 Luck

### ISSUE THREAD

**Issue by Sebe47** [TheLimePixel/Modern-Skyblock-3#221]
Version 3.1.5.3

I dont think that this is intended

![image](https://user-images.githubusercontent.com/6533550/36946343-df6aeb14-1fbb-11e8-8120-b688b16c69b0.png)

**Comment by Zepic** [comment]
Not a bug

**Comment by Sebe47** [comment]
So is it meant to be that strong?

Luck 909 is realy Overpowerd :-D 

All the Rib Bones in my Inventory comes from only a few Mobs

**Comment by Zepic** [comment]
It is quite over powered but as you can see here it has been reported and pixel added it as not a bug.
https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/194
