### ISSUE TITLE
QOL Mod suggestions

### ISSUE THREAD

**Issue by RustyXXL** [TheLimePixel/Modern-Skyblock-3#227]
Here are some suggestions that don't change a lot gameplay wise but improve quality of life. Thanks for your consideration.

AppleSkin ( https://minecraft.curseforge.com/projects/appleskin )
Adds more information to the Food Bar and food item tooltips

Overpowered armorbar ( https://minecraft.curseforge.com/projects/overpowered-armor-bar )
Allows the Armor Bar to wrap around similar to the health bar

Stepup fix ( https://minecraft.curseforge.com/projects/stepupfixer )
Fixes the Vanilla AutoJump feature

Ungrabmouse ( https://minecraft.curseforge.com/projects/ungrab-mouse-mod )
You can assign a hotkey to ungrab the mouse from the window without having to open a gui, thus allowing to change the window while having the normal view still active.

Also the following mod slightly changes the wither skelly mechanics and thus has some gamemechanic changes, but I still would enjoy these changes.

Wither Skeletons tweaks ( https://minecraft.curseforge.com/projects/wither-skeleton-tweaks )
Changes some Wither Skelly mechanics.

Additionally I would really like to have Dank Null ( https://minecraft.curseforge.com/projects/dank-null ) and the Exchangers ( https://minecraft.curseforge.com/projects/exchangers ) mods available without having to add them myself. I just love those mods, so sorry for sneaking these 2 in here. ;P

**Comment by TheLimePixel** [comment]
1. Yeah, I might as well add it since Quark only displays the hunger value.
2. Quark already does that
3. Some mod already fixes it
4. I might as well
5. Breaks progression
6. No and no. Other mods in the pack already add that (Astral Sorcery adds the Replacement Rod and Open Blocks adds the Dev/Null)

**Comment by RustyXXL** [comment]
Didn't know Quark added 2 and 3, I always add 1-4 without big thoughts, and usually don't play with quark to much. ;)
5 I can understand, it isn't that important in this pack anyway, it's just a mod I tend to add in many non-skyblock packs. :)
The Dank Null however offers a lot more features tham the dev/null from open blocks. It has more slots, can be extracted from via the docking station, is upgradeable to hold more than 64 blocks etc. It is very powerfull, so I still can understand if you don't want it, but I still think it would be nice to have and still will add it myself...it helps immensly when in the aether or twilight forest to collect nice building blocks...:P
And I'm simply used to the exchangers mod...I will look into the astral sorcery wand once more....only tried the  botania wand, and while being cool, it severly lacks in the options department ;)
