### ISSUE TITLE
Cannot Install Modpack

### ISSUE THREAD

**Issue by sticklin10** [TheLimePixel/Modern-Skyblock-3#231]
Whenever attempting to install the pack i get the error:

"Addon Install Error. Error: Failed to get mod loader from the manifest"

Have done a clean install of the launcher and changed the file locations.
Running as administrator as well.

**Comment by dydokamil** [comment]
Same here on a mac: "Failed to get mod loader from the manifest".

**Comment by MrSelenix** [comment]
I can only assume you're trying to install v3.1.5.3? If so, neither can I. However you can install v3.1.5.2 and that does work. Maybe there's an issue with a mod in the latest release that makes it not downloadable ¯\_(ツ)_/¯
