### ISSUE TITLE
Endermen breaking blocks

### ISSUE THREAD

**Issue by kokorosss** [TheLimePixel/Modern-Skyblock-3#237]
Which mod let Endermen breaking blocks,the update didn't disable it so I want to find the mod config to do that.....

**Comment by syrun97** [comment]
did "/gamerule mobGriefing false" ?
https://minecraft.gamepedia.com/Enderman#Moving_blocks

**Comment by kokorosss** [comment]
They are  breaking blocks not moving blocks ,did the command work for breaking block?

**Comment by TheLimePixel** [comment]
That was disabled ages ago. Are you on the latest version?

**Comment by kokorosss** [comment]
I just update to a new version, but it keep breaking the block I place, so I want to know which mod it is......

**Comment by TheLimePixel** [comment]
Either way, it's not quite an issue.
