### ISSUE TITLE
Crab tons of "Unable to resolve texture due to upward reference" in log

### ISSUE THREAD

**Issue by syrun97** [TheLimePixel/Modern-Skyblock-3#238]
[17:21:11 ]~ [17:23:32] at this, "Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all.json" is spammed
https://pastebin.com/gDnKuRcR
version: 3.1.5.3 and disabled iChun's BS Mods(including coremod), enderzoo(why add this on skyblock?), enderman evolution(I HATE ENDERMAN),minimap(cuz im running on potato), tipthescale(inserted optifine =this mod do nothing but eating my ram) and itemzoom(what this do?), installed optifine HD C9 ultra(optifine=more fps on potato),Laggoggles FORGE-1.12-4.1(to hunt the insane frame drop)

**Comment by EmosewaPixel** [comment]
What were you looking at?
