### ISSUE TITLE
Crash when opening

### ISSUE THREAD

**Issue by turningpages** [TheLimePixel/Modern-Skyblock-3#24]
Hi
I am having a problem opening the modpack from the twitch launcher. 
When i Launch it i almost immediately get an error from mojang that the game has crashed.
I have reinstalled it multiple times and have repaired the modpack. I have not change anything of the modpack and the correct RAM is allocated.
 
This is the crashlog:
https://pastebin.com/HGsZawNV

Thank you in advance for any help.

**Comment by Fababfan** [comment]
Hey. I don't know, if this would help, but if you play the most recent version of the pack, you should launch it with the version 2608 of forge, not 2607.

**Comment by TheLimePixel** [comment]
It doesn't matter

**Comment by turningpages** [comment]
I tried it, but unfortunately still doesn't work...
