### ISSUE TITLE
Astral Sorcery Telescope issue

### ISSUE THREAD

**Issue by logicalghost** [TheLimePixel/Modern-Skyblock-3#242]
Unable to get the telescope to work properly with Astral Sorcery after update 3.1.5.3
Version of Astral Sorcery is 1.8.5
If I try using the telescope it disappears or does nothing at all.
If I try and break it with an axe after it has disappeared the game will crash.

The game crashed whilst playing level event
Error: java.lang.IllegalArgumentException: 
Cannot get property PropertyEnum{name=machine, clazz=class hellfirepvp.astralsorcery.common.block.BlockMachine$MachineType, values=[telescope, grindstone]} 
as it does not exist in BlockStateContainer{block=chisel:cobblestone2, properties=[variation]}
![telescope]

(https://user-images.githubusercontent.com/37166095/37130795-c3357630-224a-11e8-92b7-4da2dae5bdb4.png)

**Comment by logicalghost** [comment]
In case it matters the issue is occurring when either the Native Launcher Java or the latest version of Java 1.8.0.161 are used. Although I was able to get the telescope to work one time while switching between the two.

**Comment by TheLimePixel** [comment]
You are carrying it.

**Comment by logicalghost** [comment]
I am able to pick it up and carry it but in this case I am not. If I pick it up and move it to a different location I am still not able to use it by right clicking with an open hand or even with another item in my hand.

**Comment by Elvi81** [comment]
Click the legs of the telescope, it will react.

**Comment by logicalghost** [comment]
The legs of the telescope work, thanks. That is an odd hit box but at least I know it is not completely broken. There is still an issue though where if you pick it up and move it you get the result in the attached picture and if you try and break it with either a tinkers or vanilla axe it causes the game to crash. I have not tried it with other tools.
