### ISSUE TITLE
Duping with CarryON and Black Hole Tank/Unit

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#248]
did you miss me? I have not heard from me for a long time. Unfortunately I found a small duping bug again.

pick up the black hole tank or unit with carryon and it doubles up.

can you change the config like I did? Thank you. Screenshot is below
https://screen.pudding.tk/2axuwatx26.png

**Comment by TheLimePixel** [comment]
Apparently it's been fixed in the latest IF version.
