### ISSUE TITLE
I can't get Draconium Ore in Void Ore Miner

### ISSUE THREAD

**Issue by 1004452714** [TheLimePixel/Modern-Skyblock-3#249]
I want get some draconium ore,  so I build  Void Ore Miner  Tier 1and 2。
But I get this 
![image](https://user-images.githubusercontent.com/28773469/37202815-a1cf17ee-23c6-11e8-8484-bc52b7dcd6a4.png)

not this 
![image](https://user-images.githubusercontent.com/28773469/37202833-b309f3bc-23c6-11e8-8743-53004beb5355.png)

**Comment by ghost** [comment]
same here

**Comment by hossumquat** [comment]
You can just place it and break it again with silk touch to get the proper ore.  That's what I've been doing.

**Comment by b0bst3r** [comment]
I just throw mine into the Mek ore processing line and even though it doesn't give you any "uses" in JEI it processes just fine as ore.
