### ISSUE TITLE
weird stage issue

### ISSUE THREAD

**Issue by DODOMAN300** [TheLimePixel/Modern-Skyblock-3#253]
![2018-03-10_17 49 14](https://user-images.githubusercontent.com/36645630/37244103-0c1a2ef8-2495-11e8-9046-123f68b388b5.png)
![2018-03-10_17 49 15](https://user-images.githubusercontent.com/36645630/37244105-0cfe96a6-2495-11e8-833d-ad2e808fde35.png)
i finished basic resources and basic tinkering and opened mystical flowers basic farming and automation and better storage but still it doesnt let me acces to hoppers or worms

**Comment by TheLimePixel** [comment]
Claim the quest.
