### ISSUE TITLE
Planet Progression not working properly?

### ISSUE THREAD

**Issue by hossumquat** [TheLimePixel/Modern-Skyblock-3#254]
I am guessing something is not right.  I've launched 7 different satellites but I keep getting the same set of researches over and over.  I've been to the moon and am trying to unlock mars now.  I've gotten research and unlocked the moon, neptune, uranus, jupiter, mercury, saturn, triton, titiania and titan.  All I'm getting is more researches for those.  My current total researches are as follows:

5  Moon
10 Neptune
13 Uranus
3 Jupiter
22 Mercury
14 Saturn
13 Triton
18 Titania
19 Titan

All that and yet I can't get even one research for mars?  Seems like something is bugged here.

**Comment by TheLimePixel** [comment]
It's random
