### ISSUE TITLE
Modpack crashes while indexing ingredients in the pre-title load screen

### ISSUE THREAD

**Issue by dpcollier128** [TheLimePixel/Modern-Skyblock-3#255]
I haven't had issues like this with the pack before... not even with this version of the pack. It started happening yesterday (March 9th) and hasn't cleared up since scanning for viruses, updating java, updating my display drivers, and cleaning up unrelated parts of my system. It's obviously a memory issue, but I can't seem to expand my operating memory allocation past 7282mb within the Curse/Twitch launcher while I have it set to at least a full 8gb. While investigating the issue on my system, I've seen my CPU usage nearly max out for all my cores and the rate of pack loading significantly slow down towards the end.

I haven't been able to fix this issue for myself so far, and the game is crashing at pretty much the same spot each time I try to boot it up with this pack. If there is already a solution to my problem, I don't know how to find it or where. I'll try either repairing my installation or cloning it afresh, but I doubt that will fix the problem.

Here is a pastebin of my crash log: https://pastebin.com/B46C4gbX

I've really enjoyed playing with this pack. Even if my problem can't be solved here, I would like to know of a support forum where I may continue troubleshooting it. Otherwise, I may have to wait for the next pack version before I try running it again.

**Comment by dpcollier128** [comment]
Well, I managed to create a fresh installation then import my preferences, saves, and settings from the old, non-working installation. The old installation still doesn't start up properly, but I suppose that a fresh build can't hurt much. I'll see if this new installation breaks in the way the old one did. So far; so good.

**Comment by b0bst3r** [comment]
Which version of the mod pack is this?

**Comment by dpcollier128** [comment]
3.1.5.3

**Comment by b0bst3r** [comment]
Well according to that crash log 

 java.lang.OutOfMemoryError: GC overhead limit exceeded

Not enough RAM, however 8GB which you have assigned is enough, I know people who run it on 6.

So have you added any mods?

Also you may have updated Java but the Twitch launcher will continue to use an old version unless you instruct it to do otherwise, in your case it's running - 1.8.0_25 which is old.  See https://goo.gl/cCcNu2

**Comment by TheLimePixel** [comment]
Well, the amount of RAM it uses depends on your CPU.
