### ISSUE TITLE
Trapped in the Nether

### ISSUE THREAD

**Issue by EchartDenzari** [TheLimePixel/Modern-Skyblock-3#257]
After the last update, whenever I head into the nether, I can't use the portal to return! I'm stuck here and I'm not really sure how to get back to keep playing the pack!

**Comment by redsdracomancer** [comment]
I have had problems with nether as well occasionally I am unable to go threw, or come back from then nether on my server.

**Comment by hossumquat** [comment]
Should probably use the "teleport" feature of journey map waypoints to get back.  You do have a waypoint in the overworld I hope?  I don't know if teleporting should be enabled or not but it is in the current version.

**Comment by TheLimePixel** [comment]
Just go to spawn.
