### ISSUE TITLE
Quest line breaking

### ISSUE THREAD

**Issue by zigzagmzn** [TheLimePixel/Modern-Skyblock-3#261]
I quit to the title page to take a break and when I reopened I started getting the quest progression bells back to back. Upon opening the questbook all of the quest appear to be opened however I cannot access any of them whether they were previously unlocked or not. This is the second time this has happened and the only I can continue with my save is to delete the pack and reinstall then restore my last backup.

**Comment by rolovis** [comment]
Same problem. Was using staged progression. Looks like the quests to unlock the next stage are getting auto-completed, but in the quest book they're just titled "New Quest".
