### ISSUE TITLE
Reliquary super drops

### ISSUE THREAD

**Issue by kmork1** [TheLimePixel/Modern-Skyblock-3#265]
So after I killed an enemy with a weapon called inspiration from mega loot enemies started dropping between 30 - 80 of their reliquary drops. Like I’d kill one creeper and 64 catalyzijg gland. I’m on version 3.1.5.3 of the pack.

**Comment by syrun97** [comment]
mega loot item w/ luck make that. and that is "intended".

**Comment by kmork1** [comment]
Is it supposed to permanent  Bc it happens with whatever I swing. Fist wood planks anything

**Comment by RustyXXL** [comment]
The Luck is on the MegaLoot helmets and is independant from the held item.

**Comment by kmork1** [comment]
Ahh ok thanks
