### ISSUE TITLE
Quest complete, new quest keeps popping up

### ISSUE THREAD

**Issue by GeronVanDenHam** [TheLimePixel/Modern-Skyblock-3#268]
after i logged out of the world and logged back in again, i kept on having this message of a quest onlocking, and then completing, and then unlocking again. when i opened up the questbook, the kichtenmode seemed to have openen, while i was already playing in gatted mode. quest 2 times. I then tried to reset the questbook but nothing changed. 
picture of what I see: 
https://ibb.co/bMjZkH

**Comment by TiuTalk** [comment]
I have the same issue 👍

**Comment by Itadiki** [comment]
Same problem

**Comment by GeronVanDenHam** [comment]
fixed it by using the command to clear the questline, then restart the client, then go to creative mode and cheat in all the items to complete the quest i had so far, and throw them in the void after the quest was updated.
