### ISSUE TITLE
Porc Faucet/channel does not work on Crucible

### ISSUE THREAD

**Issue by StephJ2Fan** [TheLimePixel/Modern-Skyblock-3#27]
Version:3.0.1 and 3.0.2 both.

When trying to place a faucet on a crucible to retrieve lava into clay barrel, it does not work. Also, the item disappears completely.

**Comment by Ravalli03** [comment]
I may be wrong, but I think that faucet is made to work with tinkers

**Comment by StephJ2Fan** [comment]
You were able to use the porc faucet/channel in MS2 on the crucible to put it in the clay barrel.

**Comment by lavraleksej** [comment]
Crucibles seem to cancel any interaction with them as part of "you cannot use buckets on crucibles", you have to shift-click to place a faucet on one

**Comment by TheLimePixel** [comment]
Yeah, you need to be sneaking while placing it.
