### ISSUE TITLE
Opener can copy items

### ISSUE THREAD

**Issue by mpeilun12** [TheLimePixel/Modern-Skyblock-3#270]
When Tinker Crafting Table connected Opener, use Tinker Crafting Table let item enter opener that you can see the item in the Opener constantly copy

**Comment by shadow306k** [comment]
For want of lots of diamond tools to grind down, I've not been able to replicate this.

**Comment by TheLimePixel** [comment]
What Opener?

**Comment by Wigalot** [comment]
I'd take a guess he means the lootbag opener
