### ISSUE TITLE
 Light Gems Quest - Fluorite

### ISSUE THREAD

**Issue by Topside08** [TheLimePixel/Modern-Skyblock-3#272]
The quest is calling for the NuclearCraft Version
![2018-03-15_23 55 11](https://user-images.githubusercontent.com/37430351/37504276-a962cc34-28b3-11e8-94cd-d39cc9b90cc2.png)

I think you meant it to call for the Silent's Gems Version
![2018-03-15_23 55 23](https://user-images.githubusercontent.com/37430351/37504277-ab917456-28b3-11e8-88a4-ab98616a4560.png)

**Comment by mcdodge34** [comment]
I have this exact same issue at the moment, lucky for me, it didn't block progression, but unsure if gated mod needs them, I'm unable to complete this one, will probably try in next version.

**Comment by Wigalot** [comment]
You shouldn't be unable to complete it as fluorite (NuclearCraft Version) still comes from same place the rest of the light gems come from. Crushing and washing end stone. Also, I do believe the two variants are interchangeable in recipes. :)

![image](https://user-images.githubusercontent.com/37457017/37569357-0cd77072-2ad9-11e8-94b6-350f01326e68.png)

![image](https://user-images.githubusercontent.com/37457017/37569360-14800460-2ad9-11e8-8747-883c9692a832.png)

![image](https://user-images.githubusercontent.com/37457017/37569329-9df9c420-2ad8-11e8-95c1-f1e244ecf7ed.png)

![image](https://user-images.githubusercontent.com/37457017/37569337-b598c234-2ad8-11e8-9977-26a5cc455d36.png)

**Comment by Topside08** [comment]
@Wigalot I didn't know you could get it that way I was jumping around to the little blobs of endstone ore
@EmosewaPixel thanks for all the hard work you put into this modpack
