### ISSUE TITLE
No recipe for cold cloud parachute from The Aether

### ISSUE THREAD

**Issue by Wigalot** [TheLimePixel/Modern-Skyblock-3#275]
I can't craft the cold cloud parachute to complete the quest for it. No recipe is shown in jei but there is a recipe for the gold cloud parachute. 

I'm playing version 3.1.5.3

**Comment by mckulich** [comment]
i just encountered same issue

**Comment by Wigalot** [comment]
Oddly enough the higher tier gold parachute  is given to the player upon entry to the aether.

**Comment by mckulich** [comment]
i know right, you can even craft it in player grid, but that doesnt work for cold one, anyway it is just minor bug, they will just add recipe and it will be fine
