### ISSUE TITLE
Nether Portal not teleporting

### ISSUE THREAD

**Issue by oOMonkeytimeOo** [TheLimePixel/Modern-Skyblock-3#278]
My nether portal has stopped working. It lights up and makes the visual and sound effect, but never teleport's me to the nether. I have tried moving it, including moving it over 1600 blocks away and I still have the same problems. I loaded a new map and made a portal and it worked fine.

**Comment by TheLimePixel** [comment]
Killing yourself fixes it.

**Comment by E404-N0-1** [comment]
It may be a silent’s gems bug I became immune to any and all damage in the nether then when I left I couldn’t go back and I was still immune,(tried fall damage and diamond spikes) it wasn’t til I switched off my flight chaos gem (doing so gave me fall damage) that I was back to normal and able to return to the nether
