### ISSUE TITLE
Calculator Wrench not craftable

### ISSUE THREAD

**Issue by therodet** [TheLimePixel/Modern-Skyblock-3#279]
The recipies for the required Reinforced Sword and Reinforced Pickaxe conflict with Silent's Gems, and the resulting tools don't work for crafting the wrench.

**Comment by TheLimePixel** [comment]
Use the Wirktable.

**Comment by therodet** [comment]
... guess that's why the 'Tip' exists saying to read the quest descriptions. Apologies for that
