### ISSUE TITLE
Endermen breaking blocks - Bug/Suggestion

### ISSUE THREAD

**Issue by Fababfan** [TheLimePixel/Modern-Skyblock-3#28]
I tried to kill an enderman by putting some blocks above my head. Unfortunately endermen can break those blocks. And so I was killed, but when I respawned, the blocks were lying on the ground, but I couldn't pick them up. Furthermore they didn't despawn even an hour later.

**Comment by Ravalli03** [comment]
I'm also having the same issue

**Comment by Fababfan** [comment]
Now an enderman hunt me and destroyed a chest to reach me. The chest was an empty part of a half-filled double chest. When I opened the chest, the GUI showed a double-chest-interface and when I closed the GUI, the chest was repaired, as if nothing happened. But the broken chest was still lying on the floor, unable to be picked up.

In this context I wanted to suggest, that endermen shouldn't be able to break filled chests (if this isn't already the case).

Also I discovered that you can easily kill endermen without getting hurt, if you hit them through an open door, as they can't break doors because they are 2 blocks high. That makes their ability to brake blocks if you hit them pretty useless.
