### ISSUE TITLE
Spawner agitator and the cardboard box Server crash

### ISSUE THREAD

**Issue by redsdracomancer** [TheLimePixel/Modern-Skyblock-3#283]
So I put a spawner agitator on a blaze spawner I had set up for a while, and decided to move it so I grabbed a cardboard box from mechanism, and managed to get my server into a endless crash loop. Anyways restoring it to a back up but here are the logs: 
[crash-2018-03-18_02.15.37-server.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1822447/crash-2018-03-18_02.15.37-server.txt)

**Comment by MaartenKok8** [comment]
@EmosewaPixel A new version of PneumaticCraft has been uploaded to curse, containing this fix. When it's approved: https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized/files/2543426
