### ISSUE TITLE
TechReborn Roost Chickens

### ISSUE THREAD

**Issue by TheL0ki** [TheLimePixel/Modern-Skyblock-3#284]
The chickens wich supply refined iron, tungsten and tungsten steel seem to be broken as they can not breed or give items. Sometimes they do miracly work but most of the time the percentage exceeds 100% or count to the negatives.

![chicken1](https://user-images.githubusercontent.com/14993611/37567277-e1a22d5c-2ac4-11e8-8c8b-6f30bf13bd37.PNG)
![chicken2](https://user-images.githubusercontent.com/14993611/37567278-e1be6bfc-2ac4-11e8-87db-0c9da07d7c4a.PNG)
![image](https://user-images.githubusercontent.com/14993611/37567299-3ff72970-2ac5-11e8-887f-bea6b4bdbc52.png)

Happens at breedind and when in the roost.

MS3 v3.1.5.3

**Comment by TheLimePixel** [comment]
They aren't implemented into Roost yet. Breed them the regular way.
