### ISSUE TITLE
Unable to do damage to mobs

### ISSUE THREAD

**Issue by Zarizan** [TheLimePixel/Modern-Skyblock-3#285]
Playing in the latest version of Modern Skyblock 3 (3.1.5.3) on a server, i very shortly after starting encountered an issue, where i was no longer able to do damage to mobs with melee, but could still do so with ranged weapons.. 

I am the only person on the server who has that issue

**Comment by TheLimePixel** [comment]
Did you copy your SP world to the server?

**Comment by Zarizan** [comment]
No, started completely from fresh.. also, i tried getting an enderman to kill me, i restarted the server, but none of it helped

**Comment by TheLimePixel** [comment]
Ok, try running the server without FTB Utilities and deleting everything related to it (the local file and the ftbutils stuff in the world file). And then adding it back.

**Comment by Zarizan** [comment]
I have no idea how, but that did solve the issue..
Any info on what caused, so it hopefully wont happen again, and ill be able to warn the players on the server about it aswell?

**Comment by TheLimePixel** [comment]
FTB Utilities' protected chunks feature messed up for you.
