### ISSUE TITLE
JEI recipe for Wood Pile is Incorrect

### ISSUE THREAD

**Issue by Dystilled** [TheLimePixel/Modern-Skyblock-3#287]
It seems that the recipe for Wood Pile (Forestry) has been changed due to Oak bark and Wood Pile sharing a recipe. 

Changed to Oak wood in the following pattern: 
O X O
X  X  X
O X O

However in JEI it still shows the original recipe for Wood Piles which is rather confusing: 

O O X
O O X
X  X  X

This also means that there is no indication for those who know the forestry mod and are looking to use it that Wood Pile is actually craftable unless they experiment and guess the recipe.

**Comment by TheLimePixel** [comment]
It's a shapeless recipe.

**Comment by Dystilled** [comment]
The fact it's a shapeless recipe is not what I reported. 

Being a shapeless recipe doesn't change the fact that its only indicative recipe is incorrect in JEI

If you were going to have 1 recipe it should be one thats actually valid for crafting the item, not the recipe of a completely different item.

**Comment by TheLimePixel** [comment]
It's not. It  has the shapeless symbol.

**Comment by Dystilled** [comment]
*sigh*
