### ISSUE TITLE
Actually Additions not unlooking

### ISSUE THREAD

**Issue by Khalep** [TheLimePixel/Modern-Skyblock-3#288]
In my Version 3.1.5.3 Actually Additions wont unlock even though i completed all progression Quest up to A Basic factory. Heavy Machinery and Life in the Forest is also Completed. A True Blacksmith is half complet becaus i don't yet have acces to The Wither for a Beacon.
The Power of the Stars is unlocked but without Actually Additions i can't craft Rock CRystal Ore or Floating Crystal.
Any ideas?

**Comment by csokasg** [comment]
are you in staged mode?
if yes, are you completed the following (main) quests?
in basic farming and automation tab  "structured crafting" and "diamond spike"
AND in better storage  "uncolossal chest" and "obsidian chest" and "iron colossal chest"

**Comment by Khalep** [comment]
Yes i play staged mode. I did all the quest except for the iron colossal chest because it does not look like a progression quest in the questbook. I will try when i get home this weekend.

**Comment by TheLimePixel** [comment]
That's your issue then.
