### ISSUE TITLE
combustion heater spits redstone back out

### ISSUE THREAD

**Issue by bennyb1971** [TheLimePixel/Modern-Skyblock-3#29]
for some reason on my server the combustion heater setup (iron casing, iron heater) doesnt seem to accept redstone (to make glowstone). When you throw it in it spits it back out (redstone auto returns to inventory, like it seems you have a magnet on you).

**Comment by TheLimePixel** [comment]
You need a Nether Brick Casing. The Iron one can't reach high enough HU. You can see how much HU something needs in JEI.

**Comment by bennyb1971** [comment]
even with the nether brick casing it isnt accepting the redstone, does it need another heater too?

**Comment by bennyb1971** [comment]
the issue started when i updated my version of spnge to the latest version (to fix entering the nether causing a server crash) so i guess this is another sponge issue

**Comment by bennyb1971** [comment]
well since i updated sponge, the author released a few more updates of it, going to update sponge to latest again and will inform you if it is fixed

**Comment by bennyb1971** [comment]
nope, updating sponge didnt fix it, it looks like the combustion chameber doesnt seem to recognize redstone as an ingredient

**Comment by bennyb1971** [comment]
well i got it to work, but didnt know that the order you put ingredients into it matters

**Comment by TheLimePixel** [comment]
The ratio matters, not the order.
