### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Piincakes** [TheLimePixel/Modern-Skyblock-3#290]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Cyclops Core (cyclopscore)

I get this crash report when i try to launch the mod pack with native launcher, and [This crash report](https://pastebin.com/v99DRc3m) when I launch with the jar launcher.

i have restarted and re installed the mod pack. it still doesn't help.

**Comment by b0bst3r** [comment]
Pack version?
