### ISSUE TITLE
Forestry Worktable cannot craft staged recipes

### ISSUE THREAD

**Issue by zornor** [TheLimePixel/Modern-Skyblock-3#292]
Attempting to craft with any staged recipe with the Worktable will make a ghost item that will disappear when clicked on. The ingredients are recovered when the ghost disappears. I'm playing singleplayer.

**Comment by zornor** [comment]
how is it not a bug? :\ 

I've unlocked the relevant stages and I'm getting an unexpected result. I can craft the recipes with a regular crafting table, just not the worktable,

**Comment by TheLimePixel** [comment]
There is nothing that can be done about it. It's a fake player, it can't craft it.

**Comment by zornor** [comment]
i see, sounds like it'd be more trouble than it's worth to fix. no worries
