### ISSUE TITLE
Magneticraft Wind Turbine

### ISSUE THREAD

**Issue by Back2Attack** [TheLimePixel/Modern-Skyblock-3#295]
While attempting to craft the Magneticraft Wind Turbine in my single player it requires Fabric Mesh which has a 3x3 string recipe, when doing the 3x3 string recipe it is crafting String Mesh from Extra Planets and there seems to be no way around this.
How can I get around this or change the recipe for either of the items?

**Comment by TheLimePixel** [comment]
Use the workable.

**Comment by Back2Attack** [comment]
Saying "use the workable" doesn't help when I attempt to use the Extra Planets mesh it doesn't complete the recipe and there seems to be no other way to craft the wind turbine without the fabric mesh which I can't craft...

**Comment by b0bst3r** [comment]
Forestry worktable allows you to cycle through conflicting recipes.
