### ISSUE TITLE
Satellite not showing up in  Satellite Controller

### ISSUE THREAD

**Issue by martinschuberteu** [TheLimePixel/Modern-Skyblock-3#298]
Hi,
I've launched two Basic Satellites already in Satellite Rockets, but I can't select any in the Satellite Controller (also there is a typo in the Satellite Controller UI: it says "Satelltie ID"). I'm pretty sure I did everything correctly, but also didn't find much information on this.

**Comment by TheLimePixel** [comment]
Well you need to be on the Rocket till it leaves the atmosphere. Then you'll just fall off it.

**Comment by martinschuberteu** [comment]
Thank you! I couldn't find this information anywhere and didn't even think about staying on the rocket...
