### ISSUE TITLE
Blazes don't spawn in nether

### ISSUE THREAD

**Issue by Fababfan** [TheLimePixel/Modern-Skyblock-3#30]
I created a netherrack platform in the nether just as the quest book told me, to get some blaze rods from blazes. The platform is 7 blocks wide an 18-33 blocks from the point where I waited for them to spawn. But within altogether 10 minutes not a single blaze spawned. I also tried to put some nether bricks in between, but it didn't help. Am I doing something wrong or is it just bad luck?

**Comment by PiggyWhiskey** [comment]
Just bad luck I think.
I've gotten Blazes to spawn.

1. Make sure it's the vanilla Netherrack and not a Chisel version.
2. Try enclose it like an Overworld Mob Spawner. Blazes require Light less than 11.
3. 7 Blocks may not be enough room, I had a 20x4 platform and only got a dozen Blazes over 20 minutes.
4. Mobs won't spawn within 24 blocks of the player, so make it 24-32 blocks away.
4a. Outside of 32 blocks from the player, mobs may randomly despawn.
