### ISSUE TITLE
Ore Dictionary

### ISSUE THREAD

**Issue by Kuperus** [TheLimePixel/Modern-Skyblock-3#300]
I`m working on storage system, but it seems that various versions of Nickel and Silver are not working together in a compacting drawer, can they be added to the ore dictionary?

to recreate: make compacting drawer with 1 type of metal in it (silver or nickel) then try to add the other version of silver or nickel (tech reborn, thermal foundation and factory tech)

**Comment by tahg** [comment]
Drawers don't automatically work that way, You need to install a Conversion Upgrade into each drawer you want Ore Dictionary support for.
