### ISSUE TITLE
Little bug on latest version

### ISSUE THREAD

**Issue by GameReally** [TheLimePixel/Modern-Skyblock-3#301]
Colossal chest wall (silver) become (copper) after placing with diamond wand

**Comment by TheLimePixel** [comment]
Just don't do that.

**Comment by GameReally** [comment]
lel that was for a little bugfix XD just want to help sorry :P

2018-03-25 15:29 GMT+02:00 EmosewaPixel <notifications@github.com>:

**Comment by GameReally** [comment]
Hi! Sorry for the loss of time, I'm stuck and idk how to craft Iridium
Ingot, simply some crafting are blocked and there is no clear way to
proceed.. can you help me and maybe fix a little bit that section of the
questbook?

2018-03-26 16:30 GMT+02:00 Michele GameReally <notubeyb@gmail.com>:

**Comment by GameReally** [comment]
Hi, I really thank you since now for all your work you're doing! Just want
to ask if is normal to have unlocked "Underpressure" and have to unlock the
quest Assembly IO Unit but I can't craft an Hopper, Did i skip something
very important? Is not too much clear.. but I really love your pack and the
questbook! Sorry for every stupid email I send you but i feel a little
blocked..

2018-04-12 19:46 GMT+02:00 Michele GameReally <notubeyb@gmail.com>:
