### ISSUE TITLE
Botania Alchemy Catalyst Destroys Items and Only Works in certain directions

### ISSUE THREAD

**Issue by sunferth** [TheLimePixel/Modern-Skyblock-3#303]
These are two issues related to Botania on Modern Skyblock 3 3.1.5.3 When placing and using mana spreaders they can only fire in the south direction. I have tried breaking and placing but no mana is shot even though the animation of it shooting is played. And upon using the alchemy catalyst I have tried multiple times with different amounts of mana and regardless what items I throw in it, if it says I can complete the procedure it destroys the item and does not return the product.

**Comment by TheLimePixel** [comment]
The first one isn't a bug. The latter can't be reproduced.
