### ISSUE TITLE
Strange inventory lag when opening inventories

### ISSUE THREAD

**Issue by robertmr1** [TheLimePixel/Modern-Skyblock-3#305]
Yeah, I know, I should try fixing it myself. Yes, I googled what I could and whatever you can find on google, chances are I did it and it hasn't worked.
Everytime I open an inventory, be it the player inventory, ESC menu or chest, it has a 3-6s delay before opening the actual inventory and it's really irritating. Is there any fix to this?

**Comment by TheLimePixel** [comment]
This just sounds like lag.

**Comment by robertmr1** [comment]
Really? Did you close the topic?

**Comment by robertmr1** [comment]
There are numerous other people with the same problem on the internet

**Comment by TheLimePixel** [comment]
Yeah, that is just lag.

**Comment by robertmr1** [comment]
Ok, go ++++ yourself. Kisses

**Comment by robertmr1** [comment]
Yes, it's just lag, unusual lag. That's why I created the topic

**Comment by TheLimePixel** [comment]
It's TPS lag.

**Comment by robertmr1** [comment]
I have allocated 12 GB RAM to play, I don't understand why the lag appeared

**Comment by TheLimePixel** [comment]
Try the Lag Goggles mod. A common cause are Hoppers.

**Comment by robertmr1** [comment]
Didn't work unfortunately. I gave up playing this mod, for 6 days worked without this problem, but today began this lag when I open inventories. Unfortunately I will have to play another mod.

**Comment by Trelander84** [comment]
Certain sections of the JEI can cause lag when you open inventories (or hit e). Not sure if this is your issue but a warning. When I @tinkers for instance, it always lags. @robertmr1

**Comment by robertmr1** [comment]
Thanks, I already have finded this on internet, but no one has reaveal one solution unfortunatelly. @Trelander84
