### ISSUE TITLE
Itemducts corrupt the game when using with calculator machines

### ISSUE THREAD

**Issue by Kevincav** [TheLimePixel/Modern-Skyblock-3#306]
I used an itemduct with a calculator machine and the game crashed (and won't start up again) after whitelisting stone dust in the servo and turning redstone mode off.

Crash report: https://pastebin.com/UQmD4a49

**Comment by b0bst3r** [comment]
What mod pack version you playing?

**Comment by Kevincav** [comment]
3.1.5.1

**Comment by TheLimePixel** [comment]
Update.
