### ISSUE TITLE
Agricraft Issues

### ISSUE THREAD

**Issue by RustyXXL** [TheLimePixel/Modern-Skyblock-3#307]
1. When breaking Agricraft Cropsticks, Botania Sunny Quartz Slabs spawn in their place. The Drops are still being dropped, but the farmland (and potential Worms planted there) is reverted back to dirt.
2.  Lightlevel calculations seem a bit off. I converted my old non-agricraft farm to use for agricraft. the lowest light level in this farm is 9, which is enough for stuff to grow, but agricraft complains that there isn't enough light there for plants to grow.
3. I tried improving my wheat seeds. They don't seem to spread to the double cropsticks, only to single cropsticks, in which case their stats won't improve.
Crossbreeding Wheat + Potatoes did work, and at first it showed Carrots on the cropsticks, but when broken it gave me blue orchid seeds (along with the sunny quartz slab.

**Comment by TheLimePixel** [comment]
The first one is mentioned in the guestbook.
I think that the second one is intended because the required light level is in the book.
 The last issue is on my side. I had a feeling that it could happen.
