### ISSUE TITLE
Crop sticks/snad now require Kitchensink mode after update

### ISSUE THREAD

**Issue by FisfulOfDice** [TheLimePixel/Modern-Skyblock-3#309]
After updating to a new world and following the instructions in the update notes, I cannot create crop sticks or snad (which I was able to create before) in staged mode due to those two quests requiring being in kitchensink mode. As such, I cannot do any of the quests in Better Farming.

**Comment by TheLimePixel** [comment]
It's an OR requirement. You don't need kitchensink mode, you need to unlock Basic Farming

**Comment by FisfulOfDice** [comment]
I didn't realize that the seeds quest in Basic Resources had changed. I went and got potato seeds and completed that quest to unlock it, but even though the quests are unlocked I still can't create crop sticks or snad despite those quests being unlocked.
