### ISSUE TITLE
[SUGGESTION/OFFER] Server for MS3

### ISSUE THREAD

**Issue by MSandro** [TheLimePixel/Modern-Skyblock-3#31]
Hi, I really love your Modern Skyblock Mod Packs. The v3 is also really nice work! So I thought, maybe you want to readd a "official server" to the title screen. I have a nice root server with good hardware. There is already running a Modern Skyblock 3 server in version v3.0.2. It would be nice if you could add it as official server to your modpack.

IP: 188.68.40.215, Domain: yt-gamer.net, Port: 25566
Uptime above 90 % and regular reliable modpack update

The port is not on default because there is already run a other mc server.

Please let me know your requirements and wishes regarding the server, I will gladly implement them, if possible.

 
Regards

**Comment by TheLimePixel** [comment]
No. (that is all I'm going to say)
