### ISSUE TITLE
Survival Fishing Rod

### ISSUE THREAD

**Issue by KreatorB** [TheLimePixel/Modern-Skyblock-3#311]
It doe not catch anything anymore since the update to version 3.2

**Comment by RustyXXL** [comment]
I had that issue while wearing a luck helmet from Megaloot. Make sure you aren't wearing one of those.

**Comment by KreatorB** [comment]
I know I am wearing the samurai helmet, does that fall into that category

**Comment by RustyXXL** [comment]
If it has Luck, yes

**Comment by KreatorB** [comment]
looks like the LUCK on the HELP it the reason thank you
