### ISSUE TITLE
Mystical Agriculture/Aggraditions crops Mod Support

### ISSUE THREAD

**Issue by RustyXXL** [TheLimePixel/Modern-Skyblock-3#314]
The mod support (ie Phytogenic Insolator/Agricraft) for Mystical Agriculture Crops seem to be missing some Crops. Some of them work in neither the phytogenic insolator nor the Agricraft crops, some work only in agricraft.
I don't know if this is on your end, I just noticed it, while checking which Crops I could use with Agricraft.

Here's what I've found:
All of the Inferium seeds work in neither the Phytogenic Insolator nor Agricraft crops

Aggraditions:
Those three, I can see why they won't work with the PI, still the dragonegg seed requires a flux and should imo work like the other 2
Nether Star seeds only work on agricraft cropsticks
Dragon Egg Seeds work on neither
Awakened Draconium only on agricraft cropsticks

Agriculture:
neither Agricraft nor PI work for the following seeds
Fluxed Electrum Seed
Elementium Seeds
Dawnstone seeds
Steelleaf Seeds
Ironwood Seeds
Knightmetal seeds
Fiery Ingot Seeds
Skystone Seeds
Menril Seeds

The Phytogenic Insolator doesn't work with (but Agricraft crops do seem to work):
Black Quartz seeds
Rock Crystal Seeds
Star Metal Seeds
Aquamarine Seeds

Additionally the following Seeds can't be used for the Industrial Foregoing Bioreactor, while all others can:
Titanium Seeds
Mithril seeds
Fluxed Electrum Seed
Elementium Seeds
Dawnstone seeds
Steelleaf Seeds
Ironwood Seeds
Knightmetal seeds
Fiery Ingot Seeds
Skystone Seeds

**Comment by TheLimePixel** [comment]
Those are the last added seeds, so it's normal for them not to be supported yet.
