### ISSUE TITLE
Alchemy Catalyst Issue with Botania

### ISSUE THREAD

**Issue by KreatorB** [TheLimePixel/Modern-Skyblock-3#316]
So I have my Alchemy Catalyst from Botania setup and I throw a birch sapling in in order to obtain the jungle sapling and it is only consuming the Sapling. Note, it is using mana while this happens. I am doing this under Version 3.2 and ideas?

As a note, I did it using the Infusion Stone I would rather do it with Botania as it does not take 10 beans and most of my life.. ;-)

**Comment by TheLimePixel** [comment]
You are not the first person that this has happened to, but with only that information, I haven't been able to reproduce it.

**Comment by neograymatter** [comment]
Do you have endoflames nearby? I've seen this happen on a few different packs and it turned out that endoflames were consuming the newly created sapling instantly.

**Comment by TheLimePixel** [comment]
How did I not think of that? XD

**Comment by KreatorB** [comment]
oh,  I have my spreader 1 block away and around it in a half circle is the endoflames with an open crate on top dropping from a bonsai hopper.  I will test the distance tonight and see if it correct the issue. thank you

**Comment by KreatorB** [comment]
Okay so I move the mana pool 2 blocks away from the spreader and endo flames and that did not work. However 3 blocks of space from endo flames was the key. 3 Spaces is required. thank you
