### ISSUE TITLE
Weird botania mana burst

### ISSUE THREAD

**Issue by ZZaphodd** [TheLimePixel/Modern-Skyblock-3#317]
https://www.youtube.com/watch?v=jw9ji3uD8l0

I'm not that experienced with botania, but mana bursts seems collided with themselves and I've never seen like this before. Am I missing something about botania's special mechanics?

modpack version : 3.1.5.3
(it's not on the latest version, but.... I didn't see any related change between this version and the latest)

**Comment by ZZaphodd** [comment]
It seems be interdiction torch from reliquary make mana burst bounces.
Is it intented behavior in this modpack? then this issue might be closed as incorrect.

I spammed interdiction torches near botania flowers. because enderman/evolved one relocates dirt / grass block.

**Comment by b0bst3r** [comment]
Can't help this the mana burst is an entity and the torch affect entities, just don't put torches anywhere near your mana setup.  Use mega torches to stop the endermen from spawning.
