### ISSUE TITLE
Runic altar retrieval and machine/chest pickup conflicts(Shift+right click)

### ISSUE THREAD

**Issue by ZZaphodd** [TheLimePixel/Modern-Skyblock-3#318]
When player is right next to runic altar, player picks up the runic altar.
When player have a little bit more distance, item could be removed from the altar. 

It seems be pick up operation has shorter range.

If pick up operation(don't know which mod do that)'s distance restriction is intentional and for resolve 
the conflict, it might be good let players knows from tips.

TIPS : "Did you lift up the runic altar and get get frustrated? Step back and try again."

**Comment by b0bst3r** [comment]
Remap the "carry on" key to something else, shift right click is used in too many other things but that's what the mod defaults to.
