### ISSUE TITLE
Crash on loading 3.1.5.3 world in 3.2

### ISSUE THREAD

**Issue by Hibernating-Bear** [TheLimePixel/Modern-Skyblock-3#323]
Have had the same crash repeat 3 times, appears to be related to some food values from what i can gather from the crash report/s

Crash Report:
https://pastebin.com/RbGAnRwa

If you require anything else, more than happy to provide

**Comment by b0bst3r** [comment]
https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/17
