### ISSUE TITLE
Enviromental Tech unlocked yet not.

### ISSUE THREAD

**Issue by Elvi81** [TheLimePixel/Modern-Skyblock-3#324]
These images should explain what i mean.
I'm in gated mode.
Pack version 3.2 beta.
https://imgur.com/89Fbsh6
https://imgur.com/ccWXLIJ

**Comment by Bigbosseken** [comment]
I had to- /bq_admin edit and reset that quest (Environmental Tech) in Questbook tab. Then /bq_admin edit again and reclaim that quest to reactive it.

**Comment by Elvi81** [comment]
How do you reset it? can't seem to find anything that does this.

**Comment by Bigbosseken** [comment]
You have to be admin or have cheats on (easy way is to open lan and enable cheats). Then type in /bq_admin edit    it will let you edit your quest book. While in the book click on Questbook tab and click edit. Rest the quest, then complete it. Your going to want to type in /bq_admin edit again to set it back to normal. Then go back into the book and reclaim the quest.

**Comment by Elvi81** [comment]
There is no reset option in there and i'm the op of my server.

**Comment by Elvi81** [comment]
Still doing it after a reset and 3.2.0.1 update.
Before completion
https://imgur.com/h2OrmjC

After
https://imgur.com/XdAfnrr

Edit:
Only way to get it working was to use complete on quest 198.
