### ISSUE TITLE
Agriculture world breaking bug

### ISSUE THREAD

**Issue by irifted** [TheLimePixel/Modern-Skyblock-3#325]
If you have a water source tile next to dirt with crops on top, don't break the dirt without first clearing the crops on top.  The water block seems to fail to update and causes an irreversible world crash- loading up world leads to exact same crash and problem.   
Here is the pastebin of the crash- 
https://pastebin.com/6ARAbgrT

**Comment by Elvi81** [comment]
Can confirm, this does cause a crash on server atleast.
