### ISSUE TITLE
Enviromental Tech getting chiseled versions

### ISSUE THREAD

**Issue by Nazta** [TheLimePixel/Modern-Skyblock-3#326]
Tier 1-6 void resource miner gets all the different types of chiseled ice.
If not intentional, it's a simple json edit to fix it(for each tier).

```
{
  "target": "light_blue",
  "weight": 8,
  "id": "OD_PREFIX:ice"
},
```

To

```
{
  "target": "light_blue",
  "weight": 8,
  "id": "minecraft:ice"
},
```

It also picks up things like chiseled limestone and marble.

**Comment by TheLimePixel** [comment]
Well, it's not really an issue. It's simple enough to chisel them or use a drawer with a conversion upgrade to turn them into the default.
