### ISSUE TITLE
Quests don't complete unless all items are present in inventory

### ISSUE THREAD

**Issue by andremiller** [TheLimePixel/Modern-Skyblock-3#33]
Certain retrieval quests do not update incrementally when you acquire the items, but only update once you have all the items in your inventory.

For example:
Quest: Water Extractor
  Item: Water Extractor
  Item: Compressed Water Extractor

After crafting the Water Extractor the quest did not want to update. A Detect/Submit and re-opening questbook also did not update it. The Water Extractor was then used to craft a Compressed Water Extractor and again the quest would not update. Crafting another normal Water Extractor completed the quest right away.

Another example:

Quest: Basic Fluid Transfer
  Item: Unfired Porcelain
  Item: Porcelain Faucet
  Item: Porcelain Channel

Just having the Unfired Porcelain did not update the quest, and after consuming all the Unfired Porcelain I had to craft the Faucet and Channel it didn't update any of the items. I created another Unfired Porcelain and the whole quest completed.

I'm currently on 3.0.1, so not sure if this is fixed on other versions or intended. Also playing on a server with no additional mods installed.

**Comment by TheLimePixel** [comment]
If you started playing before 3.0.0.2, update your questbook. If not...

**Comment by andremiller** [comment]
Thank you. This was a new server installed with 3.0.1, but my client was updated from a previous version.
Updating the questbook fixed other quests that were in progress, so it looks like that worked!

**Comment by andremiller** [comment]
This issue appeared again after updating our server from 3.0.1 to 3.1, quests no longer update incrementally, but only after all items are present in inventory. It's doing this for all players on our server, and we did use the questbook to Reload Quests.

One particular example is the Sin Runes from Mystical Flowers. I had half of the runes in my inventory and clicking Detect/Submit did not update any of them, even after multiple tries of closing and opening the questbook. But as soon as I had all of them in my inventory at the same time the quest updated and completed.

EDIT: Still present in 3.1.1, tested after doing a quest reload and then trying to complete Regular Gems quest.

**Comment by andremiller** [comment]
I think I have resolved this. On a whim I deleted my client profile on Twitch and downloaded a fresh install, with a fresh client side config, and without any changes on the server, now the quests are updating incrementally again (tested with the Regular Gems quest).
