### ISSUE TITLE
Better Quest Completing Random Quests

### ISSUE THREAD

**Issue by nman130** [TheLimePixel/Modern-Skyblock-3#331]
Occasionally when I enter my world, it will show all of the quests in the "Questbook" tab under the Staged heading even though I started in gated mode. It will also take random quests in each of the tabs and complete them even though the stages are supposed to be locked. I'm not sure what causes this, but I get a "New Quest" quest completion notification multiple times upon logging in when this happens. I also can't reset this manually because I am unable to see the quest numbers. Is there a way I'm missing to see them? I've attached an imgur album showing some of the issues. I wasn't able to get a screenshot of the "New Quest" notification, but the rest is in the album: https://imgur.com/a/j4U6J.

**Comment by dragonup1793** [comment]
I have the same issue

**Comment by alexsch01** [comment]
@EmosewaPixel i have same issue makes it unplayable at this point if this randomly happens or when I click on update questbook quest plz fix love the modpack

**Comment by dragonup1793** [comment]
just go back to old version and you can still play
