### ISSUE TITLE
Missing mods

### ISSUE THREAD

**Issue by redsdracomancer** [TheLimePixel/Modern-Skyblock-3#332]
Not sure what happened but it appears that Agricraft for the server is wanting a different version of forge after the latest update.
[crash-2018-03-30_19.42.25-server.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1865062/crash-2018-03-30_19.42.25-server.txt)

**Comment by JohnTitor95** [comment]
My game also crashing on starting up after the update.

**Comment by TheLimePixel** [comment]
Well update the forge on your server.
