### ISSUE TITLE
Update issue in Staged mode

### ISSUE THREAD

**Issue by Creker231** [TheLimePixel/Modern-Skyblock-3#334]
Before Updating I had opened Basic Automation.
![base profile screenshot 2018 03 31 - 12 45 35 29](https://user-images.githubusercontent.com/28734231/38161984-7fd16a80-34e1-11e8-9cfe-c79be4df1645.png)
But now it says that this 
![base profile screenshot 2018 03 31 - 12 45 47 59](https://user-images.githubusercontent.com/28734231/38161985-83e3b614-34e1-11e8-9806-5849b64bae40.png)

**Comment by Gameriti** [comment]
Did you reload the questbook?

**Comment by Creker231** [comment]
yes

**Comment by TheLimePixel** [comment]
Changelog.
