### ISSUE TITLE
Agricraft

### ISSUE THREAD

**Issue by Gameriti** [TheLimePixel/Modern-Skyblock-3#335]
Ok so I'm really not sure whats wrong with agricraft but whenever you break crop sticks its spawns a block called "sunny quartz slab". And whenever you break mystical petal seeds it gives your a random flower seed instead of the seed you are supposed to get.
See Bug Here: https://youtu.be/sDSfmUmzwZE

**Comment by TheLimePixel** [comment]
Update.
