### ISSUE TITLE
Open Stages Problem---> Questbook doesnt give the command

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#337]
Please read it completely and do not close it directly.

I've already asked on Discord but there was no one who could really help me with that. You yourself do not have the problem so I or we are unique.

The problem is: After the last update (3.2 not the current one) came, the problem arose that the users on our server can no longer unlock stages.

The Basic Farming (bf) and Basic Automation (ba) were unlocked by a command. so far, everything is fine.
If you try to unlock another stage like chicken or embers or another, you can claim it but the command will not be triggered. The items that are locked are still locked even though the corresponding quest has been completed and the command has been claimed.

I hope I could describe it so that you understand it. On discord I had my problems with it.

As I said please do not close. If questions remain open please write.

**Comment by TheLimePixel** [comment]
Do you have any plug-ins stopping certain commands?

**Comment by ghost** [comment]
There are no plugins available to stop or cancel the commands. I also tried with a player to see if anything happens in the console. Again, I have to say that nothing happened. quest was claimed, command was not executed, nothing is in the console

**Comment by ghost** [comment]
looking for 3 days, we finally found the problem. it was due to spongeforge. with a downgrade to an older version, everything works fine now.

doesnt work with 1.12.2-2611-8.0.0-BETA-2993
and work with 1.12.2-2611-7.1.0-BETA-2990

might be helpful to test this even further and to send spongeforge.

**Comment by TheLimePixel** [comment]
You know how I feel about sponge.
