### ISSUE TITLE
Gated mode progression tiers randomly unlock

### ISSUE THREAD

**Issue by jaxx050** [TheLimePixel/Modern-Skyblock-3#339]
I booted up my game yesterday after playing for a few hours the day previously, and found that all of my quest tier nodes had mysteriously unlocked and duplicated themselves, with the lefthand pane showing everything in the tree, and the righthand pane having all the nodes that revealed themselves with only the "claim reward" console command left for most of them. The exceptions were Equivalence, which still had me having not completed it, and Mystical Crops, which showed me having completed it but not allowing me to click on it to unlock rewards. Picture: https://i.gyazo.com/d618c69686c1b9a62f23e392f7a0f236.png
Running the newest pack version in a single player world on Hardcore mode.
Edit: to clarify, I had only unlocked to the level of A True Blacksmith legitimately, with the exception of Tech Reborn. So everything up to that point. If there's a way to fully reset my quest progression I'd be happy to do that, I can just remake the stuff to turn in.

**Comment by kayrena** [comment]
I am having the same issue though not on hard core mode.

**Comment by TheLimePixel** [comment]
But yes, reset the book or roll back to a backup.
