### ISSUE TITLE
Crashes when doing certain actions

### ISSUE THREAD

**Issue by TheoVerhelst** [TheLimePixel/Modern-Skyblock-3#34]
Hi,

My game sometimes crashes when doing certain actions.
Here are two examples that happened recently:
* When removing a redstone torch (and indirectly activating a piston):
https://pastebin.com/8jrr0g1A

* When killing an Enderman:
https://pastebin.com/Pmh204gX

I allocated 6518 Mo of RAM to the game. Couldn't allocate more, since I have 8 Go.
My CPU: Intel Core i5-7200U @ 2.5GHz

**Comment by TheLimePixel** [comment]
What else was the Redstone Torch next to? A Crucible Inserter?

Edit: Actually, as I suspected, you tried moving a Crucible Inserter with a Piston. Why would you do that?

**Comment by TheoVerhelst** [comment]
Well, I wanted to dispatch items between two Crucible Inserters using two Hoppers and two Sticky Pistons, alternating with a redstone clock (I was too early in the game to craft a proper conveyor belt splitter, for example). But this kind of crashes happened quite frequently on my machine, not always with redstone. Sometimes the game freezes for like 30 - 60 seconds, and sometimes it totally crashes as shown above.

I know it's vague, but I was hoping that the logs above could help you spot a more general problem than this piston-related crash.

Cheers.

**Comment by TheLimePixel** [comment]
Well, the piston one is some weird mod interaction, so it won't be fixed. And on which version are you? The Evolved Enderman crash was fixed 2 versions ago.

**Comment by TheoVerhelst** [comment]
I'm using version 3.0.0.1, that must be why. Thanks for your time 😄
