### ISSUE TITLE
New update broke my QUESTBOOK

### ISSUE THREAD

**Issue by martinegui** [TheLimePixel/Modern-Skyblock-3#340]
Hey guys,
I was playing a few days I was at chickens stage, i playing the mode that you neeed to progress each mode but u can rush at mode if u wanna, BUT after this update my questbook broke, all the modes were unlocked and i had 2 QUestbooks trees exactly the same just separate for some centimeters.
I have my backup, I will restore it and try again, any way to do this work? Anyone with the same problem?

Thanks for your help

**Comment by dragonup1793** [comment]
had the same issue and all the mod author said is read the changelog and closed the report

**Comment by TheLimePixel** [comment]
No, I said read the pack description.

**Comment by dragonup1793** [comment]
quoted from your message 
Read the 3.2 Changelog .
--

**Comment by TheLimePixel** [comment]
In was a different issue.
