### ISSUE TITLE
new update broke movement

### ISSUE THREAD

**Issue by dragonup1793** [TheLimePixel/Modern-Skyblock-3#341]
when I load my world after running commands in patch notes i'm at 0,0  when i wasn't when i logged out and every time i try and move the world flips out and spins every time I try and move

**Comment by sreekrishn** [comment]
the new update version 3.2.0.1 deleted my world save
and it is not present in the backup folder
![capture](https://user-images.githubusercontent.com/36627174/38170380-f42d62b0-35a1-11e8-98a8-62609ec88a74.PNG)

**Comment by TheLimePixel** [comment]
Well, both of you revert to the backup that you got while updating.
