### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by IWriteAnarchy** [TheLimePixel/Modern-Skyblock-3#342]
Is the guide supposed to be like this?
![issue](https://user-images.githubusercontent.com/37946862/38170125-90b9db16-354a-11e8-9cd0-a878354acb2d.png)

**Comment by TheLimePixel** [comment]
April Fool's!

**Comment by Northbadge** [comment]
So how do you disable it?

**Comment by TheLimePixel** [comment]
You're stuck with it for the day. Although, I guess you can try changing the date on your computer.

**Comment by Northbadge** [comment]
So you put something irreversible, which prevents new players from getting basic starting info, into your modpack as part of April Fool's? May want to add an disable in a future don't you think...

**Comment by TheLimePixel** [comment]
It's not my mod.

**Comment by TheLimePixel** [comment]
Plus, all textures are saturated on April Fool's because of some mod. It's not really a day to play the pack.
