### ISSUE TITLE
Character has pig nose and noises

### ISSUE THREAD

**Issue by E404-N0-1** [TheLimePixel/Modern-Skyblock-3#343]
My silent gem sword also has eyes could anyony tell me what mod(s) this is and how to disable it the oink is annoying

**Comment by Ncrpts** [comment]
I think it's an april's fool gag, but can't pinpoint what mod causes it

**Comment by Vexillium** [comment]
ive been trawling through the config files for around an hour now and its a bitch to find it, its part of the hats mod but to get rid of it you need to play around in the config files, supposedly its being gotten rid of in the next update in a few days
- its the pig snout hat that can occasionally be found on hostile mobs but its hard coded to spawn on the player for now you can also get rid of it by collecting the hat and turning it on and off but good luck ACTUALLY doing it you can also apparently ditch it if your on a server and get it by killing each other to obtain the hat but yet again good luck actually finding a server for this pack.
I'm looking through the code registry right now if I figure it out ill post a code patch and INI line for you guys but tbh I'm not that great of a programmer I specialise in textures and art

**Comment by b0bst3r** [comment]
It'll all be over soon.
