### ISSUE TITLE
Magneticraft Light Iron Plate not ackcepted in any Immersive Engineering recipes

### ISSUE THREAD

**Issue by MatthiasMann** [TheLimePixel/Modern-Skyblock-3#345]
I'm using version 3.2.0.1 and I can't use any light iron/copper/etc plates made with the Magneticraft Crushing Table in any recipe of Immersive Engineering - like making copper wires.

**Comment by TheLimePixel** [comment]
Well, make IE ones. MagnetiCraft stuff doesn't work with other mods's stuff and vise versa.
