### ISSUE TITLE
Enviromental Technology q bug

### ISSUE THREAD

**Issue by devilsoul87** [TheLimePixel/Modern-Skyblock-3#346]
![bug](https://user-images.githubusercontent.com/37986606/38177466-c45a0db8-360a-11e8-80c2-d6281e11905e.jpg)
  I dont know what to do if i can start this q line if i was opened it before and not started before this new patch...

**Comment by TheLimePixel** [comment]
These quests are opened because they took the place of ones that were deleted.

**Comment by devilsoul87** [comment]
Yea, i got it, but i cant start this quest line, before i was opened it and now litherite q not starting... i tried with console commands try remove or retake it but still cant start it
