### ISSUE TITLE
Is Reliquary Pedestal Fishing Success supposed to be 0?

### ISSUE THREAD

**Issue by JohnTitor95** [TheLimePixel/Modern-Skyblock-3#347]
Kind of weird that the success rate for fishing pedestals from reliquary would be zero, gets rid of automation.

**Comment by JohnTitor95** [comment]
What, no response?

**Comment by TheLimePixel** [comment]
I haven't messed with the config for Reliquary.

**Comment by JohnTitor95** [comment]
That's weird, because it was set to a non-default value, that came straight from downloading the modpack.
