### ISSUE TITLE
Tier 6 - Artichoke requires Tier 7 - Lettuce -- Quests

### ISSUE THREAD

**Issue by Trelander84** [TheLimePixel/Modern-Skyblock-3#348]
Artichoke needs lettuce, lettuce needs celery. 

Possibly Tier 6 Should be

Celery
Lettuce

Tier 7

Artichoke

Edit: nothing stopping you from completing quests btw, all seeds look available, so just had to make em out of order. Just doesn't flow like the rest.

**Comment by TheLimePixel** [comment]
*facepalm^
