### ISSUE TITLE
Applied Energistics 2/Game Stage interaction

### ISSUE THREAD

**Issue by Caspygh** [TheLimePixel/Modern-Skyblock-3#35]
There's a weird interaction between AE2 and Game Stage in which you can't craft items unlocked through stages with an AE2 crafting terminal. I've taken a few screenshots in a test world to demonstrate this. When I checked the same recipe with a vanilla crafting table, the item was craftable. Also, using a pattern encoder (the block one, not the terminal) will show it's craftable but, when the pattern is created, it will be an invalid pattern, unusable with the AE2's auto crafting system.
https://ibb.co/hZ2vpR
https://ibb.co/bHUKG6
https://ibb.co/hUdqOm
https://ibb.co/e2qRw6
https://ibb.co/bEdqOm
https://ibb.co/mdWMUR
https://ibb.co/kG9mw6
https://ibb.co/dx6AOm
I haven't tried recreating this bug in multiplayer. 
Also, I should mention that I've turned off the AE2 channels and I installed the Appleskin mod for the visual representation of the food saturation but I doubt any of those two would conflict with the pack.

Edit: Pack version 3.0.2

**Comment by TheLimePixel** [comment]
Well, I can't reproduce it, so I'm going with.

**Comment by DoomSquirter** [comment]
using 3.1.1 this is still an issue.

bag opener for example.  the item shows up in the crafting window but you can't pull it out and actually take one.
