### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by Kandrina** [TheLimePixel/Modern-Skyblock-3#351]
i just updated to 3.2.0.1 now i get the following error:

[21:06:15] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod agricraft (AgriCraft) requires [forge@[14.23.2.2618,)]
Missing Mods:
forge : [14.23.2.2618,)

i did replace all the old mods, including forge

**Comment by redsdracomancer** [comment]
You just need to update forge on the server

**Comment by Kandrina** [comment]
i updated forge and it broke the map, i guess i need to reinstall the pack completely

**Comment by Kandrina** [comment]
ok, i reverted it back to what i had before, i did update forge
![image](https://user-images.githubusercontent.com/8957277/38219115-78f5a678-36d4-11e8-99a8-cc7865a9a6f6.png)

but i'm still getting the same error

**Comment by redsdracomancer** [comment]
use forge 1.12.2-14.23.2.2641

**Comment by Kandrina** [comment]
got it to work by renaming the forge file to minecraft_server.jar
