### ISSUE TITLE
Hoppers Not Craftable

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#352]
No Longer able to craft hoppers. This is after the pack update that separated Better Farming & Automation into their own respective questlines. This issue continues after re-loading quest book as BF was available to complete but BA was already complete. Any Help would be great.

**Comment by ghost** [comment]
Okay so I Fixed it by entering "/gamestage add @p ba" couldn't find this anywhere so ended up scrolling to line 1603 in the Default Quests JSON File. It probably has these commands somewhere accessible but thought I'd mention I couldnt find it :)

**Comment by RustyXXL** [comment]
Maybe that's why it is mentioned in the changelog for 3.2 and the changelog for 3.2.0.1 tells you to read the previous changelog? ;P
