### ISSUE TITLE
Remove Buildcraft Until Stable?

### ISSUE THREAD

**Issue by JohnTitor95** [TheLimePixel/Modern-Skyblock-3#354]
Buildcraft is in the pack right now, with no real warnings about stability other than the initial load saying it's in Alpha. Nearly anything buildcraft causes my game to crash. Placing redstone engine? Crash. Remove redstone engine? Crash. Place pipes? They sometimes glitch out, especially next to a lot of blocks, and guess what, also crash. Reading the in game manual? Crash. 

I think the mod should be either removed from the pack, or more clearly warned against until it is safer to use.

**Comment by TheLimePixel** [comment]
Nope. Everything works fine more me.
