### ISSUE TITLE
Crash report v3.2.0.1 (eating food)

### ISSUE THREAD

**Issue by chaos-synthesis** [TheLimePixel/Modern-Skyblock-3#357]
Game crashes when player eating "Ground Beef (Raw)"(mod Galacticraft Core). This may be not related to the modpack, but please take a look at the crash report: [https://pastebin.com/4V57GJRA](https://pastebin.com/4V57GJRA)

**Comment by TheLimePixel** [comment]
Yup, that's a GalactiCraft crash.
