### ISSUE TITLE
Thermal Upgade kits requires Kitchen sink mode?

### ISSUE THREAD

**Issue by Kipthare** [TheLimePixel/Modern-Skyblock-3#359]
I am in staged mode, and after a screw up with the most recent update (maybe test your work a bit before saying its all good) I had to reset my quest book to the beginning. I had previously finished the thermal enhancements section and worked my way up to it again. Only to find that the upgrade kits from thermal where still locked saying it required both Kitchen sink mode and thermal enhancements.

**Comment by TheLimePixel** [comment]
OR not AND

**Comment by Kipthare** [comment]
Looking at it right NOW says "Hardened Upgrade kit Requires: (AND) -Kitchensink mode -Thermal enhancements"
