### ISSUE TITLE
Cauldron Cleaning (drop rates)

### ISSUE THREAD

**Issue by moetrix** [TheLimePixel/Modern-Skyblock-3#36]
Is it normal that i have **super low drop rates** while cauldron cleaning? talking like **0.182% for iron** and **0.096% or something like that for silver** etc.
Nearly cleaned a stack of rock dust and haven't gotten a single ore drop, gems work fine though.
Playing on version 3.0.2

**Comment by TheLimePixel** [comment]
Yup
