### ISSUE TITLE
Server crash while upgrading from 3.1.5.3 to 3.2.0.1

### ISSUE THREAD

**Issue by mcdodge34** [TheLimePixel/Modern-Skyblock-3#362]
The more I try to love this pack, the more problems I get, its been 1 week that I try to upgrade the world that works fine in 3.1.5.3 to either the 3.2 or the 3.2.0.1 edition, I've tried everything I could think of this time, I use straight files and didn't add my usual mods (aroma backup and just a magnet thoses mods shouldn't be an issue but just in case I decided to use the untouched files just to be 100% sure), it keeps crashing with 2-3 random crash every single time, I've made enough progress that I don't wanna start again in a new world only to discover I'll be unable to upgrade to a newer version of your pack later on, I have no clue why my world does theses crash, the pack works #1 in 3.1.5.3 I'm not sure if I want to continue this adventure knowing that I will encounter bugs and problems in the 3.1.5.3 that are fixed in a version of the pack that I can't upgrade to. 

I understand you have a real life, but not supporting the ones that enjoy your hard work isn't going to make you a lot of friends. I'm usually pretty good at figuring the crash logs myself (I started playing modded Minecraft in the 1.2.5 era of Minecraft using my own modded servers), but this time, I'm clueless, even deleted every single bit of the dimensions in the world folder except compact machines, the overworld and the nether to see if that could fix the crash related to Galacticraft Venus, nope, it didn't work.

First I have to remove the Hats mod from the pack because I end up with this every single time I try to start the server with my world, got no problems, hats aren't needed when we just play on private family servers : https://pastebin.com/7HCGAn9d

Then once I remove the Hats mod from the pack, I get this one : https://pastebin.com/YtziBZzB
That if I didn't get the one reffering to Galacticraft Venus : https://pastebin.com/XkyeKpJy

Please can you take a look at theses.

**Comment by TheLimePixel** [comment]
Ok, what do you get after you delete the dimension?

**Comment by mcdodge34** [comment]
Going to work right now, be back after 9pm GMT-5, I will send my world to you if yoi wanna try when I'm back home. Thanks for trying to help me out theses 3 crashlogs are there all the time, randomly

**Comment by mcdodge34** [comment]
Ok, here's a copy of my world if you want to test it out : http://www.mediafire.com/file/zgyo0ck071os38c/world%202018-04-05%2010%3B07%3B06%20%28Full%29.zip

Note that I removed a couple of mods but they aren't affecting progression line and are mostly client stuff that are on server too but they annoy me more than anything, the only main mod I took off is EnderZoo, the others are mousetweaks, itemzoom tipthescale, and so on, theses aren't needed for the pack to work for sure. Oh yeah I added 1 mod, don't think its gonna affect it either Just a Magnet you can find it there but I tested without it, doesn't make any difference : https://minecraft.curseforge.com/projects/jam-just-a-magnet

Trying to fix it again today, I upgraded forge to latest version to see if that could help, crossing my fingers but so far nothing better cause those crash reports repeat themselves, they are all the same all the time, strange thing is that world works fine in 3.1.5.3, its when I try to update that it doesn't want to load the server and crash. I would really love to know what happens, is there a community that could help me somewhere else also, maybe submitting this somewhere would help me out, I don't do it on reddit cause theses are deleted by bots on the ftb official reddit or ignored if posted in the ftbcrash reddit since no one goes there except for posting crashlogs usually so its not helping a lot.

So far, the same crashlogs again and again, it doesn't like foamfix on my rig so getting rid of it seems to help, no surprise there this foamfix does strange things sometimes, also had to remove hats, no problems with that like I said in original post.

I swear I'll end up solving this issue, its driving me nuts, I'm Autist Asperger, so I'm extremely determined and dedicated when I'm trying to fix something, I must have tested and tried for at least 10hrs of real life to fix this problem. When I finally think its solved and I move the server to the test machine, I get crash again and again, that is after successfully starting the server 4-5 times on my main rig the same crash reports are there again and again, I don't think posting them again would help, but if you need them, I have 8 of them from testing so far, I give up for now, will test stuff later after work tonight probably.

**Comment by mcdodge34** [comment]
Ok, I've decided to try to play in 3.1.5.3 till I hit the wall, and if I hit a bug that cannot be solved, I'll just give up on this pack, is there anything major that could prevent me and my brother from finishing the quest line in the 3.1.5.3 edition ???

**Comment by TheLimePixel** [comment]
Why don't you just restart as most people did?

**Comment by mcdodge34** [comment]
I give this pack so much time already, not gonna happen sorry, especially with the chickens breeding I've done, and my brother is very deep into the bee breeding, some people think its funny to restart at every update, not me. I'll try to upgrade my world to latest 3.3 this week, maybe we will get lucky, just tell me where will my adventure ends in 3.1.5.3, will it be while getting to a particular stage, or I may complete the whole thing...

**Comment by mcdodge34** [comment]
Miracle, except for some quests that seems to be completed in different quest stages like some basic stuff in enderio stage and others even if we didn't touch it yet, I upgraded the map to 3.3.0.1 and have 0 crash reports so I updated my server finally, we can deal with some quests being completed I suppose, and some trophy that we should have aren't there, but its something I could live with for now.

**Comment by TheLimePixel** [comment]
Ok, I'm glad it finally worked for you. You have those quests unlocked because you previously had quests completed that were deleted and then these quests were added and got their ids. And some pages have additional quests that unlock afterwards, so that's why you don't have those trophies.

**Comment by mcdodge34** [comment]
Any tips to solve this, is it possible to edit them so they aren't marked as done perhaps that would be possible...

**Comment by mcdodge34** [comment]
Ok, think I've seen some youtubers do it with other packs, will figure this out, thanks for your help.
