### ISSUE TITLE
Missing Floral Fertiliser

### ISSUE THREAD

**Issue by Lost-Ninja** [TheLimePixel/Modern-Skyblock-3#363]
Found it no issue in Gated Mode (prior to the most recent update) but now in a Kitchen Sink play-through it has no recipe. I'm in the current version of the pack and the play through was started after the update.

There is a reference to it in the scripts (useful.zs) where it is "disabled for progression", however there is no obvious clue as to how to make Botania flowers grow otherwise.

**Comment by TheLimePixel** [comment]
It's disabled.

**Comment by Lost-Ninja** [comment]
So how then do you force Mystical Agriculture Plants (the ones that would normally grow with Floral Fertiliser) to grow? JEI/NEI/Botania Manual aren't any help.
