### ISSUE TITLE
Graphite Bug

### ISSUE THREAD

**Issue by Khalep** [TheLimePixel/Modern-Skyblock-3#366]
When you place Charcoal in an Air Compressor(PneumaticCraft) and break it it will convert the Charcoal to Graphit Bars and Double the amount which you put in.

Edit: Version 3.2.0.1

**Comment by TheLimePixel** [comment]
It's due to your pickaxe.

**Comment by desht** [comment]
Actually, there is a bug in PNC:R here; the tile entity's contents shouldn't be getting smelted too.  I have a fix in dev right now, but it needs a bit more testing (changing the way drops are calculated could have unforeseen side-effects).
