### ISSUE TITLE
Decrease default backup interval

### ISSUE THREAD

**Issue by MirrorImageQS** [TheLimePixel/Modern-Skyblock-3#367]
As admitted to in the overview of the pack, BQ3 is unstable, which comes with the suggestion to "back up often." However, the default backup interval for FTB in the configuration is 2 hours (meaning 2 consecutive in-game hours). For those who don't play for that long in a single session, that effectively means FTB does not back up the save at all.

ftbutilities.cfg:
`D:backup_timer=2.0`

I would suggest that if the proposed solution to BQ3 instability is "back up often," then the default back up interval should be much shorter (the parameter supports a value as short as 3 minutes between backups, "0.05"). I would suggest that 15 minutes ("0.25") would be sufficient.

**Comment by TheLimePixel** [comment]
30min is enough.
