### ISSUE TITLE
Better questing mod not reading already completed quests

### ISSUE THREAD

**Issue by PMOY408** [TheLimePixel/Modern-Skyblock-3#370]
after the 3.2.1 patch, and even if I already have completed every quest in the previous lines, the basic automation line is completely unfamiliar and I even have completed some quests in basic automation  

![2018-04-05_00 45 20](https://user-images.githubusercontent.com/38093593/38347943-9b48ace0-386c-11e8-8174-20364aecd5cb.png)

**Comment by PMOY408** [comment]
![2018-04-05_01 04 09](https://user-images.githubusercontent.com/38093593/38348017-45c599a8-386d-11e8-8356-8180c1c660c6.png)

**Comment by SpamaelMC** [comment]
This happens to me as well after the update. Everything that needs "Basic Automation" is unfamiliar although I long passed that point.
I did try to reload the quests from Questbook->ReloadQuestbook several times, but it didn't seem to make any difference. 

If it makes any difference, I'm running on a Mac, Java Version: 1.8.0_65

Thanks

Later Edit: I'm in single player, forgot to mention that.

**Comment by b0bst3r** [comment]
What version did you upgrade from?

**Comment by SpamaelMC** [comment]
Myself from 3.1.5.3

**Comment by b0bst3r** [comment]
Did you follow the instructions in the changlog to add back in the stages?

**Comment by SpamaelMC** [comment]
Unfortunately, no. I only read the current changelog, not the previous one, I'm sorry about that. 
I'll test it asap (the /gamestage command) and get back to you on that. 

Later Edit: It worked great, thank you and sorry for not reading the complete changelog.
Fur further references, the command:

/gamestage add \<username\> ba 

does the trick.

**Comment by PMOY408** [comment]
Thanks guys!

**Comment by sirnoct** [comment]
Yeah I have this issue too but I can't use the command help pls

**Comment by thmarth** [comment]
@sirnoct are you in a single-player world?
Try the "LAN Server" option in the menu after loading in and checking the "Enable Cheats", that should allow you to run the command.
The LAN server will only persist through the current session.

**Comment by sirnoct** [comment]
@thmarth No yeah I manged to fix it the old fashioned way by downloaded NBTExplorer and changed the numerical for "allow commands" to 1 effectively enabling cheats
