### ISSUE TITLE
Stage Basic Farming won't let me do any quest

### ISSUE THREAD

**Issue by Iv1202** [TheLimePixel/Modern-Skyblock-3#372]
I upgraded from 3.1.5.3 to 3.2.0.1 after I did the instructions that the changelog said, but now, when I try to progress in the new stage it says I can't because I don't have it unlocked.
I reloaded the questbook as well.![2018-04-05_16 07 13](https://user-images.githubusercontent.com/38106564/38370853-6aa29658-38eb-11e8-9fcc-7385d3238400.png)
![2018-04-05_16 04 04](https://user-images.githubusercontent.com/38106564/38370759-24f1df2e-38eb-11e8-8dff-d455fd552b61.png)

**Comment by thmarth** [comment]
Try `/gamestage add <username> bf` instead of `ba`
That should unlock the "Basic Farming" stage, I had the same issue.

**Comment by Iv1202** [comment]
Yeah, that definitely seemed to work, thanks @thmarth !

**Comment by TheLimePixel** [comment]
You didn't have it unlocked... you need to complete compressed cactus and seeds.
