### ISSUE TITLE
Eating Nuclearcraft food crashes game

### ISSUE THREAD

**Issue by BanzaiRun** [TheLimePixel/Modern-Skyblock-3#373]
In kitchen sink mode:-

Tried eating both dehydrated carrots and apples (purely for extra hearts) caused same crash each time..

java.lang.NullPointerException: Ticking player

**Comment by b0bst3r** [comment]
Full crash log into pastebin and linked here please

**Comment by BanzaiRun** [comment]
Here you go:-

https://pastebin.com/Bn99e9pa

Great job otherwise, really enjoying it :+1:
