### ISSUE TITLE
I can't use the /gamestage add command

### ISSUE THREAD

**Issue by sirnoct** [TheLimePixel/Modern-Skyblock-3#375]
Scrap that. I couldn't do the command as I made the world without cheats and had to sort it out the vanilla way by downloading NBTexplorer and Changed the value of "use commands" to 1 so I could use the command. so if anyone else has this issue there's the way to fix it. (Link to the NBTExplorer https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac)

**Comment by RustyXXL** [comment]
You also just could open your game to LAN to allow commands...it works just for the current session, but doesn't involve nbt editing, and is actually a vanilla minecraft feature.
