### ISSUE TITLE
Sequential fabricator not crafting enderium blend but still using up the items.

### ISSUE THREAD

**Issue by RichardEHarris** [TheLimePixel/Modern-Skyblock-3#376]
Sequential fabricator uses up items when crafting Enderium blend but does not output the crafted item.
Seems to work fine with other crafting operations.
Also seems to have the same effect when the fluidic fabrication augment is installed in the machine.
I am in gated mode and i have Thermal expansion unlocked

![2018-04-06_16 58 09](https://user-images.githubusercontent.com/19771641/38408177-8d0a8aae-39bb-11e8-988a-80281db25c19.png)
![2018-04-06_16 58 13](https://user-images.githubusercontent.com/19771641/38408178-8d3cd5cc-39bb-11e8-862b-a3c6886102fb.png)

**Comment by RichardEHarris** [comment]
I've found that it happens with other Thermal expansion recipes which require a fluid too, such as signalum blend but does not happen with other mod recipes that take fluids such as the insulated MV wire coils from immersive engineering. i checked with kitchen sink mode and it still doesn't work.

I tested with a clean instance of minecraft with only Thermal expansion, JEI and all the dependencies and the blend recipes work in the Sequential Fabricator so it must be a problem with this pack or some mod in this pack interfering.

**Comment by temp1029** [comment]
I am seeing this to. Also an issue [here](https://github.com/CoFH/Feedback/issues/1190) in the CoFH issue tracker for this where @KingLemming said it's a pack issue.

**Comment by TheLimePixel** [comment]
Oh, ik why, it's because of the staging.

**Comment by temp1029** [comment]
Any chance of a fix or would that need to be accounted for on the mod’s side?
