### ISSUE TITLE
Galacticraft cryo crash

### ISSUE THREAD

**Issue by Elvi81** [TheLimePixel/Modern-Skyblock-3#378]
Using the galacticraft cryo can cause the server to crash.
Events that seem to unfold.
Use cryo on mars for instance at night.
Day comes, lookin at solar panels, no energy generated even if sun is directly above.
Try the cryo again and... crash...
This is the only way to get the radiation to go down at this stage that i've found but if it crashes like this then there's no real way to continue, the antirad drink is too far off to use.

Crash report: https://pastebin.com/CKpTysGm

**Comment by b0bst3r** [comment]
Killing yourself reduces radiation down as far as 50%
Sleeping reduces radiation so long as you aren't on a server using morpheus.

**Comment by Elvi81** [comment]
I tried killing myself once but it didn't go down with more than 10%, also when i wrote the top post even sleeping had no effect.

**Comment by TheLimePixel** [comment]
Using it in the overworld works perfectly.
