### ISSUE TITLE
Better Questing will not let me craft items from the ba branch

### ISSUE THREAD

**Issue by KiroStarr** [TheLimePixel/Modern-Skyblock-3#379]
I'm playing on a server on the latest release of the pack as a party. We have the Better Automation quest unlocked, but we can't craft any of the items associated with it, such as the hopping bonsai pot or any of the spikes. We have tried the command that's listed on the change log, replaced the better questing file with the one in the backup folder, and have refreshed the quest book from the built in refresh quest. Is there something that we're missing or not doing correctly?

**Comment by DonnerVarg** [comment]
I am not allowed to carry items from the ba branch in my hand. Notably, I have Hoppers, but they're now on a locked branch. I assume this is a bug because Hopping Bonsai Pots are a quest I have already completed and they still require Hoppers.

**Comment by DonnerVarg** [comment]
Looks like a quest reload is needed, but it doesn't work perfectly for me. bfaa became ba and fa

**Comment by Elvi81** [comment]
KiroStarr everyone must refresh their quest books.

**Comment by DonnerVarg** [comment]
Oddly, I still don't have access to ba branch blocks/items, though the Basic Automation task is marked complete.

**Comment by KiroStarr** [comment]
Everyone has refreshed the quest books, we still don't have the ability to craft anything from the ba branch

**Comment by DonnerVarg** [comment]
It seems Better Automation is unlocked (still completed), but the ba gamestage isn't unlocked, I assume because when I claimed it, the bfaa gamestage was unlocked. I tried to alter the quest database to get ba as a second command reward for something else, but apparently I formed the json wrong.

**Comment by Elvi81** [comment]
Try /bq_admin complete questid username or no username for everyone, the op needs to do this.
The id for better automation under gated mode is 983.
Id's can be gotten by pressing f3+h and hovering the mouse over the quests.

**Comment by KiroStarr** [comment]
I'll have the admin try that next time he's online.

**Comment by TheLimePixel** [comment]
You have to claim the quest on the first quest page. If you've done that before the update, read the changelog.

**Comment by KiroStarr** [comment]
That has been done already, along with replacing the file from backup, running the command listed on the changelog, and refreshing the questbook from the build in refresh quest. I can complete every other quest in the ba chain with the exception of the spikes and the hopping bonsai pot quests.
