### ISSUE TITLE
All fluid quests complete automatically

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#382]
if you fill the bound blood drop with blood, the quests that need fluids will be automatically completed. this error only occurs when the item has been filled with some blood.

https://screen.ilikepudding.tk/nbl032um81.png
https://screen.ilikepudding.tk/tg9w1j6kla.png
https://screen.ilikepudding.tk/djrj0k93qs.png

Affected quests are: 637, 658, 644, 665, 722, 719, 721, 717, 720, 723, 311, 568, 564, 433, 428, 426, 798, 164

**Comment by ghost** [comment]
why do u close it alltime? then take the item out of the game (crafttweaker, config)

**Comment by TheLimePixel** [comment]
That is a useful item.

**Comment by ghost** [comment]
then remove quests

**Comment by ghost** [comment]
it makes absolutely no sense to make an item automatically complete it even though the quest requirements are not met.

**Comment by TheLimePixel** [comment]
I know it doesn't and I don't get how broken fluid handling can be for that to happen.

**Comment by ghost** [comment]
then just remove the quests of the liquids, then the problem should be fixed. maybe it's up to better questing itself or to evilcraft because it does not work properly to let the liquids differ.....
