### ISSUE TITLE
Basic Automation stage broken

### ISSUE THREAD

**Issue by JacksonWelt** [TheLimePixel/Modern-Skyblock-3#383]
After updating to 3.2.0.1, I am unable to make anything requiring stage BA, all items are "Unfamiliar Items".
Since the update I have unlocked other stages and those work fine, as well as all others that were previously unlocked. I reloaded questbook to no avail.

**Comment by MoocowTheGodly** [comment]
From the changelog:
-If you had Basic Farming And Automation unlocked (this includes being in kitchensink mode), do /gamestage add <username> ba
-If you are in kitchensink mode do /gamestage add <username> bf
-To get the new loot chest rewards, do /bqs_loot default load

Have you done this?
