### ISSUE TITLE
Mystical Lime Seeds, Mystical Green Seeds. Same recipe.

### ISSUE THREAD

**Issue by PLEisenherz** [TheLimePixel/Modern-Skyblock-3#393]
Is it intendet that Mystical Lime Seeds and Mystical Green Seeds  have the same Recipe?

Version: 3.2.0.1
MC: 1.12.2
Forge:14.23.2.2634

**Comment by TheLimePixel** [comment]
I'm not the mod dev to tell you that. Either way, you have a chance of getting either of them.

**Comment by PLEisenherz** [comment]
thx
