### ISSUE TITLE
bug better questing quest book

### ISSUE THREAD

**Issue by miouwarp** [TheLimePixel/Modern-Skyblock-3#394]
hello, 

I play solo

my problem is that all chapter quests are unlocked and some quest are unlocked  on the latest version

if I play on the previous version
I just have the environmental tech chapter and the quest to unlock and a quest in overpowered

if you have an idea how I can solve my problem

thx #

**Comment by TheLimePixel** [comment]
Is it just the quests on the main page?

**Comment by WJ44** [comment]
I have a similar problem, only I started in 3.2, all the chapters were already unlocked. And now with updating some random quests, indeed on the main page, get unlocked.
