### ISSUE TITLE
Low framerate and long loading times since 3.2

### ISSUE THREAD

**Issue by taylorsamy** [TheLimePixel/Modern-Skyblock-3#395]
Ever since version 3.2 my framerate went from 100+ to 20 with spikes down to 0, and the pack takes at least 20 minutes to load

**Comment by GoodBob** [comment]
Same. I have not been able to load the game because it is taking so long. Seems to take the longest on "Indexing ingredients".

**Comment by TheLimePixel** [comment]
Does your RAM bar spike?

**Comment by taylorsamy** [comment]
No it doesn't

**Comment by GoodBob** [comment]
Mine does.

**Comment by GoodBob** [comment]
I have been able to load the game now. I had to change the profile options to allow for ~6 gigs of ram. Still takes 10-15 minutes to load.

**Comment by taylorsamy** [comment]
My profile is set to 8 gigs of ram, still takes half an hour to load

**Comment by TheLimePixel** [comment]
If you have enough RAM to where it doesn't spike, it's all on your CPU.
