### ISSUE TITLE
Can craft Crucible Inserter after upgrade to 3.3 (gated)

### ISSUE THREAD

**Issue by oliverjanik** [TheLimePixel/Modern-Skyblock-3#397]
Some of the items from Basic automation are not craftable anymore. It says Unknown item.
I finished this quest before upgrading and I'm locked out of some items in this gate.

**Comment by LargeDoot** [comment]
Believe you have to do /gamestage add <playername> ba.
I had the same issue.

**Comment by oliverjanik** [comment]
thanks didn't know that command existed
