### ISSUE TITLE
Game crash on launch after updating to 3.3

### ISSUE THREAD

**Issue by LargeDoot** [TheLimePixel/Modern-Skyblock-3#398]
Game crash on launch after updating to 3.3. 
Crashlog: https://pastebin.com/aWFhUDME

Don't know what other details I can give, I just updated and this happened.

**Comment by LargeDoot** [comment]
Changing this config line to false fixed the issue:
    # Does not force the material, only allows it to be loaded. Other mods and requirements are still needed for this to load
    B:"Allow Soularium Material"=false

I guessed this would happen to others hence my post.

**Comment by TheLimePixel** [comment]
It's already false.

**Comment by ThaDaVos** [comment]
Just downloaded Server Files and it's set to True in moartinkers.cfg
Causes server to crash on bootup

Part of the crash-reports which proofs this:
https://pastebin.com/Njnp8rzQ
