### ISSUE TITLE
planet progression telescope

### ISSUE THREAD

**Issue by Elvi81** [TheLimePixel/Modern-Skyblock-3#399]
Planet progression telescope not accepting power after 3.3 update, neighter cables nor gc or other batteries.

**Comment by TheLimePixel** [comment]
Did you re-place it? It's made up of 3 blocks now.

**Comment by Elvi81** [comment]
Had to be replaced as it went poof anyway.
I can place a "cage" of cables around it and not one of them connect nor give power to it.

**Comment by MJRLegends** [comment]
Yes you should not be able to use cables i stopped that as it was never intended, you need to use batteries in the GUI

**Comment by Elvi81** [comment]
UHM! i tried using GC batteries and it did not work!, read my first post :(

**Comment by Elvi81** [comment]
https://imgur.com/a/64JHE

This is what it looks like.

**Comment by MJRLegends** [comment]
Thanks a planet progression update will be out in the next few hours

**Comment by TheLimePixel** [comment]
I guess a pack update will be out in a day then.

**Comment by MJRLegends** [comment]
Yeah working on the updates now so shouldnt be long

**Comment by Elvi81** [comment]
Works again as of pack version 3.3.1.1 beta.

**Comment by MJRLegends** [comment]
Nice
