### ISSUE TITLE
Steam Dynamos with Turbine Augment don't accept steam

### ISSUE THREAD

**Issue by Kyks20** [TheLimePixel/Modern-Skyblock-3#400]
Looks like  if u upgrade Steam Dynamos with Turbine Augment and use to generate steam from other sources the they don't accept it. i looked NEI and only mekanism steam was there but i found out that turbine augment wants thermal steam not mekanism steam. same thing is whit Nuclearcraft steam,
https://github.com/turbodiesel4598/NuclearCraft/issues/216 there is a longer info about it. can u somehow change that only thermal steam is allowed?

**Comment by TheLimePixel** [comment]
No
