### ISSUE TITLE
Recipe conflict with Fabric Mesh

### ISSUE THREAD

**Issue by Daoenti** [TheLimePixel/Modern-Skyblock-3#401]
The Fabric Mesh from Magneticraft has a recipe conflict with String Mesh from Extra Planets, both are 9 string in a 3x3 crafting grid.

**Comment by Daoenti** [comment]
Just realized I was on an old version, let me update and I'll resubmit if it is still an issue.

**Comment by Daoenti** [comment]
Issue still exists on 3.3.1

**Comment by TheLimePixel** [comment]
Forestry Worktable.

**Comment by Daoenti** [comment]
That is a complete BS response to a valid recipe conflict.  How are people supposed to know something like that?

**Comment by TheLimePixel** [comment]
It has a quest which is required for it.

**Comment by Daoenti** [comment]
But that quest doesn't even unlock until after you can make things that have recipe conflicts.  By the time I was able to start making Magneticraft things I hadn't come anywhere close to unlocking the Forestry quest line, so to most people it's going to look like a bug and conflict.  There's no way everyone should be expected read every single quest description of locked quests to know what may be possible in the future?

If it's supposed to 'gate' Magneticraft that's fine, but then Magneticraft needs to be locked until after Forestry.

Factory Tech (which gates the Forestry quest lines you mention) is such a useless slog to just rush through the quests that it's very possible people will be looking to Magneticraft to automate things before they go through Factory Tech.

Perhaps your answer of 'It has a quest' is right, but if that's the case then the quest flow has issues.

**Comment by TheLimePixel** [comment]
Nope, it's vise versa. I'm guessing you haven't updated your book for a few versions.

**Comment by Daoenti** [comment]
I update it every time, and I have no idea what you are talking about... Forestry in my book is after Factory Tech, Magnitecraft isn't gated at all from any quest I can find.

So I don't understand what you mean by 'vice versa' at ALL.

**Comment by TheLimePixel** [comment]
The quests where you have to make items that have recipe conflicts require you to complete the workable quest. Now, if you complete it without knowing what it does, without reading the description for it, before those quests, that's your issue.

**Comment by Daoenti** [comment]
I'm done with this pack... good luck to you but this thing is a convoluted mess.
