### ISSUE TITLE
"The Trophy Room" questbook chapter not behaving as it should?

### ISSUE THREAD

**Issue by Ncrpts** [TheLimePixel/Modern-Skyblock-3#402]
Playing in gated mode on a server, updated pack from 3.2.0.1 to 3.3.1

After reloading the questbook, in the new category "The Trophy Room" I have the quest "life in the forest" that is marked already complete and claimed even though i haven't unlocked the stage yet, 

i could claim without issue 4 trophy quests (br, bt, bf, amc) but i did not get quest showing up for basic automation and mystical flora (and all quests within these stage are both fully complete and claimed)

**Comment by TheLimePixel** [comment]
More quests unlock on those pages as you progress. And I guess LITF was unlocked as it slightly corrupted when updating.

**Comment by Ncrpts** [comment]
yes but that makes 3 trophies unobtainable so far, hope you can find the cause

**Comment by Ncrpts** [comment]
i will try to replicate from a brand new world see if it's reproduced
