### ISSUE TITLE
Dropping Items Delete them

### ISSUE THREAD

**Issue by kazu231** [TheLimePixel/Modern-Skyblock-3#405]
Upon updating to pack version 3.3.1 any items that i drop from my inventory are deleted instantly.

Only addition to the pack i have made is optifine

thanks

**Comment by kazu231** [comment]
Doing testing it seems that the block breaker from random things is causing this, as once it is turned off and i cause a block update, items can then on be dropped properly

**Comment by megamanzteam** [comment]
I can confirm this, however it didn't matter if it was on or off for me. I had to remove it from the world before getting any drops.

**Comment by doppelhelix** [comment]
Another issue with the block breaker (propably related) is that it does not break blocks. The cracking animation appears briefly and stops. Breaking the block braker or the block that is supposed to be broken will void them.

**Comment by drewkeating** [comment]
I can confirm this. Also, the Mechanical Miner from Extra Utilities is causing this as well.

**Comment by TheLimePixel** [comment]
With everything updated, I can't reproduce it. I'm guessing it was a forge issue.
