### ISSUE TITLE
Carry On mod does not pick up chests

### ISSUE THREAD

**Issue by andremiller** [TheLimePixel/Modern-Skyblock-3#41]
The included Carry On mod adds functionality to pick up tile entities and mobs with shift-right-click, but on version 3.1 of the pack it only works on mobs (tested on animals), but not on tile-entities (tested on chests).

**Comment by pie-flavor** [comment]
https://github.com/Tschipp/CarryOn/issues/70

**Comment by Tschipp** [comment]
Yes, I accidentally used a version of FTBU that was not released to the public yet.
Edit: well not on curseforge anyway.
