### ISSUE TITLE
Ender Bucket and Grave Keys Invisible

### ISSUE THREAD

**Issue by Cheata** [TheLimePixel/Modern-Skyblock-3#413]
Just updated to version 3.2.1 from version 3.2.0.1 and iv noticed that the ender bucket and the grave key are no longer visible. in my inventory, on the ground, on a crafting table, in my hand, its not even visible in JEI, however the object is still there and can be interacted with (tool tips pop up when hovered over in inventory, JEI etc).

I'm running a private server with 2 clients connecting and both are having the same problem so i suspect the issues is in the server but i'm not sure if its a problem with the mod or not as i would have expected someone else to notice it by now. 

Can anybody enlighten me as to what may have caused this and how it may be fixed.

Thanks

**Comment by Cheata** [comment]
Thought id better mention that i decided to load up a single player game and after unlocking kitchen sink mode i found the same problem so its defiantly the client ill do some more checking and let u know what i find

**Comment by TheLimePixel** [comment]
It just happened once EnderIO was added. I don't know how, nor why, so it can't be fixed.

**Comment by Cheata** [comment]
So this is a known issue then and its not just me?
