### ISSUE TITLE
Crash report :/

### ISSUE THREAD

**Issue by benji19** [TheLimePixel/Modern-Skyblock-3#414]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

I get this crash report when i try to launch the mod pack can somwone help me

**Comment by TheLimePixel** [comment]
Restart your computer.

**Comment by benji19** [comment]
hi it has more or less helped but now it is stuck at the last part of at 6/7
