### ISSUE TITLE
Ghost lightsources freezes server.

### ISSUE THREAD

**Issue by Elvi81** [TheLimePixel/Modern-Skyblock-3#416]
I'm not 100% on this one but i think it's botania's light source... thing that's freezing up my server, soon as i get near one... boom. can't do a thing. no error's or anything, it just times me out and server is still on so a complete freeze :(

**Comment by Elvi81** [comment]
It might not be botania afterall, copied the server world to my pc, went into singleplayer and went to these bad places, instant freeze, removed player file and tried again, i thought i had a brakethru but it just took longer to freeze.

**Comment by Elvi81** [comment]
Okay 1 spot fixed... i hope as it was there it started but it seems to be ghost light sources of some kind, now i only need to figure out how to fix that guys base, it's full of these, can't even enter without either freezing the server or the client.
Suggestions are welcome.

**Comment by TheLimePixel** [comment]
What do you mean "Ghost light sources"? Provide a screenshot

**Comment by Elvi81** [comment]
Managed to get one of an older save without freezing but this is the only spot i can show as what i call ghost light, literary no light source.

https://imgur.com/a/KBoWA

Even if you look at the spot via say mcedit2 there is no light emitting block,
Can't go near a players base thanks to these as it either freezes up the client or the server.

**Comment by piercy** [comment]
Did you get anywhere with this @Elvi81 ?

**Comment by Elvi81** [comment]
Sorry not yet.

**Comment by piercy** [comment]
damn, i went through mcedit and couldnt find anything off in the area thats the problem.  That said mcedit wasnt working very well. Lots of ? blocks.  

I tried increasing the timeouts to crazy numbers but i dont think its having an effect.  We thought an update might have done it, we had a backup before the update. So tried that, that also has the issue.  were pretty stuck on what to try or even do now.  Im thinking about getting the guy in, try teleporting him to me and then deleting / reseting his island from there.   Although i think if we do that he might just quit the modpack.  Hes pretty bummed out about it.  Hoping if we get him back to where he was with creative and commands at least he hasnt lost too much and will stay playing.

**Comment by Elvi81** [comment]
I have a feeling a relight of the offended areas could possibly help but i've not managed to do that as of yet.
The place where i found this issue at first started working after i managed to place blocks where the supposed light was, however this was 1 light so it wasn't as bad, a few relogs and it cleared up so yeah i think the light in the areas need to be redone.

**Comment by piercy** [comment]
yeah the area offending by me is lit up as far as i can tell.  I dunno whats up with mine.

**Comment by ttechr** [comment]
Sorry to revive old post, but have you gotten into pneumaticraft yet? Specifically the Amadron?

**Comment by Elvi81** [comment]
I hadn't been thru pneumaticraft at the time this started, maybe the player on my server might have but where i first noticed the problem there was no pneumaticraft stuff.
Yes Amadron used but this is after these things happend and hasn't affected the server since... as far as i know.

**Comment by piercy** [comment]
my lot hadnt reach pneumaticraft when we had the issue

**Comment by ttechr** [comment]
We had a similar issue as thing and it turned out to be a ton of Pneumaticraft drones in one chunk. I went in with McEdit and removed them and it fixed the issue.

**Comment by Elvi81** [comment]
I realy doubt it's drones in the nether... maybe a bad chunk where a light was but the other players place... dunno, how can you see in mcedit if there's drones?

**Comment by ttechr** [comment]
Well I went thru the chunks view thinking it was entities and sure enough one chunk high up had a ton of them so i went thru and deleted all of them and it worked.

**Comment by Elvi81** [comment]
Nope, not a single thing higher up than a jungle tree.

**Comment by InflamedSebi** [comment]
Only thing you could try is replacing every air block with dirt (is RFTools builder card a thing?) and then remove the dirt again (quarry card + filter?) usually those ghost lights disappear when an other block is placed in the same space.
But i wouldn't try it in live server ... this might make things worse if its not working ...

**Comment by Elvi81** [comment]
Not possible as when your in the same place as those... spots the server grinds to a halt, does not crash tho.
Tried the same thing via mcedit 1 and 2 and it would not save, both programs crash.
Only mcedit 1 said something about "too big chunks" when trying to save after an edit.
