### ISSUE TITLE
Bug: Ender Dragon failed to spawn?

### ISSUE THREAD

**Issue by GrumpyGiant** [TheLimePixel/Modern-Skyblock-3#419]
I am playing through in staged mode and working through advanced resources. I built the end portal multiblock, provided the portal block with redstone and was teleported through without any issues. Once I loaded into the end, the dragon was nowhere to be found, no boss health bar, no noises, nothing. The bedrock portal isn't formed, but the obsidian towers are as well as the crystals on the towers, the other mobs are all present and the island formed fully as did the distant islands, the only thing missing is the dragon itself. If you need any additional information from me or I can help in any way please let me know. I have a video containing the issue on youtube if you need a visual aid but I'm not here to self promote so if you need a link it's available.

P.S. you might need to look at the Light Matter quest, seems it can't be unlocked without being in Kitchen Sink mode but I could be wrong there.

This is a single player world, version 3.3.1 launched from the twitch app.

**Comment by passh2o** [comment]
I'm still having this problem. I tried deleting the end dimension several times as the change log suggested. I've updated to the most recent version (3.3.1.2) in hopes that it was fixed.
