### ISSUE TITLE
OreExcavation and Rock Grinder leaves blocks in multiplayer

### ISSUE THREAD

**Issue by andremiller** [TheLimePixel/Modern-Skyblock-3#42]
When using OreExcavation to mine a group of blocks with the Rock Grinder the blocks stay in the world for other players that were online when they were mined. The other players can walk on them, and break them (but they don't drop anything) and they disappear when they log out and in again.

We noticed this on our shared island with multiple players playing together on the same island (using /island invite)

Tested on version 3.1 of the pack, using Compressed Rock Grinder on Compressed Stone blocks with two players online on the same shared island.

**Comment by TheLimePixel** [comment]
Yeah, this is some weird mod interaction as the grinder isn't supposed to do a 3x3x3 in the first place.
