### ISSUE TITLE
[Enhancement Request] Better visualization of main quest line progression

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#423]
I would love to be able to visualize all the quests in the main quest line, to be able to see what are the actual requirements to advance to each stage and to reach a specific mod I would like to play with. I've been messing around with the quest book and I think I found a solution.

For gated mode the solution is quite simple, just changing the visibility of all the quests below _Basic Resources_ and _Basic Tinkering_ to _CHAINED_ does the trick.

For staged mode it is not as simple, just changing the quest visibility to _CHAINED_ is not enough, as any prerequisite being visible triggers the visibility of a quest with _CHAINED_. To work around this I found a way that involves creating a proxy quest for each of the prerequisite outside the main quest line, and setting this proxies as invisible and silent (to prevent the completion notice for them).

I've made a script to take the quests json and patch it up with the changes I described above. I've uploaded this script as a gist:

https://gist.github.com/War-Wizard/fac296e6ec05ab727e00b8e2c2ddbe9c

(yes, it's an html file... it's just a javascript listening to a html file input, parsing the json, altering it and giving it back to you as a "download")

I've also uploaded to gist the resulting json file after patching the quests json of version 3.3.1.1, for anyone who might want to check how these changes work:

https://gist.github.com/War-Wizard/a9c2fa173b75a1432778f70c47b45e4f

**Comment by TheLimePixel** [comment]
Personally, I don't want every stage being visible. It's interesting to see new things unlock. I do however want to be able to see what the next staged mode quest requires, so it's the same as gated.

**Comment by ghost** [comment]
That may be possible if the quests to be completed were to appear as tasks instead of prerequisites.

I see two ways of implementing this:

1) Make them scoreboard tasks and have hidden proxy quests that auto claim with a scoreboard reward. When a main quest is completed, its proxy quest gets completed and claimed, triggering the scoreboard reward and completing the task in the main quest line. It's a bit convoluted but can be done with what the mods that are currently in the pack provide. I think I can modify the script I've made to do this.

2) An addon to BetterQuesting could provide a task linked to the completion of a quest, this way the quests required to progress the stage can be specified as tasks. As far as i know there are no such addon, I'm looking into it.

**Comment by ghost** [comment]
PS: Regarding option (1), it has to be taken into account that the scoreboard task gui is not really intuitive for the user when it is not used for the specific purpose of tracking a score, so... option 1 feels more and more like a hack rather than a solution.

**Comment by TheLimePixel** [comment]
Well, I'll see where this poll goes: https://www.strawpoll.me/15507664/r
 Your idea might be implemented.

**Comment by ghost** [comment]
Nice!

Either way I think you have a very compelling use case scenario for having quests as tasks rather than prerequisites, and there isn't a mod that adds that. I've been looking for a reason to try my hand at coding a mod from scratch, and this seems like a good opportunity.

**Comment by ghost** [comment]
/edit nevermind seems it just something wrong with my world
