### ISSUE TITLE
Akashic Tome

### ISSUE THREAD

**Issue by Timeslice42** [TheLimePixel/Modern-Skyblock-3#426]
Please add the Info Calculator.

**Comment by TheLimePixel** [comment]
A Calculator in a tome? No.

**Comment by Timeslice42** [comment]
It's the mod's guide book. I fail to see the issue.

**Comment by TheLimePixel** [comment]
Yes, but it's not technically a book.

**Comment by Timeslice42** [comment]
Neither is the embers guide. The point is to have a convenient place to store all of the mod guides.

**Comment by TheLimePixel** [comment]
Well, in theory it is stone that you've written on. :P
