### ISSUE TITLE
3.3.1 can't autocraft tiny dry rubber into dry rubber from any autocrafters and problem with Aether portals ???

### ISSUE THREAD

**Issue by mcdodge34** [TheLimePixel/Modern-Skyblock-3#428]
Ok, I've tried all the auto-crafters that I have access to at this time (I don't have rftools yet), they work fine for all other recipes, but they refuse to autocraft the dry rubber needed for plastic, I can craft it fine in a crafting table, it works fine, but I can't autocraft it in any automatic crafter, in the sequential fabricator of Thermal Expansion, it seems to work but it deletes the dry rubber automatically, in Extra Utilities both the mechanical crafter and analog crafter, it looks like if the recipe wasn't valid. I don't have access to another crafter yet or maybe there's one that I have no idea exist. For now it creates a ton of tiny dry rubber and I'l manually craft it fine on a crafting table, but its a pain to have to do this because we have to smelt the result to get plastic, I generally have automatic machines for that.

And we finally paid a visit to the Aether dimension, but our portal to return to normal world was gone when we went back where it was (marked on map), we had to cheat the supplies to craft it back, is it supposed to do this there's no such reports on their github but maybe this is intended cause we don't know anything about this mod ???

I know there's an update for the modpack, I'll install it tomorrow, still have some tests to do before deploying on real server, I'm paranoid about safety so have backups and such and I test for awhile before deploying.

**Comment by TheLimePixel** [comment]
That is simple impossible to do. You need an ME system to autocraft.

**Comment by mcdodge34** [comment]
Just tested it in FTB Revelation this morning on latest version of the pack, and had 0 issue with all the crafters I've mentioned in this topic, so its not impossible to automate, its easy even with the mechanical crafter it can be done, I could record a video of it if you want. I suspect there's something that blocks it in your pack, but its beyond my understanding here.

And what about the Aether portal problem, just not sure what could have happened there, I'll wait to complete this until I have a teleportation thing cause if we have to manually craft a portal to come back to overworld each time, gonna be very annoying.

**Comment by TheLimePixel** [comment]
It's the fact that they are restricted.

Oh, and I have no idea about the Aether issue. That shouldn't happen. Just /spawn I guess.

**Comment by mcdodge34** [comment]
Ok, for Aether, I'll use the /home for now, so the fact that they are restricted prevent me from auto-crafting them, weird, I don't understand why it would do this, and since I've unlocked this stage, is there any command I could try to remove the restriction maybe, that would help me a lot to enjoy the pack.

**Comment by TheLimePixel** [comment]
All autocrafters are fake players. They need to be allowed to autocraft. However, all, but AE2's, when given access can allow you to bypass restrictions.

**Comment by mcdodge34** [comment]
So I can't auto-craft any restricted items even if I've unlocked them, that will be a big pain in the butt when I reach Galacticraft stage seriously, since AE2 is far down the line, I don't blame it, but it will be very annoying soon since we have all these auto-crafters that are mainly not very useful now.

**Comment by TheLimePixel** [comment]
AE2 and GalactiCraft are in the same row as of 3.3

**Comment by mcdodge34** [comment]
Ok, so I'll reach AE2 around same time, would love to see a new graphic with the questlines updated, the one I have is old, love to see the kind of charts that was posted on reddit to better visualize how everything is unlocked and when.

**Comment by TheLimePixel** [comment]
Oh, you won't need that in the version that just came out.

**Comment by mcdodge34** [comment]
Cool, but just to make sure I better put the first update (going from 3.3.1.0 to 3.3.1.1) then the second one, or I can go straight, I know sometimes its not a good idea to skip some and I got a feeling already that going from 3.1.5.3 direct to 3.3 caused some problems, I wasn't able to upgrade to 3.2 cause server had many unsolvable crash, weird that it was all solved in 3.3

**Comment by mcdodge34** [comment]
Why I always have problems is beyond me here, when I try to migrate to either 3.3.1.1 or 3.3.2, everything works fine, but everything I had done in the last 1-2 days is deleted from the map, portal to Aether gone and we just went there to complete it and returned with a new portal cause it was indeed deleted when we came back to it, also all the machines I had done from Industrial Foregoing gone, all the chests, drawers that I had put down during the last 1-2 days aren't there, its like the only thing that follow is my inventory content with all new stuff I had done including a new machine, the rest has just vanished, but the stuff is working fine and is there on the current server in 3.3.1 I'm starting to think this modpack update cause chunk corrupting and the game just revert back to a state where the chunk was previously, without the chests, drawers or machines I had done on it, I'll do more experimenting during this weekend cause I'll be extremely busy for the next few days, I'm not sure I wanna progress anymore, if I loose everything on a server modpack upgrade. Its beyond my understanding there, the backup is fine and freshly done when I try this.
