### ISSUE TITLE
Fix FactoryTech Water Collector biome restriction

### ISSUE THREAD

**Issue by oliverjanik** [TheLimePixel/Modern-Skyblock-3#430]
It only works in ocean and river biomes.

https://github.com/dalapo/FactoryTech/issues/72

**Comment by TheLimePixel** [comment]
It works in every biome.

**Comment by oliverjanik** [comment]
I'm in frozen river and does not work... I tested in creative, worked in ocean biome

**Comment by TheLimePixel** [comment]
You need to place the water and then the grate.

**Comment by oliverjanik** [comment]
Grate? I'm talking about Water Collector. Grates work fine.

**Comment by TheLimePixel** [comment]
... There are 10 different water sources in this pack. Why would you use that one? -_-

**Comment by oliverjanik** [comment]
I'm in gated, anything that works with FactoryTech pipes?

**Comment by TheLimePixel** [comment]
The Sink if you have A Master Chef unlocked.
