### ISSUE TITLE
Unable to log into MC?

### ISSUE THREAD

**Issue by QwesdeCZ** [TheLimePixel/Modern-Skyblock-3#432]
Hello,
i am new with mods so it is probably my fault, but i am not able to run this mod on my account. I downloaded the right version (1.12.2) from Twitch app, but when i click on Play - game crashed from unexpected error (an unexpected issue occured and the game crashed. We are sorry for inconvenience) i have no idea how to fix it. please help

Thanks for all comments. And i apologize if i made some English mistakes, i was not born as an Englishman

**Comment by Elvi81** [comment]
You probably ran out of ram, twitch defaults to something like 1-2Gb ram while this pack needs atleast 6Gb to run, if you didn't change the ram settings in twitch options under minecraft... this could be the problem.
Also if you don't have atleast 8Gb of total ram, you probably won't be able to run this.

**Comment by TheLimePixel** [comment]
You need to provide a crash log.
