### ISSUE TITLE
[SSP][Version 3.3.1.2] Game freeze on eating specific item.

### ISSUE THREAD

**Issue by phazingazrael** [TheLimePixel/Modern-Skyblock-3#433]
When attempting to eat the food item "Burger Bun" from Galacticraft Core my game client completely freezes up until i manually close it through Task manager.
3 of 4 attempts to recreate the crash were successful as well.

here is the crash log copied to pastebin.
https://pastebin.com/LJRAAL68

**Comment by TheLimePixel** [comment]
Sounds like you aren't on the latest version.
