### ISSUE TITLE
CTD: Galacticraft Lightpanel and Chisel Interaction

### ISSUE THREAD

**Issue by Flatts3000** [TheLimePixel/Modern-Skyblock-3#434]
Version: 3.2.0.1
CR: [https://pastebin.com/cwLK7kRj](https://pastebin.com/cwLK7kRj)

**Comment by Elvi81** [comment]
I crash if i fly and left click one of the GC panels, on ground however it works.

**Comment by Flatts3000** [comment]
I crashed when breaking the light panel with a pickaxe when on the ground.
