### ISSUE TITLE
[Gated] Mystical Crops Stage Requirement

### ISSUE THREAD

**Issue by TheL0ki** [TheLimePixel/Modern-Skyblock-3#440]
There seems to be an error in handing in the "Material Dimlet (Inferium Ore)". I only had 1 of the Inferium Ore Dimlets in my inventory and a few other material dimlets. When i tried to hand in the one i already had, it consumed all the other material dimlets as well and unlocked the stage (as all the other items i already handed in previously).

I assume, as long as there is one of the required dimlets in the inventory the questbook treats all the others as the same.

Version: 3.3.1.1

**Comment by TheLimePixel** [comment]
Yeah, I forgot to disable ingoreNBT for that.
