### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by LadyGrelka** [TheLimePixel/Modern-Skyblock-3#441]
My game keeps freezing up and then crashing, I will post the crash report.  I will also put up my dxdiag file.
[Minecraft Crash Report.docx](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1933042/Minecraft.Crash.Report.docx)
[DxDiag.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1933043/DxDiag.txt)

PS, if this is a RAM issure, aka not enough RAM just tell me and close this issue, I am hoping to be upgrading to 16GIGs within the next month.

**Comment by SilentAssassin01** [comment]
I'm guessing it's raining in your world? Crash log looks very similar to one I was getting on the crop block pack. There's a bug in agricraft that sometimes causes a crash when it's raining if you have a multiblock agricraft tank.
[https://github.com/AgriCraft/AgriCraft/issues/1128](url)

**Comment by LadyGrelka** [comment]
It rains all the time lol, I am always having to turn it off, because it causes lag. I will try taking down my water tank, I think its the one from agricraft.
