### ISSUE TITLE
Certain blocks keeping NBT data when broken

### ISSUE THREAD

**Issue by jezzen** [TheLimePixel/Modern-Skyblock-3#443]
A few blocks (so far, Structured Crafters from Structured Crafting and Proxies from CapabilityProxy) are keeping info on their position and rotation on being broken, which is adding useless data and preventing them from stacking with each other.

![2018-04-21_18 03 54](https://user-images.githubusercontent.com/18730266/39081964-64d3fe42-458e-11e8-9d44-25813f77c4bb.png)

![image](https://user-images.githubusercontent.com/18730266/39081968-71aca52e-458e-11e8-9a7c-e80e071f2275.png)

On a side note, the changelog for 3.3.1.2 it mentions being able to see the whole stage line for the mode, but there seems to be no change from needing the prerequisite stages unlocked to see the next stage (Having both reloaded the quests and started a new world). Bug? Not implemented correctly?
![2018-04-21_18 06 09](https://user-images.githubusercontent.com/18730266/39082012-4ef9be8a-458f-11e8-9a45-c59fdde565d8.png)

**Comment by TheLimePixel** [comment]
1. Seriously, what did you expect me to do about it?
2. I'm guessing you forgot to update your guestbook.

**Comment by jezzen** [comment]
Realized that they are both CyclopsMC mods and found EvilCraft and Colossal Chests showing the issue.

Also, even without looking into the mods causing it, there is an easy stopgap measure to make it more convenient: using a CraftTweaker script to be able to reset the NBT data.

[data_reset.zs.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1935469/data_reset.zs.txt)
Added .txt file extension to be able to upload it.

Lastly, you do realise that I mentioned reloading the quests. I had done both the quest for it, and manually with /bq_admin default load. Even a new save file didn't show the stage progression.

**Comment by TheLimePixel** [comment]
1.Fair point. However, I already uploaded the next version.
2.Weird... actually, it isn't even working for me. I probably messed up somewhere.

**Comment by jezzen** [comment]
Just went through the quest book to see how the visibility stuff works. Here's an updated quests .json with the appropriate quests set as CHAIN visibility.

[DefaultQuests.json.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1936238/DefaultQuests.json.txt)
Again, just added .txt to upload.

![image](https://user-images.githubusercontent.com/18730266/39101352-ce1ea0d4-46db-11e8-9afb-3d1e53a5b314.png)
![image](https://user-images.githubusercontent.com/18730266/39101527-08b4b0d8-46de-11e8-8497-219a81d7e040.png)
