### ISSUE TITLE
Lots of problems (Loading, Making world, Closing world)

### ISSUE THREAD

**Issue by kd827827** [TheLimePixel/Modern-Skyblock-3#447]
[2018-04-21-7.log](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1935748/2018-04-21-7.log)

[2018-04-22-1.log](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1935746/2018-04-22-1.log)

Loading takes 10-15 min with 7 GB of ram

When I create a world, it either takes longer than 10 min or my game freezes.

Any time i save and exit the game freezes on shutting down internal server.

**Comment by TheLimePixel** [comment]
Is this your first time loading the pack?

**Comment by kd827827** [comment]
Nope

**Comment by TheLimePixel** [comment]
Either way, that sounds like a CPU issue. Maybe try removing some visual mods?

**Comment by kd827827** [comment]
ok
