### ISSUE TITLE
Luminous Crafting Table Has No Recipe

### ISSUE THREAD

**Issue by Dystilled** [TheLimePixel/Modern-Skyblock-3#448]
Quest- Luminous crafting table

"To make a Luminous crafting table and a resonating wand, link the floating crystal to a crafting table and use the recipe in the journal"

JEI has no recipe. Clicking or pressing R on it does not provide a recipe. 

Quest book has no recipe. 

Guide has no recipe. 

Astral Tome/Journal requires the Luminous Crafting Table to create. 

Only item called Journal in JEI is for Agricraft. 

Even tried Linking Crystal to a crafting table to see if it shows a ghost recipe. Nope.

**Comment by TheLimePixel** [comment]
Oh, it's not called "Astral Tome". You can make it in a crafting table with a Crystal linked to it.

**Comment by Dystilled** [comment]
You still haven't said what the item actually is. 

Resonating wand is craftable in a crystal linked crafting table, but this doesn't address the fact theres no recipe for the table.
