### ISSUE TITLE
No recipe for Luminous Crafting Table- Closed Prematurely

### ISSUE THREAD

**Issue by Dystilled** [TheLimePixel/Modern-Skyblock-3#449]
You still haven't said what the item actually is that you need. 

Resonating wand is craftable in a crystal linked crafting table, but this doesn't address the fact theres no recipe for the table.

Luminous crafting table has no recipe indicated to the player in game.

**Comment by TheLimePixel** [comment]
It's in the Astral Tome.

**Comment by Dystilled** [comment]
So you need to update the pack to indicate this
