### ISSUE TITLE
[SSP] Previous Recipe Locked

### ISSUE THREAD

**Issue by DragonPHD** [TheLimePixel/Modern-Skyblock-3#450]
I have lost the ability to craft a hopper (Item unlocked in BA) although I unlocked it prior to the update. I have reset the questbook and relogged multiple times. 

I would surmise it is because it used to be BFaf (or something) and isn't considered the same. 

Mostly this is just a request for the command to use to re-unlock it

Thanks

**Comment by TheLimePixel** [comment]
3.3 changelog.
