### ISSUE TITLE
[Version 3.3.1.3] Server files zip missing libraries

### ISSUE THREAD

**Issue by thmarth** [TheLimePixel/Modern-Skyblock-3#460]
The server file zip for version 3.3.1.3 is missing some forge required library dependencies introduced in Forge 1.12.2 Build 2657.
Specifically, libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar

This library is automatically installed by Twitch, therefore most users won't have this issue.

**Comment by saytheb** [comment]
As a workaround until this is updated, anyone having the issue needs to grab the forge installer jar and use it to install the missing libraries. Remember, if you are on linux or running from command line, you'll want to use the --installServer param.
