### ISSUE TITLE
Minor Bug with PneumaticCraft/Tinkers' Construct

### ISSUE THREAD

**Issue by Jeffreyzilla** [TheLimePixel/Modern-Skyblock-3#464]
When placing any smeltable items in a PneumaticCraft machine (first tested with Coal in a Thermopneumatic Processing Plant, later confirmed with an Air Compressor and Gold Dust), breaking the machine with the smeltable contents inside results in it being smelted in an instant. This could be abused for easily smelting large amounts of items very quickly. The reason for this is having Autosmelt on a Tinkers' Pickaxe and breaking the machine with something smeltable inside results in the item bring smelted. I'm not sure if this works with other mods' machines as well (I'm not too far into the pack), but inserting it into Factorytech machines doesn't seem to cause this bug. I've tried to reproduce it with my other Tinkers' Pickaxe (without Autosmelt) and did not get the smelted item I would get with the Autosmelt Pick.

Steps to reproduce:
-Place a smeltable item (Example: Coal) in a PneumaticCraft machine, making sure it's not consumed by the machine in the process.
-Make a Tinkers' Pickaxe with Autosmelt on it (Firewood will do the trick).
-Break the PneumaticCraft machine with the Tinkers' Pickaxe.

I ended up testing this with multiple machines and smeltable items for testing purposes only.

If something isn't explained well or any questions arise, feel free to contact me.

-Jeffreyzilla

**Comment by TheLimePixel** [comment]
You're not on the latest version, are you?

**Comment by Jeffreyzilla** [comment]
I think I am but I also think I'm not. At seemingly random times the Twitch Launcher doesn't mention there's an update, so it's very possible that might be the issue. I'm currently playing version 3.3.1.2, and the client has no update for me as of yet. If there's a newer version that I am currently unaware of then hereby my sincere apologies, and I'll make sure it won't happen again in the future!

**Comment by TheLimePixel** [comment]
Well, yes, there is and this is fixed now. Don't worry about it, Twitch is just weird like that sometimes, I get it.
