### ISSUE TITLE
Empty FactoryTech Electric Furnace Generates Charcoal

### ISSUE THREAD

**Issue by xob** [TheLimePixel/Modern-Skyblock-3#465]
Not sure if this is specific to 3.3.1.3, as I only just crafted and placed the FactoryTech Electric Furnace, but there is a recipe in there that turns [nothing] into Charcoal.

This means that I can't leave the furnace empty with its required components, as it will just burn through those components to generate charcoal out of thin air.

**Comment by TheLimePixel** [comment]
It seems to happen because of this recipe: 
![image](https://user-images.githubusercontent.com/25333164/39239500-58cf79f0-4881-11e8-8d94-63724625ad8a.png)
 I have no idea what adds it, so, if I can't remove it, you've got infinite Charcoal until it's fixed in the mod that adds it.

**Comment by TheLimePixel** [comment]
Welp, GG. You've got infinite Charcoal.
