### ISSUE TITLE
Chicken Roost Collector recipe doesn't work. 

### ISSUE THREAD

**Issue by Dystilled** [TheLimePixel/Modern-Skyblock-3#468]
Says that Chicken is a missing item despite having it, breeding 2 chickens together to ensure its definitely a Roost chicken also does not solve the issue.

**Comment by TheLimePixel** [comment]
JEI doesn't handle items with NBT well. Just manually put it in there.

**Comment by Dystilled** [comment]
.... What?

The recipe doesn't work at all, it's not a JEI issue. I've tried it.
