### ISSUE TITLE
Chicken Roost Collector Recipe does not work. 

### ISSUE THREAD

**Issue by Dystilled** [TheLimePixel/Modern-Skyblock-3#469]
The issue I reported and you closed was not for JEI not putting the items in the crafting bench, it was that the recipe does not work at all. 

I have checked chickens picked up with the chicken rod, as well as vanilla chickens bred using the chicken mod and neither work.

**Comment by TheLimePixel** [comment]
Works perfect;y fine with any chicken that doesn't have stats
![image](https://user-images.githubusercontent.com/25333164/39239127-4a3dafa2-4880-11e8-9389-f6394b596f92.png)
![image](https://user-images.githubusercontent.com/25333164/39239137-506cf8ec-4880-11e8-8f2f-62b78a400063.png)
![image](https://user-images.githubusercontent.com/25333164/39239148-55d1461c-4880-11e8-9d2c-69bfe791a63b.png)

**Comment by IssaGalaxy** [comment]
I had the same issue i solved it by placing the chicken down again and then picking it up with the chicken stick and after that the recipe worked for some reason
