### ISSUE TITLE
Crushing Table - Gold Ore Block

### ISSUE THREAD

**Issue by corerupt83** [TheLimePixel/Modern-Skyblock-3#47]
Pack version 3.1
Multiplayer

The gold ore block when placed on the crushing table sometimes disappears, and when it doesn't you cant use the stone hammer to break it down into chunks.

**Comment by TheLimePixel** [comment]
Yes, you need an Iron Hammer to break it. Stone Hammers work on Ores that can be mined with a Stone Pick, Iron Hammers for those mined with an Iron Pick and the Steel Hammers with every ore
