### ISSUE TITLE
Ender I/O has bad pre-requisites

### ISSUE THREAD

**Issue by cinnamennen** [TheLimePixel/Modern-Skyblock-3#471]
In gated mode, to unlock Ender I/O you need to have unlocked Thermal Machinery and Actually Additions. To complete the quest requirements, you need Resonant Fluxduct, which requires Thermal Enhancements to be unlocked. Thermal Enhancements should be made a prereq for the Ender I/O quest.

**Comment by TheLimePixel** [comment]
Why would you need Thermal Enhancements for Resonant Fluxducts?

**Comment by TheLimePixel** [comment]
Oh, the items require it. Woops!
