### ISSUE TITLE
Chickens progression not intuitive

### ISSUE THREAD

**Issue by rayanth** [TheLimePixel/Modern-Skyblock-3#472]
In order to progress past Smart Chickens in the Chickens Chapter, Chemical Reactions is needed from Reborn Tech, which in the Questbook tab is not even visible yet if you're working the questbook row-by-row. Twice, this has caused me some confusion as I search through all of my open chapters for the 'Chemical Reactions' quest, only to find it's in a chapter that I don't even know how to get to yet.

Recommend trying to move Reborn Tech earlier... I understand the need for the chemical reactions for the recipes, not trying to recommend changing recipes for the basic chickens. Just see if Reborn Tech can at least be visible before or at the same time as Chickens.

Side note: 3.3.1.3, fresh install, While I can click on the chapters I have not unlocked to view them, you indicated in 3.3.1.2 notes that we should be able to see the entire stage line - I take this to assume we should be able to see the 'map' on the questbook tab for still-locked chapters, but that is not happening, at least in Staged mode.

**Comment by ThaDaVos** [comment]
Same here - would love to start with chickens now but locked because of Reborn Tech

Also not seeing the stage lines - in Gated mode

**Comment by TheLimePixel** [comment]
Fixed the latter. I won't be changing the placement of Tech Reborn, that is final.
