### ISSUE TITLE
[Version 3.3.1.4] Combustion Collector no longer recognized after update.

### ISSUE THREAD

**Issue by SuddenTurmoil** [TheLimePixel/Modern-Skyblock-3#475]
After updating to the latest version the combustion collector is no longer recognized as a known and placeable item. The quest stage had been completed prior to update. Questbook updated. Betterquesting restored from backup and updated. 

Unknown items are now also thrown on the ground if they enter your hotbar, a problem for washing Silent Gems early on. Not sure if this is intended behavior.

**Comment by TheLimePixel** [comment]
Well, you have 6 changelogs to read. Have fun!
