### ISSUE TITLE
[3.3.1.4] "Everything Needed For Messing With Genes" not recognizing fluids (Staged)

### ISSUE THREAD

**Issue by rayanth** [TheLimePixel/Modern-Skyblock-3#477]
the quest in Bees chapter titled 'Everything Needed for Messing With Genes' is not recognizing that I have any of the fluids in my inventory. Have tried adding every type of canister in full stacks. I noticed that when hovering over the required item in the questbook, it does not show a mod name in the tooltip, not sure if relevant.

Additionally, it used to be possible to see a quest ID when hovering over the quest in the quest chapter screen. It is no longer showing those, and I can't find any other way to identify the ID, so I cannot manually complete the quest using /bq_admin

**Comment by rayanth** [comment]
Same issue with Extracting From Trees in Thermal Machinery

**Comment by TheLimePixel** [comment]
Do you have all the fluids in your inventory?

**Comment by rayanth** [comment]
Tried with a bucket of each, and also with stacks of the larger capsules of each, no dice. Also, made sure to hit 'detect' each time I tried, in case it wasn't updating... several times.

**Comment by rayanth** [comment]
will continue testing with other fluids-required quests. Since it popped up in Thermal Machinery also, I'm suspecting it's a bigger problem. I've edited those two quests in this world to remove the fluid requirement so I could move on, but  can go back on a save to try again -- Will have to poke at it this weekend. Just crashed the game with the Planet Progression bug, and will have to try and resurrect a backup

**Comment by rayanth** [comment]
Will have to poke at it this weekend. Just crashed the game with the Planet Progression bug, and will have to try and resurrect a backup

**Comment by TheLimePixel** [comment]
Works fine for me, I just had to click the detect button.
