### ISSUE TITLE
Extra Planets Tier 10 Electric rocket

### ISSUE THREAD

**Issue by Elvi81** [TheLimePixel/Modern-Skyblock-3#478]
Nothing happens when you press space on this rocket even if it's fully charged and pressing space on all the other tiers work just fine.

**Comment by rayanth** [comment]
try exiting (left shift) and re-entering the rocket. I've found this fixes the issue when it happens on other rockets. seems to be caused by jumping into the rocket and hitting space too quickly after placing it.

**Comment by Elvi81** [comment]
Has absolutely no effect, and this does not affect the other rockets.

**Comment by Elvi81** [comment]
This issue is maybe fixed in the next Extra Planets update, update after version 0.3.3 that is.
