### ISSUE TITLE
[3.3.1.4] [Staged] Ender Machinery: Attraction Obelisk quest still requires Aversion Obelisk item

### ISSUE THREAD

**Issue by rayanth** [TheLimePixel/Modern-Skyblock-3#479]
As reported in bug #446, the staged mode quest 'Attraction Obelisk' requires the Aversion Obelisk. The 'Aversion Obelisk' quest also requires the aversion obelisk:

![bugeio](https://user-images.githubusercontent.com/8252741/39381858-6986ac58-4a18-11e8-9983-e8faa54587e1.PNG)

**Comment by rayanth** [comment]
With the Attractor Obelisk in my possession, this quest would not complete. With the Aversion Obelisk in my possession, both this quest and Aversion Obelisk quest completed at the same time.

**Comment by TheLimePixel** [comment]
Now, if you had provided an image then, it would have been fixed. I thought you meant it as in it requires the quest for it.

**Comment by ThaDaVos** [comment]
@EmosewaPixel Maybe set up somekind of bug/issue report template which people have to fill in?
