### ISSUE TITLE
Number/list of foods eaten resets on startup in 3.3.1.4

### ISSUE THREAD

**Issue by SumaniPardia** [TheLimePixel/Modern-Skyblock-3#480]
I had 298 foods eaten before updating to 3.3.1.4 from 3.3.1.3.  Now when I load my game I'm back to 8 hearts with no foods eaten.  If i try to copy over my backed-up solcarrot:food entry in my player.dat file (using NBTExplorer) it still resets it back to 0 entries after I load my game.  After testing a few foods in 3.3.1.4 it appears that Spice of Life: Carrot Edition changed the entry format from modname:fooditem to modname:fooditem@number.
![phcreset](https://user-images.githubusercontent.com/38802058/39391451-38e43254-4a69-11e8-91f8-8f91673db119.PNG)

**Comment by TheLimePixel** [comment]
Yes, in a way, it's intended. It fixed meta data not being recognized. However, you can probably fix it by copying the old one and adding @0 at the end of every entry.

**Comment by SumaniPardia** [comment]
In case someone else stumbles on this, you have to change it in the Level.dat > Data > Player section as well if you're playing single player.
