### ISSUE TITLE
Astral Sorcery Recipes not working

### ISSUE THREAD

**Issue by miscillo** [TheLimePixel/Modern-Skyblock-3#482]
Hi.

I'm having a wired problem with the latest version of the pack (3.3.1.4), staged version. 

I want to craft the Iridescent Altar. So I make an Infusion Altar with all its multiblock to craft the 4 resonating gems but it doesn't work. I check for wrong marble or other wrong blocks, but I can't find any error. After an hour, I decided to give myself the 4 resonating gems via cheats. 
But also the celestial altar doesn't want to work with the correct recipe... is there a problem with Astral Sorcery?

**Comment by ThaDaVos** [comment]
Have you checked that you have enough star light? Some recipes only work at almost midnight I noticed - I haven't encountered any issues with AS yet
