### ISSUE TITLE
Double ImmersiveEngineering core mods

### ISSUE THREAD

**Issue by henkaa** [TheLimePixel/Modern-Skyblock-3#484]
I updated to 3.3.1.4 of this pack and now I notice there are two ImmersiveEngineering core mods installed.
Is that a bug or intended?
I looked up what version it should be since I intend to send a bug report on the Wire Cutter that is now one time use for some reason.

ImmersiveEngineering-0.12.76-core
ImmersiveEngineering-0.12.80-core

**Comment by TheLimePixel** [comment]
Twitch doesn't delete them when updating, not my problem.

**Comment by henkaa** [comment]
So if I manually delete the 76 on my side (and on server) it should be as intended?

**Comment by TheLimePixel** [comment]
Yes

**Comment by henkaa** [comment]
Great. Hope that solves my Immersive Enginnering glitches then.
Thanks for the input.
