### ISSUE TITLE
Questbook Autocompletes quests for unselected gamemode

### ISSUE THREAD

**Issue by AetherialMist** [TheLimePixel/Modern-Skyblock-3#485]
I have had this happen a few times across different versions. In this case I was in staged mode, but I have had it happen while in kitchensink mode as well. The questbook starts saying I completed quests in the gamemode I did NOT select. This happened whenever I logged-out and log back into the world (singleplayer). It doesn't affect the restricted items, as long as I don't claim the "completed" quests from the wrong line. But the two quest lines do end up overlapping (which is annoying when trying to claim the correct stages). Also I have never played on Gated mode on any of the versions. I have also included a picture of my inventory if that is of any use (The island deletion bug seems to be related to certain items left in the inventory when logging into a world). reloading the questbook does not fix this either.
![inventory](https://user-images.githubusercontent.com/25269014/39413818-983c864c-4bf5-11e8-85bc-e3566907c403.jpg)
![questbook bug](https://user-images.githubusercontent.com/25269014/39413819-984c9c3a-4bf5-11e8-96d4-0e1624098c0e.jpg)

**Comment by TheLimePixel** [comment]
Revert to a backup.
