### ISSUE TITLE
Recipes missing for Simply Jetpacks armor.

### ISSUE THREAD

**Issue by DraegonX** [TheLimePixel/Modern-Skyblock-3#487]
Hi.  I'm playing the current version (3.3.1.4) and there is no recipe for the upgraded armor plating for Simply Jetpacks.  It worked previously, I believe in the induction smelter (I have enderium plating on my jetpack).  As it stands this is blocking at least one quest for the flux-infused jetplate.

**Comment by Aurrelsick** [comment]
Hi, same problem here in current version (3.3.1.4), i play in gated mode and i can't unlock 'digital storage' (64 Enderium armor plating needed) and same problem for the flux-infused jetplate quest.

**Comment by CarlSmotricz** [comment]
Me three! :( 
Digital Storage is also a gate to several other pages.
