### ISSUE TITLE
Calculator sickle is uncraftable.

### ISSUE THREAD

**Issue by DraegonX** [TheLimePixel/Modern-Skyblock-3#488]
Hi.  The Calculator sickle is not currently craftable, because the shovel and axe it is crafted from are crafting incorrectly.  The ingredients (reinforced stone and sticks) result in Silent's Gems tools instead of Calculator tools.  I tried using the Silent's Gems tools in the recipe but they don't work.  Thanks.

**Comment by TheLimePixel** [comment]
Forestry Worktable.
