### ISSUE TITLE
RFtools quest line requires awakened draconium from tpod

### ISSUE THREAD

**Issue by drewkeating** [TheLimePixel/Modern-Skyblock-3#492]
In the quest book, under RFtools, the quest "Custom Dimensions" requires the quest "Awakened Draconium" from the "The Power Of Dragons" quest line. The issue with that is, I need to finish the Advanced Defense quest line to unlock tpod, but I need Guardian Scales to complete AD. The only place I can think of to find guardians is in an rftools dimension.

**Comment by thmarth** [comment]
Guardians can spawn in a cursed earth mob farm.

**Comment by Elvi81** [comment]
Just make a water "pool" in a slime chunk, they seem to spawn there.

**Comment by TheLimePixel** [comment]
It needs to be an ocean people.

**Comment by drewkeating** [comment]
Pixel was right, Guardians will spawn in an ocean biome. I flew around until I found one, placed an angel block to build from, and built a guardian farm in an ocean biome.
