### ISSUE TITLE
[3.3.1.4] Fluffy Puff Seeds isn't dropped

### ISSUE THREAD

**Issue by progre** [TheLimePixel/Modern-Skyblock-3#495]
I punched grasses many time, but fluffy puff seeds isn't dropped. but other seeds was dropped.
It makes it impossible to complete that Seeds quest in Basic Resources.

I'm interesting to effect of AgriCraft and it's configurations doesn't contained fluffypuff seeds.

**Comment by TheLimePixel** [comment]
They're just rare.

**Comment by progre** [comment]
Oh.... Certainly they were just rare.
