### ISSUE TITLE
a power not connect to fusion injector

### ISSUE THREAD

**Issue by BuGRocK** [TheLimePixel/Modern-Skyblock-3#496]
i try many way to connect a power to my injector i try a conduit but not connect to block / wire it connect but no power plz tell me what to do
![2018-05-03_17 27 46](https://user-images.githubusercontent.com/38297665/39572267-b415df52-4ef8-11e8-8384-615ad5549b4c.png)

**Comment by TheLimePixel** [comment]
Use Energy Relay Crystals. Draconic Evolution specifically uses RF, so only its Relay Crystals and TE's ducts will work.

**Comment by BuGRocK** [comment]
i try but it not work 
![2018-05-05_03 57 08](https://user-images.githubusercontent.com/38297665/39652771-e562153c-5018-11e8-8277-6f4311bcf512.png)
![2018-05-05_03 57 11](https://user-images.githubusercontent.com/38297665/39652772-e5a14dc4-5018-11e8-9c5d-cfca53493a3e.png)
