### ISSUE TITLE
a power not connect to fusion injector #2 

### ISSUE THREAD

**Issue by BuGRocK** [TheLimePixel/Modern-Skyblock-3#499]
i try u comment but it not work i connect all crystal and have a power in crystal but power not sent to injector? 
![2018-05-05_03 57 08](https://user-images.githubusercontent.com/38297665/39652825-21b61128-5019-11e8-8203-adf75a1d3389.png)
![2018-05-05_03 57 11](https://user-images.githubusercontent.com/38297665/39652826-21f02e26-5019-11e8-981b-f9027dcc239b.png)

**Comment by BuGRocK** [comment]
i try to start a fusion and it don't work

**Comment by TheLimePixel** [comment]
That's not how they work... You link a crystal to them via the wrench.

**Comment by BuGRocK** [comment]
yes i do i binding with a crystal binding
​

2018-05-05 13:00 GMT+07:00 EmosewaPixel <notifications@github.com>:

**Comment by thmarth** [comment]
Use the Wireless Energy Crystal and bind it directly to the Fusion Crafting Injector

**Comment by BuGRocK** [comment]
sorry me again i try to do with you tell me but it say "that is not a valid
device"

2018-05-06 21:56 GMT+07:00 Thorgeir Marthinussen <notifications@github.com>:

**Comment by BuGRocK** [comment]
Oh sarry it's my error user T^T / i use a wrong item crystal relay vice a
energy

2018-05-09 4:15 GMT+07:00 rock <morok4@gmail.com>:
