### ISSUE TITLE
Epic Loot Samurai Helmet

### ISSUE THREAD

**Issue by Vuudrasil** [TheLimePixel/Modern-Skyblock-3#504]
Not sure if this is a bug, but I am pretty sure it is. Today I got a viking Helmet that had an effect of increasing luck by 934. This is extremely broken and allows me to get too much loot from mobs. (Also, the luck effect seems to be only working on Reliquary mob drops o.o)

~~edit-this was a viking helmet, not a samurai helmet.

**Comment by ThaDaVos** [comment]
A lot of items from the same mod have this - I had a helmet which gave me 999 luck - only thing I had to do was kill one enderman and I got stacks of those hearts
