### ISSUE TITLE
Factory Tech bug

### ISSUE THREAD

**Issue by zxmegamanfan** [TheLimePixel/Modern-Skyblock-3#505]
I seem to have found a bug with the electric furnace in that i put wood into it and i get charcoal...but that stack was done already and im getting an unlimited amount of charcoal...i already broke it and replaced it, cheated in and still...its making more charcoal. Im on ver. 3.3.1.4, single player.

**Comment by shadow306k** [comment]
#497 Yeah, this is a thing, with no currently known fix.

**Comment by zxmegamanfan** [comment]
Ok cool...then i shouldn't feel bad about cheating in the parts...
