### ISSUE TITLE
Staged Mode is locked out

### ISSUE THREAD

**Issue by bluejim31** [TheLimePixel/Modern-Skyblock-3#506]
it appears going through staged mode results in Basic resources and Basic tinkering  having 0/0 Tasks Complete and not being able to complete them, So can't unlock the continuing quests.
See https://imgur.com/a/O7nUoXz for screenshots.
Tested it on Single player and get the same issue, however gated mode works.

**Comment by Elite29er** [comment]
Having the same issue. Also, it would seem all the trigger quests are borked.

**Comment by TheLMiffy1111** [comment]
same issue

**Comment by drewkeating** [comment]
I'm having the same issue, but with the "Overpowered" quest line being locked. I just finished all the quest lines, but the last one is still locked. It says it needs "The power of dragons - draconic reactor", but that's the quest I just completed.

**Comment by shadowpanther** [comment]
Same issue in 3.4.1 - gate quests completed, checkboxes in questbook tab checked, next quest lines are still locked. https://imgur.com/a/ewNlw0M
