### ISSUE TITLE
[3.4] Opening galaxy map crashes the client

### ISSUE THREAD

**Issue by MoshiMoshi0** [TheLimePixel/Modern-Skyblock-3#508]
[Crash log](https://pastebin.com/mqan9aa7)

Seems like the problem is in ExtraPlanets [here](https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/client/handlers/MainHandlerClient.java#L383-L393) and Planet Progression [here](https://github.com/MJRLegends/Planet-Progression/blob/dev_1.12.2/src/main/java/com/mjr/planetprogression/client/handlers/MainHandlerClient.java#L60-L68) although I tried downgrading both mods to the versions in 3.3.1.4 and the crash was still happening.
I also tried to downgrade forge to 2670 like in 3.3.1.4.

**Comment by MoshiMoshi0** [comment]
So after some digging it seems that extraplanets and planet progression are only partially a problem here.
The main problem is I think logic change in FTBUtilities 5.0.2.11 [here](https://github.com/LatvianModder/FTBUtilities/commit/b0bbabc90a04f6f557657047f2c7ea55877da046#diff-b3941c1d66d237989187e3d5502d1a4cL43). Blame [commit](https://github.com/LatvianModder/FTBUtilities/commit/b0bbabc90a04f6f557657047f2c7ea55877da046).

I tried downgrading FTBUtilities and FTBLib to 5.0.2.10 but the pack crashes on loading.

**Comment by lrwerewolf** [comment]
I too am seeing this issue.  Crash report at: https://pastebin.com/Vv5sDELG

**Comment by lrwerewolf** [comment]
By turning off the ranks in config/ftbutilities.cfg, I was able to successfully use the research paper in the telescope and then launch my tier 1 rocket and land on the moon.  I had to test though with a given research paper as the Satellite Controller seemed broken.  Resetting it allowed research for the moon to continue, however.

**Comment by Segaja** [comment]
I can confirm that this workaround works.
