### ISSUE TITLE
AE2 Network/Cables don't recognise the futura chiseled ME Controllers

### ISSUE THREAD

**Issue by Dystilled** [TheLimePixel/Modern-Skyblock-3#510]
Don't think I've ever seen a modpack where they don't automatically work. Not sure why they're not being detected by AE2. 

Nothing will connect to them, wont accept power from anything, cables won't connect at all. 

Using a plain looking ME controller works fine, just not the chiselled versions.

**Comment by ThaDaVos** [comment]
The Futura chiseled ones are made from non-AE2 blocks right?
I think those are for decoration only

**Comment by Dystilled** [comment]
As mentioned they've always worked in other packs. 

They're my go to for ME Controllers because the vanilla one is so boring

**Comment by ThaDaVos** [comment]
Maybe post an issue on the mods pages - AE2 and Chisel mod - it's not something the modpack author can fix - at least I think

**Comment by Dystilled** [comment]
My assumption was that if its working on other packs I've played its an implementation/setting in the pack.

**Comment by ThaDaVos** [comment]
Check if the other packs use the same versions of both mods

**Comment by ThaDaVos** [comment]
Same version of forge also - it may also be a conflict with another mod present in this pack and not present in those

**Comment by TheLimePixel** [comment]
Nope, they've never worked. They're just a troll reward. What you're thinking of is an ME Controller.
