### ISSUE TITLE
Missing Recipe

### ISSUE THREAD

**Issue by Igor48e** [TheLimePixel/Modern-Skyblock-3#511]
The Golden Lasso from Extra Utilities 2 (I have it unlocked) has no Recipe.

**Comment by MaxNeedsSnacks** [comment]
That's merely a visual glitch from what I can tell, I can still craft it in a Vanilla crafting table (with the required amount of XP).

Here's the recipe again for future reference

![Golden Lasso](https://user-images.githubusercontent.com/12750501/39773502-a1119050-52f8-11e8-9090-494ba69eb81b.png)
