### ISSUE TITLE
Server Crash, Version 3.4

### ISSUE THREAD

**Issue by hk21702** [TheLimePixel/Modern-Skyblock-3#513]
https://pastebin.com/MuLJZjR5

Seems to be related to thaumcraft mob spawning. Can confirm the map had an area where mob spawns were possible. 

I did have an extra java argument on the server start file but it was just an increase to when timeout from the server would occur.

**Comment by MaxNeedsSnacks** [comment]
Seems to be a known issue in Thaumcraft (Azanor/thaumcraft-beta#616), Azanor mentioned Mod Interaction between Hats and Thaumcraft. For now, it's best to just disable spawning Pechs entirely within the thaumcraft_world.cfg file. (@EmosewaPixel you might want to ship this as the "default" config to prevent further crashes and issues)
