### ISSUE TITLE
crashes when trying to do inital loading of mods 

### ISSUE THREAD

**Issue by firewis** [TheLimePixel/Modern-Skyblock-3#514]
it won't even let me get to the single-player multiplayer screen 
[crash-2018-05-08_22.51.05-client.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1986232/crash-2018-05-08_22.51.05-client.txt)
[crash-2018-05-08_22.43.02-client.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1986233/crash-2018-05-08_22.43.02-client.txt)

**Comment by Tatzumori** [comment]
Hi, have you opened in background MSI Afterburner and Riva Tuner? if yes, try close them and launch again.

**Comment by TheLimePixel** [comment]
Simply restart your computer to fix it.
