### ISSUE TITLE
IE: Solor Tower not work anymore 3.4

### ISSUE THREAD

**Issue by GeertJanP85** [TheLimePixel/Modern-Skyblock-3#515]
Im playing on the version 3.4 of the mod pack and its single player. Before the update to 3.4 the solor tower was working for but after that it doesnt.

I have also moved it and its in 1 chunk with no blocks above it. I have 4 Solar Reflectors 2 against the tower and 2 1 block away to see if that makes any differents.

Normal the 4 boxex on the interface should light up but there dont.
![2018-05-09_08 48 53](https://user-images.githubusercontent.com/34487691/39799958-6fbb3448-5366-11e8-9eb3-4db62cdd1a84.png)
![2018-05-09_08 49 13](https://user-images.githubusercontent.com/34487691/39799959-6fd824c2-5366-11e8-95f8-83382be05490.png)

**Comment by TheLimePixel** [comment]
Second to last sentence
![image](https://user-images.githubusercontent.com/25333164/40330837-7fd2c0f2-5d4e-11e8-8389-2c7714588cdd.png)

**Comment by f0kx** [comment]
Hey Dude i also have this problem and after a few testing it was a mod i needed to downgrade 
Mods i Downgrade that it works
immersivetech-1.12-1.3.8 -> immersivetech-1.12-1.3.7-SevTech-Ages
ImmersiveEngineering-0.12-82 -> ImmersiveEngineering-0.12-81

**Comment by TheLimePixel** [comment]
Did you read my message? It doesn't work because it was changed so the reflectors need to be 5-10 blocks away.

**Comment by f0kx** [comment]
Fuck i tested it and i thing i build it only 4 blocks away and thought thats not the reason SRY my mistake!
after testing it again you are right you are always right :D
