### ISSUE TITLE
Bad interactions between tinkers construct crafting table and botania petal apothecary

### ISSUE THREAD

**Issue by Delerium** [TheLimePixel/Modern-Skyblock-3#52]
If the crafting table is placed next to the petal apothecary, and any items from the crafting table get auto-deposited into the petal apothecary (strangely I guess this can happen?), it will crash your game and corrupt your save.  I had to use mcedit to delete the petal apothecary in order to load my save again.

**Comment by TheLimePixel** [comment]
As far as I know, there is no blacklist, so there's nothing I can do about this.
