### ISSUE TITLE
Hopper Issues

### ISSUE THREAD

**Issue by Bazza546** [TheLimePixel/Modern-Skyblock-3#520]
After you put a hopper down, connecting it to the inventory that it needs to go to it all works fine but when you log off and return later on, the hopper pulls items from other things, for example, i have an automated consender set up, with a hopper below it, it would take the iron it produces and would pump it into a chest by its side, but once i turn off minecraft and return later the hopper would pull alchemical ore from the condenser and into the chest it was connected too, currently the condenser is the only thing i've noticed that does this, unsure of other objects it could be doing it with.

**Comment by Bickers07** [comment]
the condenser doesn't need a hopper it ejects to any inventory below it anyway
