### ISSUE TITLE
Wearable battery type items randomly insert themselves into chest slot

### ISSUE THREAD

**Issue by Dystilled** [TheLimePixel/Modern-Skyblock-3#526]
Have this happen probably every 2nd or 3rd day of playing the pack. 

If I'm carrying an item such as a lithium batpack, occasionally it will place itself in my chest slot and move what was in my chest slot (i.e armour or jetpack) to my inventory. 

These items can not be Shift Clicked into that space without it being empty, so is not user error. 

Something is causing the items to switch places for no reason.

**Comment by TheLimePixel** [comment]
Probably some weirdness with Inventory Tweaks. Nothing I can do about.
