### ISSUE TITLE
Quest tab completed but trophy not claimable

### ISSUE THREAD

**Issue by Segaja** [TheLimePixel/Modern-Skyblock-3#528]
I have completed the Better Storage quest line (https://i.imgur.com/wpu8vO9.png) but in the Trophy Room tab I can't claim the trophy for it: https://i.imgur.com/LT3IZBf.png

I'm on latest version (3.4).

**Comment by drcrazy** [comment]
Same for me with advanced thermal and Cooking quest lines. 0\0 on trophy page

![image](https://user-images.githubusercontent.com/1382352/40207187-f314251c-5a3b-11e8-8007-b6cbb03d5bc0.png)
