### ISSUE TITLE
cannot load version 3.4 from twitch

### ISSUE THREAD

**Issue by vizzair** [TheLimePixel/Modern-Skyblock-3#530]
When I load the modpack only 3 mods are installed ! 
Galaticraft planets 1.12.2-4.0.1.176,
 Galaticraft core 1.12.2-4.0.1.176 
and micdoodleCore 1.12.2-4.0.1.176

But the configs for all the mods are downloaded.

Obviously there is no game to play. In case it was something with twitch or my profiles, I created another mod area on a second drive and attemped again. Still nothing. 
Version 3.3.1.3 it the last version I can play. If i attempt to update to 3.4 it deletes all the files in the mod area and just leave the 3 above. 

All other modpacks i have loaded work fine . ( Dirkworl , Enigmatic 2, all the Ozone packs etc

Using twitch client Version 7.5.6702.487 Live
Java build 1.8.0_171-b11 64 bit
windows 10 32Gb memory NVidia gtx 1080
Everything updated to latest version

**Comment by Balorn** [comment]
This is apparently a curse/twitch issue. I got around it by manually downloading the zip from the pack page and pointing MultiMC at it.

**Comment by saytheb** [comment]
Yep, I had to do the same (download zip and move to MultiMC). Curse seems to have some major issues right now downloading files.

For those hesitant to use MultiMC.. it's actually easier than Twitch to use for Minecraft these days. Run it, open the zip from curseforge after retrying the downloading 10+ times, then launch when it's done!

**Comment by vizzair** [comment]
looks like multiMC it is then
