### ISSUE TITLE
[Suggestion] Temporarily downgrade FTBUtilities to 5.0.2.10 as hotfix for Galacticraft issue

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [TheLimePixel/Modern-Skyblock-3#532]
It is already a known issue that opening the galacticraft map crashes the game, as shown in your own issue on MJRLegends/ExtraPlanets#300.

However, after investigating the [crash report](https://pastebin.com/mqan9aa7) and checking the source code suggested by [this comment](https://github.com/MJRLegends/ExtraPlanets/issues/300#issuecomment-388436330) it becomes fairly obvious that while there definitely is an error on Galacticraft's end (which has been fixed, but will probably still take time to ship to a release), the exception that causes the game to crash is thrown by FTB Utilities, more specifically, version .11, because as mentioned in the comment, version .10 does not cause this problem.

While it is definitely a janky solution to "ignore" this error and just downgrade so the game won't **crash** because of it, it would still solve a huge problem many people (including myself, as I am currently stuck in a crash loop after going to space with a rocket) are having with progressing through the mod pack until the fix eventually got shipped in a new version of Galacticraft and then included in a later pack update.

**Comment by Segaja** [comment]
As mentioned [here](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/508#issuecomment-388714594) there is a workaround by disabling the ranks feature in ftbutilities.
