### ISSUE TITLE
Crash and issues with stage "heavy machinery"

### ISSUE THREAD

**Issue by fernando2do** [TheLimePixel/Modern-Skyblock-3#533]
my game got crashed without a crash report when i use some stuff of the immersive engineering mod, not specificly with a certain item, but i had no problems before with the modpack until i reach this mod, i noticed the crashes most times when i use the book of this mod.

also i noticed in the questbook there are some missions that i cannot unlock because it looks like i neet to complete a mission before but this is not in the page. thanks beforehand for checking it. :)

http://subirimagen.me/uploads/20180515142938.jpg

**Comment by Dystilled** [comment]
How do you know IE is responsible if you weren't specifically using something from it when you crashed? 

Not much to go on there

**Comment by fernando2do** [comment]
i have the first crash when i tried to use the crusher, three times i got crashed, i think that is this mod because it crashes 2 or 3 minutes before to interact with it, i hope you can take a look for please

**Comment by fernando2do** [comment]
or there is a file created automatically when the game crash? i dont know very much of minecraft modding :c

**Comment by Khalkion** [comment]
There is a known issue with IE book and old java versions. That's why IE tries to warn you on log in that you are not using the latest version. Bundled version of java that is downloaded automatically by minecraft is too old, switch to newer one.

**Comment by fernando2do** [comment]
Thank you so much, so there is a single way  to switch the version? Sorry if I'm annoying :c

**Comment by Khalkion** [comment]
For Twitch launcher:  https://goo.gl/cCcNu2

**Comment by Khalkion** [comment]
For twitch launcher: https://goo.gl/cCcNu2
For at launcher: https://www.ghacks.net/2015/03/11/change-which-version-of-java-minecraft-uses/
Java: https://java.com
8.171 is ok.

**Comment by fernando2do** [comment]
Thank you so much, you are my hero :)
