### ISSUE TITLE
[3.3.1.4] No trophy in staged mode

### ISSUE THREAD

**Issue by progre** [TheLimePixel/Modern-Skyblock-3#534]
I finished some quests, but I can't get some trophies.

I finished;
![rapture_20180516204530](https://user-images.githubusercontent.com/1272114/40115622-004d2f6c-594c-11e8-8c2b-fbcc1c055a6c.jpg)
![rapture_20180516204537](https://user-images.githubusercontent.com/1272114/40115625-0078ef9e-594c-11e8-8b85-b3d5968bc2dc.jpg)

But, I don't have these trophies;
![rapture_20180516204544](https://user-images.githubusercontent.com/1272114/40115692-43708fc8-594c-11e8-82a6-240f4526d5d2.jpg)

**Comment by thmarth** [comment]
For Basic Automation, see the empty spaces below the Vector Plate quest, there are two more tiers of vector plates that require components you unlock later on, at least one of them requires reaching The End.
Can't remember of the top of my head when that is unlocked.

For Mystical Flora, I believe there are similar restrictions, but don't have the game up to verify right now.

Still, it's kinda misleading that the quests are hidden until all the prerequisites are unlocked/completed.

**Comment by progre** [comment]
OK. Thx tagging.
