### ISSUE TITLE
[3.3.1.4] Why can't I craft Energy Laser Relay in staged mode?

### ISSUE THREAD

**Issue by progre** [TheLimePixel/Modern-Skyblock-3#535]
I already unlocked Actually Additions, but why can't I craft Energy Laser Relay?

![rapture_20180516204616](https://user-images.githubusercontent.com/1272114/40115884-d226c480-594c-11e8-82fd-e77e507edcbf.jpg)
![rapture_20180516204801](https://user-images.githubusercontent.com/1272114/40115887-d5016b1a-594c-11e8-9ec8-6d0ef54a812a.jpg)

**Comment by Bickers07** [comment]
might be intentional its blocked behind draconic as you can class it as wireless transfer i personally went from Immersive> extra util>thermal

**Comment by progre** [comment]
Hmm...
I thought I wanna use it for empowerer. It seem those are locked yet.

**Comment by Mc-man165** [comment]
Just advance to Immersive engineering and use the wires t connect them all
