### ISSUE TITLE
Can't Seem To move

### ISSUE THREAD

**Issue by Fluroclad** [TheLimePixel/Modern-Skyblock-3#536]
When I try and move around on the bedrock platform or any over island the camera goes crazy (rotating/moving for a couple of seconds and then seems to settle back) and I seem to stay in the exact same position.

MSB 3.4,

Playing on server as well!

**Comment by Fluroclad** [comment]
Only seems to happen if I fall off the island. However if I die or accidentally fall off, I have to create a fresh new save of the world so the camera doesn't go crazy

**Comment by Dystilled** [comment]
Have you tried going into creative mode and breaking the block under your feet?

**Comment by samiratou** [comment]
I'm having a very similar issue today. I updated to 3.4.1.1 a few days ago and it was fine. Today I log in and try to move and I get launched in the air or something. Second time I tried I got launched 1000 blocks from my base. Managed to get back to my base but once I go there any time I tried any WASD  key I got sky view but don't move. Tried logging off of the world and back on (single player). Could move sideways or backwards but not forwards (Including in creative mode). After a few tries I got sent 17K blocks away from my base and Java crashed. Reloaded the pack and I'm still 17K blocks away and can't move forward. 

Restored a backup world from the other night, and similar behavior with W making the camera go all crazy but I can't move forward (though ASD work fine). Tried jump moving and the screen turned mostly yellow, then black, then Java crashed again.

Last few lines of the log:
[18:36:32] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: Finished Aspect ItemStack Thread.
Exception in thread "Hats Mod Mob Support Thread" 
Process crashed with exitcode -805306369.

Full log here: https://paste.ee/p/6WpK5

**Comment by samiratou** [comment]
Tried a few things, including disabling Hats (in MultiMC) and loading a few previous backups, and the issue persisted. Reverted to 3.4.1 and everything seems fine at the moment.

**Comment by Kausta** [comment]
Using Taylor's algorithm in Better FPS causes the same problem for me, but switching back to Riven's "Half" fixes it. Maybe you had changed it before but haven't restarted ?

**Comment by Fluroclad** [comment]
The Taylor's Algorithm in BetterFPS was the cause of the issue. Thank you very much. Switching to Riven's resolved the problem (after a restart)
