### ISSUE TITLE
Error when loading up the game

### ISSUE THREAD

**Issue by MatttHumphrey** [TheLimePixel/Modern-Skyblock-3#537]
When loading the game through the Twitch launcher, it gets to 3 of 7 on the loading screens and then crashes, giving an error message relating to GenDustry. I have had this issue 3 times now while trying to load it up. I have tried opening it on a range of different RAM allocations, but with no success.

Crash Report: https://pastebin.com/VZhBmTdJ

**Comment by MatttHumphrey** [comment]
And i get this crash message.

https://gyazo.com/4e9cdfdf2a4eee9ea7c0b8c4e2c35bfb

I have not edited anything within the files, and it was downloaded yesterday, so i have no idea what might be causing this.
(I loaded it up many times between 6 and 12 gigabytes of ram to see if anything would happen, and nothing did)

**Comment by TheLimePixel** [comment]
Probably one of those random crashes after first downloading a pack. Just restart your computer and you should be fine.

**Comment by MatttHumphrey** [comment]
Thanks. I have had no luck yet, but i know now that it is not an issue with this pack. I am having this issue with quite a few packs that i download, so I am checking with Curse to see if there is anything they can do. Thanks again.
