### ISSUE TITLE
Quest book mistake

### ISSUE THREAD

**Issue by TheShadowSpirit** [TheLimePixel/Modern-Skyblock-3#539]
Sorry if it's in the wrong place, please let me know where to post it next time. I'm using the last version of MBS3 and in the quest book, although I'm not far in it yet, in the agricraft tab, there are 2 mistakes that I've "discovered".

First one :https://gyazo.com/ceb47dad425de279f7db6ccbac40b67c
Second one :https://gyazo.com/5268844a258016b1e715517339142344
(Don't know if those links will work either)

I hope I don't find anymore mistakes ;)

**Comment by TheLimePixel** [comment]
Umm... there are no links there

**Comment by TheShadowSpirit** [comment]
I have no idea why they disappeared but they were there when i posted it... anyway i put them back. Should work now.

**Comment by AriinPHD** [comment]
@TheShadowSpirit What is the mistake you have discovered? Could you explain it?

**Comment by Runesmacher** [comment]
Issues according to me seem to be in the text:
First one: Double "ss" in the word "guess"
Second one: i can't seem to find "mily" in a dictionary ;)

**Comment by TheShadowSpirit** [comment]
@Runesmacher You're right for the 2nd one, though the 1st one is another quest description mistake : it says 5 tier 2 seeds instead of 5 tier 12 seeds.
Guess does always need 2 "s" :)

By the way sorry Pixel if you don't consider this a bug though. As I said I don't know where to post simple spelling mistakes.

**Comment by Runesmacher** [comment]
dangit my english has failed me for the first one :)
