### ISSUE TITLE
ae crafting table - recipe stages - not working (dup of #35)

### ISSUE THREAD

**Issue by DoomSquirter** [TheLimePixel/Modern-Skyblock-3#54]
Essentially #35 .  not sure if it'll see activity since it was closed already.

any stage protected crafting recipe (i.e. bonsai or bag opener, etc) will show up as a craftable item in output but you won't be able to take it out.

upon further investigation, you might have to use something along the lines of this:
mods.recipestages.Recipes.setPackageStage("appeng", allStages);
but an allStages group would need to be created or something similar and I'm a neophyte at ct so I can't test it.

from http://crafttweaker.readthedocs.io/en/latest/#Mods/GameStages/RecipeStages/RecipeStages/

**Comment by TheLimePixel** [comment]
Oh... I didn't test taking it out...
