### ISSUE TITLE
[3.4.1] crashing on world load

### ISSUE THREAD

**Issue by drag498** [TheLimePixel/Modern-Skyblock-3#543]
[crash-2018-05-22_06.39.45-server.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/2026904/crash-2018-05-22_06.39.45-server.txt)
So when ever I try to load up my world in the lastest 3.4.1 version, it crashes every single time with this same error shown in the crash log linked above.
When I revert back to version 3.4, I'm able to load up the world perfectly fine with no issues what so ever.
As far as I can tell from the crash report, none of the mods are erroring out, and seems to be an entity spawn issue? But I'm not entirely sure.

**Comment by Kzorith** [comment]
It looks like something that's either on you or you are riding in.  Maybe put all your inventory into a chest while in 3.4, make sure you aren't carrying or riding anything and then try the upgrade again to see if you get the same or different error.

**Comment by drag498** [comment]
this error is with an empty inventory and me standing on the ground

**Comment by Kzorith** [comment]
The mod complaining is Cazsius' Spice of Life.  I don't see any bug reports on that mod's issue page regarding a crash on start.  Perhaps someone more enlightened in the ways of Minecraft can advise a course of action outside of deleting your player file and letting Minecraft recreate it.

**Comment by drag498** [comment]
sadly ive already tried that deletion of player data doesnt result in any change

**Comment by Kzorith** [comment]
You might want to raise this on the Spice of Life page (https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues) as well to see if Cazsius has any ideas.

**Comment by drag498** [comment]
oddly enough an older world i have that was in kitchen sink mode loads up just fine in 3.4.1

**Comment by Kzorith** [comment]
The crash log definitely points to a problem reading some NBT tag on your character in that game.  Unfortunately that's a far as I can take the log.

**Comment by drag498** [comment]
hmmm well where ever that nbt tag is saved it seems to not be in the player data folder :/

**Comment by drag498** [comment]
there is other player data under data/ftb_lib/players hopefully its saved there and deleting that file solves the issue. 
Edit: Nope wasn't it.

**Comment by drag498** [comment]
what im assuming is that a food item removed from the recent removal of several mods, that I ate, and was counted towards the 50 food variety to increase max health thing from spice of life is still tagged. even though the modded food is removed and perhaps that is whats causing the issue since said food item no longer exists. So basically a now non existent food is still counting towards the 50 foods eaten and so maybe thats whats the cause of the issue.

**Comment by karbonkitt** [comment]
What's interesting is that this appears to be the same issue that was marked as resolved in https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/23
Attempting to clear the food list of a player even results in the same error. A potential workaround may be finding where the foodlist is stored per player and removing the entries from the file manually.

**Comment by drag498** [comment]
well for my kitchen sink world that works just fine in 3.4.1 im going to use it as a test for my theory to see if it is indeed that bug

**Comment by jurebj** [comment]
It's the statues mod

**Comment by drag498** [comment]
well that would make sense ive eaten a royal nugget from the statues mod so thats probably the food item thats still being flagged under spice of life as being eaten towards the 50 food count, even though its gone.

**Comment by karbonkitt** [comment]
Was able to connect after deleting entries from removed mods from solcarrot:food
![image](https://user-images.githubusercontent.com/5123747/40379356-7944b0ca-5dbb-11e8-8f55-25f78ca7f764.png)
Look for anything prefaced statues: or binnies:

Gonna be really fun doing this for all my players...

**Comment by drag498** [comment]
how did you find those?

**Comment by drag498** [comment]
ok removed those nbt tags giving it a try now

**Comment by karbonkitt** [comment]
Also fun thing I've noticed going through all my player's foodlists, Tinkers Construct's 'Mom's Spaghetti' counts as a new food at each point of durability for spice of life, meaning ~100 of a players 'unique foods' are that single item granting 2 hearts.

**Comment by drag498** [comment]
so i removed the nbt data with the nbtexplorer but im still getting the same error

**Comment by drag498** [comment]
ok found the same nbt tags saved under level.dat as well as in the player data folder

**Comment by drag498** [comment]
hey hey I am now up and running on 3.4.1! thanks for the help karbonkitt :D

**Comment by Kzorith** [comment]
So, anyone who as eaten the Royal Nugget from the Statues mod will likely hit the same problem?

**Comment by karbonkitt** [comment]
Very likely, I also had a binbiescore glass entry in there for some reason that I had to take out as well.

**Comment by Dystilled** [comment]
https://pastebin.com/twXtgMsL

Also unable to load in the new update. 

I don't have royal nugget in my eaten foods, No Binnies/Statue tags in my eaten foods either.

**Comment by Dystilled** [comment]
https://imgur.com/a/uHOXvXn

These are my eaten foods

**Comment by drag498** [comment]
did you double check in the level.dat and level.dat_old file as well? the nbt tags show up there as well for single player.

**Comment by Dystilled** [comment]
the solcarrot section of the player file in all 3 areas seems to be identical to the screenshot I posted above.

**Comment by Dystilled** [comment]
Industrial Meat was also removed. 

This was my crash trigger.
