### ISSUE TITLE
Loot Chests Bug

### ISSUE THREAD

**Issue by RandomlyGenName** [TheLimePixel/Modern-Skyblock-3#544]
Modpack Version 3.4.1 
Singleplayer
How to replicate: open a loot chest
It appears that loot chests from quests give dungeon loot instead of the normal loot in 3.3.1.4

**Comment by ButterFlyThatFly** [comment]
Yep. I thought it was just me

**Comment by ttechr** [comment]
I too am having this bug. https://imgur.com/a/rn2k5VS
