### ISSUE TITLE
Making Blades quest issue

### ISSUE THREAD

**Issue by elmatador316** [TheLimePixel/Modern-Skyblock-3#545]
Hello,

I'm restarting the pack, enjoying all the updates that weren't here the first time.  I'm starting A Basic Factory, and I see the stone blade, which is cool.  However, the quest wants me to make some other sort of blade which looks unavailable:

![2018-05-22_14 56 42](https://user-images.githubusercontent.com/38150399/40384121-b5c60ab6-5dd0-11e8-84a6-26001ba472de.png)

Since everything else in this questline is behind this, I'm kind of stuck.  I did reload the questbook, and just updated to 3.4.1.  Help!

**Comment by elmatador316** [comment]
I assume you fixed all the quests for ABF?  I'm also seeing issues with the items to unlock Heavy Machinery, so I'm sure there's other issues in the questline as well.

**Comment by wickster83** [comment]
I ran into the same problem, then copied off my save file, deleted and reinstalled the mod pack, and it is working correctly now.
