### ISSUE TITLE
[3.4.1] Gated Mode: Problem with unlocking Immersive Engineering (Heavy Machinery)

### ISSUE THREAD

**Issue by lightspeer** [TheLimePixel/Modern-Skyblock-3#549]
Since the update to 3.4.1 quest ids in the book got scrambled so there are items that don't exist anymore. Here is a screen Hope it can be fixed soon

![questbookprob](https://user-images.githubusercontent.com/39554282/40418204-fd408608-5e81-11e8-94b3-ab9f62d9388c.gif)

**Comment by Hanzaii** [comment]
I have the same problem and i want to know how can i get to know the task ID of particular task,so maybe i could just past it please.
