### ISSUE TITLE
Gated mode but basic resources is locked

### ISSUE THREAD

**Issue by MrViSiOn** [TheLimePixel/Modern-Skyblock-3#55]
Hi!

I'm in gated and my first page of quest book was Basic Tinkering and I'm blocked in _basic metering_, because i need _Main gems_ but this quest is in _Basic resources_ that I have disabled... I can't continue...

Any idea?

![2018-02-06_11 41 31](https://user-images.githubusercontent.com/67826/35855189-cc3093fc-0b32-11e8-84e4-fe7e5de6b0d0.png)

**Comment by TheLimePixel** [comment]
Well unlock Basic Resources, it's just 10 Logs.

**Comment by MrViSiOn** [comment]
No instructions for that... I collect more than 10 logs and That page keeps locked...
