### ISSUE TITLE
[3.4.1] BQ doesn't progress past first quest (Basic Resources)

### ISSUE THREAD

**Issue by AriinPHD** [TheLimePixel/Modern-Skyblock-3#553]
I'm having an issue with a completely new game where I cannot progress past the first Basic Resources quest. I should be able to load the Basic Farming quest, but it's not letting me do so.

Version 3.4.1 - downloaded from scratch (not updated from older version)

See screenshots:

![2018-05-24_00 43 19](https://user-images.githubusercontent.com/5846389/40455121-ced5b3a0-5eeb-11e8-80fc-6bb6ef20163e.png)

![2018-05-24_00 43 27](https://user-images.githubusercontent.com/5846389/40455122-cf09e724-5eeb-11e8-8d05-8f1318954e09.png)

**Comment by kg6jay** [comment]
I have the exact same issue. None of the three questlines that should open up(Basic Farming, Basic Automation, and Better Storage) unlock after completing all the prerequisite questlines in Basic Resources and Basic Tinkering. (Staged Progression mode)

**Comment by TheLimePixel** [comment]
Well, you won't be able to see the entire progression line in staged mode in the next version.

**Comment by shadowpanther** [comment]
But still, how do we progress beyond the first two questlines?

**Comment by Runesmacher** [comment]
I have the same issue. To continue i used the edit command to modify the hidden task to shown tasks with a checkbox task and a item reward, allowing me to complete and make progress

Some images before the edits
![image](https://user-images.githubusercontent.com/979451/40515960-3a51a698-5faf-11e8-9dd0-be9a7c8c3455.png)
![image](https://user-images.githubusercontent.com/979451/40515968-42b3242e-5faf-11e8-9a74-e580f480e2fd.png)
![image](https://user-images.githubusercontent.com/979451/40515988-501d0f58-5faf-11e8-8a9a-34e28024b773.png)

Example of one quest after the edit (one of the netherstar quests that are usually hidden, i put em on always show)
![image](https://user-images.githubusercontent.com/979451/40516175-ed84bc0a-5faf-11e8-8c4d-3b5c60a220e6.png)

So with a small amount of edits you will be able to continue for now ;)

**Comment by jmarler** [comment]
I am having the same problem with a multiplayer server that was upgraded to 3.4 and then 3.4.1. Completed quests do not open the next quests after the required quests are completed. I also have to edit the book and manually force it.

**Comment by AriinPHD** [comment]
@EmosewaPixel I don't understand your reply. Are you sure you did not mean to respond to another thread?

@kg6jay @shadowpanther @Runesmacher @jmarler Yes, it sounds like you have a similar issue.
You can load the game without issues.
You can open the quest, select quest-path, and complete the first basic quests-lines without issue.

(Also for @EmosewaPixel ):
Then the problem starts: BQ doesn't let you open the next quest-lines that should be opened up after completing the basic quests. As the screenshot shows: I have completed all required quests; but no new quest lines are opened for me. I cannot progress the pack.

**Comment by Runesmacher** [comment]
@AriinPHD use "/bq_admin edit" and change the withgerstar quests to be shown: unlock/always and add a chckbox task and add a item reward, that will let you progress ;) If you just check the box and then validate ;)

**Comment by AriinPHD** [comment]
@Runesmacher thanks, I'll give it a try (instructions were a little unclear and confusing) and I'll also wait for an official fix. : ]

**Comment by ghost** [comment]
Can u publish the fix? u dont need a update. just have to say how you can fix it yourself. thanks x3
