### ISSUE TITLE
[3.3.1.4] FactoryTech's Electric Furnace keeps smelting charcoal out of thin air

### ISSUE THREAD

**Issue by DrBomb** [TheLimePixel/Modern-Skyblock-3#555]
As the title says, when the Electric Furnace is loaded with the heating element and wire it starts "smelting" the empty space and results in a charcoal. It cannot be stopped and it will run until either the heating element or the wire fail.

**Comment by Caspygh** [comment]
It has been fixed in 3.4 (see changelog by selecting version through twitch; under recipes section).

**Comment by DrBomb** [comment]
Right, I've been putting off updating, but I've done it and its fixed.
