### ISSUE TITLE
Multiple item quests not completing until all items are present

### ISSUE THREAD

**Issue by DingoX3** [TheLimePixel/Modern-Skyblock-3#56]
This is pretty much a copy of this issue #33

Example: Actually Additions Empowerer Quest requires 5 display stands and one empowerer. Detect/submit would not detect display stands untill the empowerer was in the inventory. Which ment having to craft an extra display stand. Possible fix: Dont require the extra crafting item or items that are needed for the next item in order to complete the quest. 

Version: 3.1
Reloading quests had no effect

**Comment by Fababfan** [comment]
What you can do is, if you know that you need to craft other items with the requested ones, to manually detect them after every step of crafting. So the 5 stands get detected and if you use them the quest will still be done.

**Comment by andremiller** [comment]
The problem is even manually detecting does not update the quest @Fababfan

**Comment by andremiller** [comment]
@DingoX3 I may have fixed the problem for my game. I play on a server, and we've tried to re-install the server and that didn't fix the problem. So I tried re-installing my client and now the quests are updating again after clicking detect/submit. This was a completele client re-install, new config, etc. See if that works for you?

**Comment by DingoX3** [comment]
@andremiller ok great. glad that fixed it for you. ill give it a shot, see what happens.
