### ISSUE TITLE
Hangs on quitting world [3.3.1.4]

### ISSUE THREAD

**Issue by Dionysusnu** [TheLimePixel/Modern-Skyblock-3#560]
my game hangs/crashes when i quit after having my singleplayer world open to LAN. after 20 minutes, still unresponding. [latest.log](https://pastebin.com/8MTjgGbF) last thing it says is something with rftools, so it might be the mod itself. i also see some fatal messages from mjrLegendsLib?

**Comment by Dionysusnu** [comment]
i'm currently updating to 3.4.1, i'll go see if that version fixes it

**Comment by TheLimePixel** [comment]
I am aware of it, but I have no idea what's causing it, so it will not be fixed.
