### ISSUE TITLE
3.4.1 Magical Wood is uncraftable

### ISSUE THREAD

**Issue by jk1895** [TheLimePixel/Modern-Skyblock-3#562]
I only have an empty recipe:
![2018-05-27_22 29 36](https://user-images.githubusercontent.com/20401451/40590362-b29b5fa4-61fd-11e8-8ed1-2530e8973cde.png)
I play in kitchensink mode.
Greetings

**Comment by TheLimePixel** [comment]
It is, just because it requires xp it isn't displayed in JEI properly.
