### ISSUE TITLE
Mega Loot -- all items "exhausted" after update

### ISSUE THREAD

**Issue by samiratou** [TheLimePixel/Modern-Skyblock-3#564]
I updated from 3.1.5.3 to 3.4.1 and now all of my Mega Loot items are "exhausted" even though many have partial or full durability, and I know for sure they were not exhausted prior to updating.

I've downloaded the files and launch the pack through MultiMC. Examples:

![axe](https://user-images.githubusercontent.com/20819531/40623583-3ccfe428-626d-11e8-9642-bf2e7767627b.png)
![dragon_chest](https://user-images.githubusercontent.com/20819531/40623584-3ce1f618-626d-11e8-8842-89b1c3b8984f.png)
![helmet](https://user-images.githubusercontent.com/20819531/40623585-3cf77704-626d-11e8-81c9-48c53520f72e.png)

**Comment by TheLimePixel** [comment]
Exhausted means you can't level them up.

**Comment by TheLimePixel** [comment]
Actually, no, that's not it. It's probably because they are from before the last update. Many balancing changes were made to MegaLoot.

**Comment by samiratou** [comment]
OK, so any Mega Loot items I have from the earlier version are done for or will I be able to use them in the future? I agree they were pretty OP, so I understand the change, I'm just confused. Thanks for your response!
