### ISSUE TITLE
Crash after patch 3.4.1.1

### ISSUE THREAD

**Issue by Szczypo** [TheLimePixel/Modern-Skyblock-3#570]
I update my pack from 3.4.1 to 3.4.1.1 and when im joining world and want to do something the game is crashing. Here is a crashlog
[crash-2018-05-30_11.14.04-client.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/2053251/crash-2018-05-30_11.14.04-client.txt)

**Comment by jk1895** [comment]
It has to do with the atomic multiplier. Because when I create a new world and try to place it down it crashes. I downgraded the calculator mod to 5.0.4 and I can load my world again.
At least at my end... :)

**Comment by Szczypo** [comment]
Nope. That downgrade, didn't work for me.

**Comment by jk1895** [comment]
This is a pity. It seems to be more broken.

**Comment by Szczypo** [comment]
I think it's broken cause of Immersive Engineering, but need help with that

**Comment by Szczypo** [comment]
I deleted all pipes from IE still the same problem. Only Distilation Tower from IE have pipes in construction. So propably there is a problem.

**Comment by KendirkRS** [comment]
-1000,78,-972 thats the cause there i think

**Comment by Szczypo** [comment]
Yea that repaired. But still there is a bug when Fluid Pipe form IE is connecting with Fluid pipes from Ender IO. Pls repair it

**Comment by TheLimePixel** [comment]
The issue probably occured because Ender IO was updated and the conduits had changes.
