### ISSUE TITLE
Crash 3.4.1.1 from Calculator blocks.

### ISSUE THREAD

**Issue by Kyreikal** [TheLimePixel/Modern-Skyblock-3#571]
When I opened the world the atomic multiplier crashed it so I used MCEdit to remove it thinking it was just some thing that happened with the update. When I tried to replace it the game crashed again.

Crash Pastebin: https://pastebin.com/YmJ3eNNe

**Comment by TheLimePixel** [comment]
I knew stuff would break. Almost every Calculator update breaks stuff.
