### ISSUE TITLE
EnderIO Item Conduits Coloring

### ISSUE THREAD

**Issue by Jasems** [TheLimePixel/Modern-Skyblock-3#573]
No longer works, tried removing and replacing but no luck. Have to use a filter on every single conduit for a system like rock crushing/cleaning if using conduits. It worked fine previously.

**Comment by andyoc1986** [comment]
same problem here colored filter not working. People beware if updating turn off all your machines first or avoid updating until this is fixed(if you use ender io) that is. luckily i backed up :).
>EDIT<
After playing around i have found this to only be an issue with all the sky resources machines conflicting with ender io it is extracting from both input and output slots automatically. this should not be an issue with any machine with designated(hard coded) or custom side I/O config's e.g mekanism or ender io.
