### ISSUE TITLE
island visit, /tp name to name /tpa /home from compact machine

### ISSUE THREAD

**Issue by Jasems** [TheLimePixel/Modern-Skyblock-3#574]
All of the above freak out and say "you are too far from your base or spawn", several times, and put you at your starting point on your island. No longer able to visit other island and can no longer /tpa friends around.

**Comment by TheLimePixel** [comment]
Yeah, you need to sharing islands to be on each other's islands. Otherwise, the only way to visit someone is in spectator mode. This is for grief protection.

**Comment by heke85** [comment]
can I disable that?
