### ISSUE TITLE
Crash nether on load 3.4.1.1

### ISSUE THREAD

**Issue by Riezing** [TheLimePixel/Modern-Skyblock-3#575]
https://pastebin.com/mu5KMWsf

**Comment by ghost** [comment]
I get this same issue. Thaumcraft is always the last non-java code on the stack.  I can make a pastebin if needed, as I have been avoiding the nether so I can keep playing.

Also, when the crash happens, the save is then bad;  It will no longer load the world without the same crash.

**Comment by lramosmc** [comment]
Same happens to me. I started a new world and can't really go to the nether. Also I'm spawning in a Netherfortress which I thought was causing this issue but maybe not. Very annoying

**Comment by BuGRocK** [comment]
me too 3.4.1.1 win7 crash when near something in a nether not a pigman

[crash-2018-06-05_00.41.30-client.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/2069400/crash-2018-06-05_00.41.30-client.txt)
