### ISSUE TITLE
Loading into world causes crash

### ISSUE THREAD

**Issue by Xyronicx** [TheLimePixel/Modern-Skyblock-3#577]
when i try to load into my single player game it just keeps crashing. it was working fine before that for about 2 weeks and i have no idea what is causing it.

https://pastebin.com/CUL1vgtL

**Comment by TheLimePixel** [comment]
in the forge config, set removeErroringEntities to true.

**Comment by Xyronicx** [comment]
I turned on removeErroringEntites tryed to load into the world 3 times and got the same error as before

**Comment by TheLimePixel** [comment]
Try the latest version?

**Comment by Xyronicx** [comment]
updated from release version to latest beta version didn't work tried with and without remove erroring entities that didn't work

crash report:
https://pastebin.com/x1at3TU6
