### ISSUE TITLE
EnderIO glitch

### ISSUE THREAD

**Issue by henkaa** [TheLimePixel/Modern-Skyblock-3#578]
In one of the updates, EnderIO, was unlocked for me. (I play staged mode). But when I try to make items in it it says Unfamiliar item.
I thought that if I finished the related questlines that normaly unlocks EnderIO maybe would fix that issue, but now it is "unlocked" for real and the items are still Unfamiliar item.
Is there a way to fix this glitch so I can play the EnderIO questline?

For additional information, I play on a multiplayer world hosted on a friends server.

**Comment by TheLimePixel** [comment]
Did you claim the quest reward?

**Comment by henkaa** [comment]
I have claimed what I can claim. I even double-checked it now. I provide some screenshots of the current status

![2018-06-04_20 33 04](https://user-images.githubusercontent.com/24732510/40934928-c337ed48-6836-11e8-9e04-185272849b2c.png)
![2018-06-04_20 33 13](https://user-images.githubusercontent.com/24732510/40934929-c35c357c-6836-11e8-875c-c9b4c92a466b.png)
![2018-06-04_20 33 20](https://user-images.githubusercontent.com/24732510/40934930-c37fafde-6836-11e8-9c7c-d7883ce81418.png)
![2018-06-04_20 33 43](https://user-images.githubusercontent.com/24732510/40934931-c3ae3c50-6836-11e8-8cbb-c7be69031240.png)

**Comment by TheLimePixel** [comment]
Either way, you can fix it by having the stage be given to you with /gamestage add <player name> em

**Comment by henkaa** [comment]
Tnx on the help. I will ask the server admin to give it :)
