### ISSUE TITLE
Version 3.4.1.2 A basic Factory/Making blades quest issue

### ISSUE THREAD

**Issue by delcali1976** [TheLimePixel/Modern-Skyblock-3#584]
I am unable to complete this quest. the second item to be created under the stone saw blade is listed as factorytech.machinepart:sawclade-8.name 1 and the icon is just a purple and black checkered box as if the image is missing. I cannot find the item that needs to be created and cannot complete the quest without this item

**Comment by 0Samuro0** [comment]
Same 
![image](https://user-images.githubusercontent.com/40067707/41167525-d1c0f360-6b4b-11e8-838d-96acab964527.png)

**Comment by TheLimePixel** [comment]
Ik, I updated it by mistake.

**Comment by yuandaci** [comment]
@EmosewaPixel    Can you update the game version, or how can the BQ command first pass the task?

**Comment by TheLimePixel** [comment]
Revert FactoryTech to the previous version.

**Comment by yuandaci** [comment]
Emmmmmm, I am a novice, a Chinese player... Is it covering the version of 3.4.1.1?  @EmosewaPixel
