### ISSUE TITLE
The game is breaking.

### ISSUE THREAD

**Issue by Spacelocked** [TheLimePixel/Modern-Skyblock-3#587]
I'm playing the most recent version of Modern Skyblock 3, and it is my favorite skyblock pack so far. But the game is literally breaking. Sometimes when I exit the game, my inventory will be sent back in time near to when I first started, when I had just a few items, my TiC bone sword, and a questbook, losing _literally everything_ in my inventory. My sword, my pickaxes, the materials I currently were holding onto or crafting with, gone- just like that. The game also thought it would be funny to complete random quests I had not completed on startup, and even unlocked new entire categories when I was playing in staged mode, essentially ruining some of the experience. I would start a new world, but what's the point if this could happen again? It's a mess, and it's really turning me off from playing the pack knowing that I can randomly lose all progress, and ruining the entire point of playing staged mode when the game randomly decides it wants me to do a semi-kitchensink mode

**Comment by Spacelocked** [comment]
Update: I've noticed that it has triggered every time I have exited the world and reopening the world without closing the game. I'm not sure if this is the only thing that triggers it, but I am able to reperform the glitch every time by doing this.

**Comment by TheLimePixel** [comment]
That's probably it.
