### ISSUE TITLE
Crashing randomly

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#588]
https://pastebin.com/8aVuNrcf

**Comment by Zauba** [comment]
i can second that issue

**Comment by Alecsey2suvorov** [comment]
I have the same problem after updating from 3.3.1.4 to 3.4.1.2 
[latest.log](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/2087584/latest.log)

**Comment by TheLimePixel** [comment]
This is a Silent's Gems issue. Although, it does also seem t have something to do with CodeChickenCore, which recently got updated, so perhaps it will be fixed in the next version.
