### ISSUE TITLE
 Help with stage not unlocking

### ISSUE THREAD

**Issue by jrbennett83** [TheLimePixel/Modern-Skyblock-3#590]
I have started playing Modern Skyblock 3, I know I'm behind with it. I am playing the stage mode. I have 100% completed Basic Resources and Basic Tinkering and the next stages have not opened up on the "Quest book" stage. Any help would be great.   Here is what it looks like https://imgur.com/a/CBj2osu

**Comment by TheLimePixel** [comment]
Update.
