### ISSUE TITLE
Wrench vs Pickaxe in Tech Reborn

### ISSUE THREAD

**Issue by henkaa** [TheLimePixel/Modern-Skyblock-3#595]
Hi.
I have gotten into the questline of tech reborn and is familiar with the IC2 concept from before, so I know to use the wrench. But there seems to be an issue. I run 3.3.1.4 on a friends server.

On some machines (I noticed this on the Transformers) using a wrench makes the item disapear, but could be removed using the pickaxe and on some the wrench works.

So I tried a pickaxe on one of my solar panels (luckely not to expensive one) and it turned into a machine frame (as expected).

So, is this a bug? Is it known? Should I report to Tech Reborn also?
If not a bug, is there a resource for when to use wrench and when to use pickaxe?

**Comment by henkaa** [comment]
Reported to Tech Reborn as well in https://github.com/TechReborn/TechReborn/issues/1543

**Comment by TheLimePixel** [comment]
You should have probably tested it on a newer version before reporting it.

**Comment by henkaa** [comment]
I will try it in the lastest of your Betas for 3.4 to se if it is in that too.

**Comment by henkaa** [comment]
I noticed a change when testing 3.4.1.2, which is using 1.12.2-.2.15.11.688
I tried on transformers, battery box and solar panel with wrench and pickaxe. This was the result
Transformer: 
- wrench: nothing happens
- pickaxe: picks item
Battery box:
- wrench: picks item
- pickaxe: picks item
Solar panel:
- wrench: picks item
- pickaxe: gives basic machine frame
