### ISSUE TITLE
Wood Pile, Recipe There, Recipe Conflict

### ISSUE THREAD

**Issue by desagas** [TheLimePixel/Modern-Skyblock-3#60]
The recipe for wood pile from Forestry still exists, but it is impossible to craft, as there is a conflicting recipe for bark.

**Comment by TheLimePixel** [comment]
The Wood Pile recipe is shapeles. You don't have to craft it in a 2x2

**Comment by desagas** [comment]
Shapeless or not, you can not craft the wood pile. It does not work. It does not matter where on a crafting grid you put it. You can not craft it because bark has the same recipe. It does not work. The very least you can do is try it. There is a recipe conflict, regardless of what table or grid you use. If you don't care, okay, fine, I understand. I was simply pointing out a conflict.

Denver Leman

On Feb 7, 2018, at 4:36 AM, EmosewaPixel <notifications@github.com<mailto:notifications@github.com>> wrote:


The Wokd Pile recipe is shaoeles. You don't have to craft it in a 2x2
