### ISSUE TITLE
Oats and Bamboo Shoot seed have the same recipe

### ISSUE THREAD

**Issue by jaront2008** [TheLimePixel/Modern-Skyblock-3#601]
I don't know if this is a bug but i'm on the questline Basic Farming Tier 5 Seeds on the latest pack 3.3.14 . And I'm working on the seeds Oats and Bamboo Shoot. According to jei they both need corn and rice seeds to mutate to make the seed. I got the Oats seed but I can't get the Banboo seed.

**Comment by jaront2008** [comment]
if it's not a bug what is it then i can't get the bamboo seed

**Comment by TheLimePixel** [comment]
You're simply unlucky.

**Comment by jaront2008** [comment]
so to be clear they have the exact same recipe but we're supposed to get two different items?

**Comment by TheLimePixel** [comment]
Yes
