### ISSUE TITLE
Server crashing in 3.4.1.3

### ISSUE THREAD

**Issue by saytheb** [TheLimePixel/Modern-Skyblock-3#603]
Looks like Factory Tech 1.5+ is bustificated for servers (client works fine).  Tried with both 1.5 and 1.5a.

https://pastebin.com/kKPbSdua

https://gitlab.com/dalapo/FactoryTech/issues/2

**Comment by aturneruk** [comment]
I'm running into this issue too – I have reverted Factory Tech to 1.3.8 to get the pack working. 

https://pastebin.com/MQGhfM6C

**Comment by dmb1881** [comment]
Glad i'm not the only one having this issue.

https://pastebin.com/dEwVUbaK

**Comment by aturneruk** [comment]
Note that the issue with Factory Tech causing server side crashes is fixed in version 1.5b.
