### ISSUE TITLE
Can break blocks (any) but will still be there

### ISSUE THREAD

**Issue by Fvd98** [TheLimePixel/Modern-Skyblock-3#604]
- I'm playing the most recent version of the game (3.4.1.3) and my solo world is a bit odd right now

- I can still interact with all the block

- I can still place anything 

but when i want to break something, the block will break but it's presence will remain... like an invisible 
  barrier and if i place something else where it was the old block reapear just as if i never broke it in the 
  first place. that apply on every block in the map, even the one i place right now.

**Comment by saytheb** [comment]
Same problem both single player and on a dedicated server.

Always here:
[16:49:44] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/darkhax/gamestages/data/GameStageSaveHandler

**Comment by ZachTGC** [comment]
I'm also having this problem, it's typically something with lag but it's not lag, so I'm not completely sure how the issue happens. @EmosewaPixel should get on this soon. I've been doing testing to see if this can be fixed.

**Comment by saytheb** [comment]
I'm almost positive it's Ore Excavation 119. It now supports game stages, but I think there's a bug if you leave the value blank for S:"Game Stage"=

**Comment by ZachTGC** [comment]
I've tried adding a game stage in the config of the mod Ore Excavation, it's not working, saytheb.

**Comment by saytheb** [comment]
@ZachTGC What if you add a random non-existant stage, such as S:"Game Stage"=ZachTGC    ??

**Comment by ZachTGC** [comment]
@saytheb It still doesn't fix the issue.

**Comment by saytheb** [comment]
Didn't think so.. worth a shot as a workaround :(
Actual error is here: 			IStageData stage = GameStageSaveHandler.getPlayerData(player.getUniqueID());
but I can't debug it.. Funwayguy's gonna have to fix it.

**Comment by ZachTGC** [comment]
Well then. A temporary workaround is to go back to the previous version.

**Comment by Fvd98** [comment]
Thx, guys , went back to the previous version and it worked ^^.

**Comment by saytheb** [comment]
@EmosewaPixel FYI.
@Fvd98 I would suggest leaving this open.. Game Stages needs to be updated to a 2.0+ version, however there's no support from the Carry On mod yet and also a crash when loading if Carry On is removed.

**Comment by Liloa** [comment]
@Fvd98 What version did you go back to? 1 previous?

**Comment by ZachTGC** [comment]
@Liloa We all wen't back to 3.4.1.2
