### ISSUE TITLE
Cannot break any block after updating to 3.4.1.3

### ISSUE THREAD

**Issue by Kausta** [TheLimePixel/Modern-Skyblock-3#605]
Cannot break any block after updating to 3.4.1.3, however I can place and use blocks, and mobs spawn/can kill them. Only problem is I cannot break anything and nothing drops.

**Comment by Alecsey2suvorov** [comment]
same problem
[latest.log](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/2108699/latest.log)

**Comment by Kausta** [comment]
Seems duplicate of #604, missed that one, closing for now.
