### ISSUE TITLE
[3.4.1.3] Factory Tech A basic factory/making blades issue still persists

### ISSUE THREAD

**Issue by delcali1976** [TheLimePixel/Modern-Skyblock-3#606]
I updated to version 3.4.1.3 and the second stage of this quest still has the missing item (See closed issue Version 3.4.1.2 a basic factory/making blades quest issue).

**Comment by minimalkid1** [comment]
When this error must be resolved becouse i want to continue my world , i'm stuck at making blades quest. Is that an error who can't be resolved fast?

**Comment by TheLimePixel** [comment]
Did you update your questbook?

**Comment by asdkola** [comment]
Yep, and it didn't help, unfortunately.
Also I checked \config\betterquesting\QuestDatabase.json and the one in my saves folder and this quests look the same in both files. So it's not quest update problem, I think

**Comment by minimalkid1** [comment]
i solved the problem. Enter in world and type "bq_user refresh" . And the quest in factory tech is available! no more bugs or missing icon or text! For me it worked!
