### ISSUE TITLE
Crashing ever since attempting to go to the moon

### ISSUE THREAD

**Issue by Liloa** [TheLimePixel/Modern-Skyblock-3#607]
I just launched to the moon in my rocket and my world crashed, I cannot even load the world anymore

**Comment by ghost** [comment]
delete your playerdata

...\minecraft\saves\theworldname\playerdata

doesnt fix the problem but u can play

WARNING: Clears your inventory, stages and thaumcraft progress

**Comment by Liloa** [comment]
Is there anyway to manually fix stages after this step?

**Comment by Liloa** [comment]
https://imgur.com/a/c9wHChl this is what im stuck at, when I open the game this is what it opens up to
https://pastebin.com/6jzqaXRn crash report
if I click "overworld" it crashes
I can click suns and zoom in on them but thats all that I can do

**Comment by Liloa** [comment]
Got it fixed, dropped in the newest version of planet progression
