### ISSUE TITLE
infinite loading on start

### ISSUE THREAD

**Issue by syrun97** [TheLimePixel/Modern-Skyblock-3#61]
version: 3.1.1.1
disabled: iChun's Useless mods exept for iChunutil(have compressed meat)
logs(crash): https://pastebin.com/1Lj0cNyU
logs(Full):
[2018-02-07-3.log.gz](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1702324/2018-02-07-3.log.gz)
BSoDed on playing and now have infinite loading on start

**Comment by TheLimePixel** [comment]
Huh, apparently Mekanism crashes you if you have no mic. This should be
