### ISSUE TITLE
Questbook buged with double Quest entry

### ISSUE THREAD

**Issue by MonschTHEGAME** [TheLimePixel/Modern-Skyblock-3#617]
![2018-06-23_20 38 00](https://user-images.githubusercontent.com/40526165/41812624-caca55c4-7726-11e8-839b-cebcb493a25e.png)

**Comment by TheLimePixel** [comment]
Just reset that quest with /bq_admin reset <quest id> . To see the id press F3+H and hover over it while holding shift.
