### ISSUE TITLE
Bug??? with trophies 

### ISSUE THREAD

**Issue by mrDNT** [TheLimePixel/Modern-Skyblock-3#619]
You can put up crafting station from Tinkers' Construct next to trophie and acquire an item from it /

**Comment by OneEyeMaker** [comment]
@EmosewaPixel 
You can fix this issue.
In TCon's config there's option for that: ```craftingStationBlacklist```.
Try add there something like:
```mcjty.questutils.blocks.pedestal.PedestalTE```.

**Comment by TheLimePixel** [comment]
O.O When was that added!?
