### ISSUE TITLE
Infinite bed.

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#62]
After making a bed and placing it, when the item is broken from the bottom half, the top stays and when you break it, you get a second bed. This is repeatable ad infinitum.

**Comment by TheLimePixel** [comment]
That is a really bad bug, but I have no idea what's causing it. :/

**Comment by TheLimePixel** [comment]
This is probably caused by some mod messing up its multiblock detection. Testing which is going to take a while.

**Comment by dncspurs** [comment]
It's a foamfix bug. There's a workaround described in the thread linked below, and a fix incoming.
https://github.com/asiekierka/FoamFix/issues/118

**Comment by TheLimePixel** [comment]
Oh, thanks!

**Comment by asiekierka** [comment]
Fixed properly in 0.9.4

**Comment by TheLimePixel** [comment]
Oh... I wish I saw this before uploading the next version. Oh well...

**Comment by asiekierka** [comment]
That's fine. Just don't forget to re-enable the config.
