### ISSUE TITLE
AE2 - Neither crafting or autocrafting working

### ISSUE THREAD

**Issue by miscillo** [TheLimePixel/Modern-Skyblock-3#620]
I've just updated the pack to the version 3.4.1.4 and now I cannot craft with AE2. 
I've try from JEI, I tried manually. Nothing to do. 
I don't see all teh autocrafting recipies and nothing seems to be working. 

I've crafted 4 wool from strings and they became 3 in the system... and I've nothing exporting that.

Is it a bug?

**Comment by Monocheli** [comment]
I am having a similar problem. Several of my crafting patterns can be seen in the their interface or the interface terminal but not in the crafting or patterning terminals. As and example I can't make the Mekanism Steel Casing in AE2. If I take out the mats and put them in a crafting table it works fine.

**Comment by miscillo** [comment]
@Monocheli I've replaced too the crafting pattern for steel metal casing from mek but it doesn't work for me...

 just thought, but could be that every recipes with osmium in it is broken or lock the ae crafting system?

**Comment by Monocheli** [comment]
@miscillo No it isn't.
I have done some further looking and in my case it seems that all of the items that were gated behind stages don't work in AE2. The Drawer Controller, AA Casing, Thermal Machine Frame and Device Frame, EnderIO Simple Machine Chassis, Mekanism Steel Casing, and Certus Quartz Seeds to name a few.

**Comment by Kethaias** [comment]
Can confirm this is an issue with all items which are specifically marked with having a stage required. Backdating to previous 'release' version, fixes the issue. Doing further investigation as to which version specifically broke this feature.

Update:
Looks like the issue started occurring between versions 3.4.1.2 and 3.4.1.3 (crafting appears to work in 3.4.1.2)

**Comment by tommysundling** [comment]
Also had the same issue and can confirm that rolling back to version 3.4.1.2 as @Kethaias suggested appears to solve the issue. Thank you for the troubleshooting.

**Comment by SuddenTurmoil** [comment]
Updated my server from previous release version 3.3.1.4 to 3.4.1.4 directly and my server has the same issue. AE2 cannot craft anything that was previously gated. Have not tried rolling back yet.

**Comment by miscillo** [comment]
I can confirm too, @Kethaias version hassn't the problem

**Comment by ghost** [comment]
I hate to be that "me too", but I just ran into this. _Is wondering how this was NOT caught in BETA_

**Comment by Therideru** [comment]
I run in the problem and i can't understand how they can release 3.4.1.4 if this disastrous issue is in the mod pack

**Comment by SuddenTurmoil** [comment]
Hey now @DemonfangArun and @Therideru , this pack is created and offered to us for free, EmosewaPixel is under no obligation to make or distribute it. Beta testing is done by players. It is our responsibility to load beta version of the pack and play them to find bugs, report them, and help get them fixed. If this bug wasn't caught before being pushed to release either we failed EmosewaPixel or the problem occurs under very certain circumstances and those beta testing did not encounter it. This pack has 323k downloads so it probably has a pretty large player base, and we have 7 people here with the issue. If it was broken for everyone don't you think there would be more of us? Give them time to hunt down the bug. If you aren't satisfied with the speed, find a way to pay EmosewaPixel a sufficient amount to make it worth being a high priority for them.

**Comment by ghost** [comment]
Preface: this is meant to be constructive criticism

@SuddenTurmoil I was leaning more towards the side of more time should've been allowed between the last beta and release. Going by Curseforge, only 8 days had elapsed between the last beta and release. It might be good to increase that to 2-3 weeks, knowing that the size of the pool of beta players is much smaller than release.

I've also noticed a large amount of updated mods per version update, and given that 3.4.1.3 had no other significant changes other than this vs 3.4.1.2 where the issue did not exist, it is likely that one of these updates is the issue.

@EmosewaPixel , are you making sure to read changelogs in full between what version of a mod you are coming from and what you're moving to? Just a friendly reminder, not accusing you of not. I also noticed a beta version of mekanism was being used in 3.4.1.4, I would advise not (yes, I understand many mods are still in their infancy for 1.12, but it's best to stick to stable).

As an aside, could you disable the messages in chat about new mod versions? Most mod configs have a line for disabling update checkers. Just some feedback.

----

For people rolling back to the last release version, here are some things I ran into:
-TE: things that go onto itemducts (servos, retrievers, etc...) will mess up. Remove before rolling back.
-Environmental Tech: Multiblock structures may lose ownership. To fix: go into creative, Shift-Right-Click with the assembler, then punch the main block. Place down a new one and right click with assembler.

**Comment by TheLimePixel** [comment]
Related to #636 (ik this was first, but that is the actual reason behind it, so I'm closing this one).
