### ISSUE TITLE
Can't craft Litherite for E.T. [3.4.1.4]

### ISSUE THREAD

**Issue by Godomos** [TheLimePixel/Modern-Skyblock-3#621]
The diamond, flint, and green dye recipe for litherite isn't working. I am in kitchen sink mode and have reset the quest book. As such, there doesn't appear to be any way to get into environmental tech.

**Comment by alexsch01** [comment]
do you have the stage unlocked?

**Comment by Godomos** [comment]
Yes, the gated content info command shows all stages unlocked, most relevant is stage "et". Locking and re-unlocking the stage made no difference.

**Comment by alexsch01** [comment]
did you update to 3.4.1.4 or is this a new world (most likely an updated world)?

**Comment by Godomos** [comment]
updated world

**Comment by Godomos** [comment]
Embarrassing. Lime green dye, not green all around... closing issue...
