### ISSUE TITLE
Can't craft stage restricted items that have been unlocked in AE2

### ISSUE THREAD

**Issue by Monocheli** [TheLimePixel/Modern-Skyblock-3#622]
I am playing in Staged mode. Since updating to 3.4.1.4 I cannot craft items that were gated behind stages in AE2. These items were unlocked prior to updating from 3.4.1.2. When putting the needed items in my crafting grid the desired item is shown as the out put but it cannot be made by clicking on it.

Some examples of crafts that don't work in AE2 are the Drawer Controller, AA Casing, Thermal Machine Frame and Device Frame, EnderIO Simple Machine Chassis, Mekanism Steel Casing, and Certus, Fluix, and Nether Quartz Seeds to name a few. All of them can still be crafted in a crafting bench. 

My crafting patterns of gated items can be seen in the their interface or the interface terminal but not in the crafting or patterning terminals.

**Comment by ecatherman** [comment]
There is a work around listed on issue [636](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/636)

Original Report: [link](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/620)
