### ISSUE TITLE
Mobs not spawning

### ISSUE THREAD

**Issue by m4n02** [TheLimePixel/Modern-Skyblock-3#623]
Basically, i made a mob trab that does acctualy works. Recently, it stoped working, even in night, and even if i put on hard, they dont spawn

**Comment by ZacEllis** [comment]
Just to make sure, you're not too close to the mob farm when testing this? 
"Mobs can only spawn 24-128 blocks away from you. However, if you're more than 32 blocks away, they'll stop moving and some will randomly despawn. They'll also despawn immediately if you're more than 128 away from them."

**Comment by m4n02** [comment]
Thanks for the Response.
Acctually, after measuring, the distance between me and the farm is 1 block too long for full spawning potential. Even with that mistake, mobs used to spawn in there. And outside of the mob farm, it used to spawn dire wolfs. I say "used", because they just spawned in snow, ignoring the light. And even these dont spawn anymore
