### ISSUE TITLE
Unable to complete the Heavy Machinery Quest in Gated Mode

### ISSUE THREAD

**Issue by Miku0Sama** [TheLimePixel/Modern-Skyblock-3#624]
I just updated the pack today to version 3.4.1.4 (Release) and it updated factory tech which removed and changed a bunch of the items the mod added, some of those removed/changed items are currently required to complete the quest "Heavy Machinery" in Gated Mode and thus preventing progression.

Edit: This is a problem before and after I completed the quest to refresh the quest book
![2018-06-27_16 57 34](https://user-images.githubusercontent.com/14240640/42004012-3aa7cb04-7a2b-11e8-8ada-69ab9e09910e.png)

**Comment by Miku0Sama** [comment]
In the meantime, if anyone else has this problem you can use these commands to give the 3 missing items
`/give @p factorytech:machinepart 16 5`
`/give @p factorytech:machinepart 16 9`
`/give @p factorytech:machinepart 16 16`

**Comment by GeneralPeaceful** [comment]
Same has happened to me, exactly as above. I don't have cheats enabled though so I can't progress down that quest line at all >_< is it possible to circumvent it from a config file?

Edit: I am playing on singleplayer.

**Comment by Miku0Sama** [comment]
You can open your world to lan and enable cheats in the process, cheats will only be enabled until you save and quit, so you can progress the quest then save&quit to go back to playing without cheats

**Comment by TheLimePixel** [comment]
Update your questbook.

**Comment by Karrq** [comment]
Updating the questbook didn't work, still shows broken items
