### ISSUE TITLE
Quark Snow bricks slab not dropping if you break stacked block

### ISSUE THREAD

**Issue by Piincakes** [TheLimePixel/Modern-Skyblock-3#625]
Whenever I break a stacked (two slabs creating a full block) snow brick slab, instead of dropping the half i was aiming at it drops nothing. Breaking a single slab does drop it, though. I have tried with and without a shovel and neither drops the slab when breaking a full slab block.

**Comment by TheLimePixel** [comment]
This is a Klee Slabs issue.
