### ISSUE TITLE
Gunpowder

### ISSUE THREAD

**Issue by Zaraga** [TheLimePixel/Modern-Skyblock-3#628]
When trying to make gunpowder by putting 1 flint into the combustion mutliblock to make 3 gun powder, the combustion machine will do a second explosion right away even when using a lever. this makes 9 blaze powder instead of the intended 3 gun powder. only way i found around this was flooding the chamber with flint and hoping it hit gunpowder instead of blaze powder.

**Comment by TheLimePixel** [comment]
That's what you need the combustion collector for.

**Comment by Zaraga** [comment]
okay i just wanted to make that this was noticed by someone, didnt know if it was a bug or otherwise. thanks!
