### ISSUE TITLE
Factory tech issue

### ISSUE THREAD

**Issue by matziel** [TheLimePixel/Modern-Skyblock-3#632]
Tried a few recipes in singleplayer for the Autocrafting Unit. Tried to do early automation with River Grate but the autocrafter seems to have problem with making Wooden Meshes. Other recipes e.g. wooden planks or sticks works fine and autoballance grid as supposed to. 
I am playing on the latest version  of the pack (3.4.1.4). Not sure if this is some kind of recipe conflict or something with Factory Tech on it's own.

**Comment by kingchills** [comment]
@EmosewaPixel Just for clarity, was this closed because it is intended that the Autocrafting Unit is not able to make the Wood Mesh?
