### ISSUE TITLE
problem with questbook

### ISSUE THREAD

**Issue by KaizeR37** [TheLimePixel/Modern-Skyblock-3#634]
here such problem appeared after the last update, tell me how to solve it.
<a target="_blank" href="https://a.radikal.ru/a22/1807/ea/dd7299ffcb92.png"><img src="https://a.radikal.ru/a22/1807/ea/dd7299ffcb92t.jpg" /></a>
and with another task an incomprehensible problem
<a target="_blank" href="https://a.radikal.ru/a39/1807/17/257e084f60f9.png"><img src="https://a.radikal.ru/a39/1807/17/257e084f60f9t.jpg" /></a>
what kind of strange question marks? By the way I deleted and installed the assembly on a new one, did not help

**Comment by TheLimePixel** [comment]
Update your questbook.

**Comment by KaizeR37** [comment]
how ? write and I will do it, I do not know how to update it

вт, 3 июл. 2018 г. в 11:21, EmosewaPixel <notifications@github.com>:

**Comment by xob** [comment]
I came here to report the same problem with the FactoryTech quest line. Updating the quest book does not help.

I loaded a brand new fresh install of the pack from the Twitch App, created a new world, and I can confirm that the problem is still there.

This issue should not be closed.
