### ISSUE TITLE
CraftTweaker error on world load

### ISSUE THREAD

**Issue by Drethic** [TheLimePixel/Modern-Skyblock-3#636]
Pack version: 3.4.1.4

When I load up my world in single player I see the following error in the chat box for CraftTweaker loading scripts:
`ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: stages.zs}: No items or blocks found for this entry!`

**Comment by Mike-RaWare** [comment]
Here's the line in `scripts/stages.zs` that causes this error:
`mods.ItemStages.addItemStage("abf", <factorytech:machinepart:*>);`

Remove it or comment it out and this error goes away.

**Comment by kylev** [comment]
Confirmed that disabling line 794 of `stages.zs` fixes the chat message and many crafting problems, including AE2.

**Comment by temp1029** [comment]
Any idea on what the fix Pixel has in dev might be? I mean, the solution here basically amounts to "disable staging", which kinda makes the pack into kitchen sink.

I found some details on the CraftTweaker documentation ([bottom of this page](https://crafttweaker.readthedocs.io/en/latest/#Mods/GameStages/RecipeStages/RecipeStages/)) but not sure if this is an actual fix or not.
