### ISSUE TITLE
[Gated mode] Many Nuclearcraft items no longer "unfamiliar" after update. Intentional?

### ISSUE THREAD

**Issue by Ax1007** [TheLimePixel/Modern-Skyblock-3#637]
Updated from 3.4 to 3.3.1.4 and noticed  all the NuclearCraft loot items, plating, solenoids etc all stopped being "Unfamiliar".

This means I can now use them to make things like the NuclearCraft CobbleStone generator, Basic Voltage Pile(for early game massive RF storage), Buffers and Basic Solar panels all extremely early on.

Other items seem to keep the tag, so Im wondering if this was intentional or a bug.

**Comment by TheLimePixel** [comment]
Related to #636
