### ISSUE TITLE
[3.4.1.4] Basic Automation (983) trophy is empty

### ISSUE THREAD

**Issue by xob** [TheLimePixel/Modern-Skyblock-3#640]
When I placed down the trophy I obtained from quest 983 (Basic Automation in Gated mode), it was an empty trophy pedestal with no item in it.

I was able to manually "fix" it by using a Tinkers' Construct Crafting Table to place a Block Breaker inside the pedestal (thanks to #597 and #619 for the hint).

Very minor bug, but I thought I'd report it.

**Comment by TheLimePixel** [comment]
Update your questbook.

**Comment by xob** [comment]
I did update my questbook before reporting the issue. I even tried to reset the quest and re-claim the reward, it still gave me an empty trophy.

Unless the Reload Questbook (863) thing doesn't work properly? Wouldn't be the first weird issue with the Better Questing mod.

EDIT: Created a new world in creative mode to test it on a fresh save. Still gives me an empty trophy.

**Comment by xob** [comment]
I loaded a brand new fresh install of the pack from the Twitch App, created a new world, and I can confirm that the problem is still there.

This issue should not be closed.
