### ISSUE TITLE
How to Get Mushrooms?

### ISSUE THREAD

**Issue by MaxAstro** [TheLimePixel/Modern-Skyblock-3#642]
I seem to be stuck at mycelium (playing on Staged mode).

To create mycelium, I need to infuse dirt with mushrooms.  To get mushrooms, I need to infuse grass with cocoa beans.  To get cocoa beans, I need a jungle tree.  To get a jungle tree, I need... to influse a sapling... with cocoa beans?

It seems circular.

**Comment by TheLimePixel** [comment]
You get cocoa from grass.
