### ISSUE TITLE
after the upgrade it is not clear what quests

### ISSUE THREAD

**Issue by KaizeR37** [TheLimePixel/Modern-Skyblock-3#643]
Tell me what kind of quests are these with a magnetic craft, there is no fashion, there are quests. If they are not needed, tell them how to remove them, if you need to tell me how to fix them, or give screenshots of what you want to do on quests. I re-installed the assembly, I updated the book, nothing helped. Please reply normally and do not close the topic until I write that everything is fixed
<a target="_blank" href="https://d.radikal.ru/d36/1807/c8/4d493d2ffc5a.png"><img src="https://d.radikal.ru/d36/1807/c8/4d493d2ffc5at.jpg" /></a>

**Comment by TheLimePixel** [comment]
They were left in by mistake. Just ignore them.

**Comment by KaizeR37** [comment]
Thanks, I then through the editor delete them, so as not to interfere
