### ISSUE TITLE
Crafting Issue 

### ISSUE THREAD

**Issue by Mental-Cube** [TheLimePixel/Modern-Skyblock-3#647]
Somethings craft in AE and the other things dont but crafts in a normal crafting grid

**Comment by Mental-Cube** [comment]
i reopened issue because still have the same problem

**Comment by Mental-Cube** [comment]
try a new world even in kitchen sink mode stil cant craft from ae2 puts the stuff in but cant take it out

**Comment by OhhSchnapps** [comment]
Has this issue been solved yet? I'm having the same problem and can't fix a solution beyond removing the gamestages mod

**Comment by ecatherman** [comment]
There is a work around listed on issue [636](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/636)

Original Report: [link](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/620)
