### ISSUE TITLE
Not able to play the modpack

### ISSUE THREAD

**Issue by melophilia** [TheLimePixel/Modern-Skyblock-3#65]
Hi! I tried playing the modpack, but I can't get it to work. I checked to see if I have the correct java, which I do, and I have the memory to just over 6GB. I just downloaded the pack, so I assume it's on the correct version as well.

![screen shot 2018-02-07 at 21 03 56](https://user-images.githubusercontent.com/36244124/35938889-cf306352-0c4a-11e8-9a2a-fc726e715b65.png)

**Comment by TheLimePixel** [comment]
Yeah, that Java version doesn't work.
