### ISSUE TITLE
Cannot progress to heavy machinery in gated mode

### ISSUE THREAD

**Issue by RandomlyGenName** [TheLimePixel/Modern-Skyblock-3#651]
Modpack version: 3.4.1.4
Issue: missing items (see image)
Please note that this world was created in 3.4.1.4 and the questbook has also been reloaded.
In order to duplicate progress to heavy machinery in gated in current version creating a fresh world.
![heavy machinery bug](https://user-images.githubusercontent.com/39528319/42511409-2cae8b0e-8495-11e8-82c5-532259a78909.PNG)

**Comment by Ax1007** [comment]
Not the dev, but this is a duplicate  of https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/624 and https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/584 and https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/593


The more recent one, dev said to "update questbook" which doesn't work. The older one says to revert FactoryTech, so I dunno what the solution is.

**Comment by Wacko71** [comment]
Only way around that I can find until fixed is to /bq_admin and then go to quest book and remove those 3 items from there. Not ideal but it was the only way I could progress into heavy machinery.

**Comment by tahg** [comment]
Despite being duplicated, and supposedly fixed, it still appears that these aren't valid items (still).  #624 gives a possible solution without having to edit the book. What's more confusing is that some of these meta values don't seem to ever been valid according the source history of FactoryTech.
