### ISSUE TITLE
SP World - Stuttering in crafting table

### ISSUE THREAD

**Issue by DarkDon** [TheLimePixel/Modern-Skyblock-3#652]
Hello on my playthrough of modern skyblock 3 departed i encountered right from the beginning, when i try lets say to craft a furnace and i dragged all the cobblestone in the pattern and after 6 or 7 cobblestone the last blocks were missing. After reopening and refreshing the table (what causes the game to slow down somehow) the missing pieces are on a stack of before placed blocks inside the grid. 

it only happened so far on the crafting table from tinkers construct , dont know if other blocks are doing the same. 

I dont know what causes this issue but it occurs every time.

My Specs:

Intel Core i5-4670K
16 gig of ram GDDR5 SDRAM ( 8gb allocated to mc)
AMD Radeon R9 280X

**Comment by TheLimePixel** [comment]
That's just the fastest it can go. We even have a mod that makes it faster than normal.

**Comment by DarkDon** [comment]
Its not the crafting as mentioned, i figured out it has to do with the block rendering on the tinkers table, in the vanilla i can craft as fast as i am able to.
