### ISSUE TITLE
Lead Alchem dust getting iron ingots

### ISSUE THREAD

**Issue by Wacko71** [TheLimePixel/Modern-Skyblock-3#654]
Playing gated mode up to heavy machinery (edited quest book to get past the factory tech issues) and need lead for immersive engineering. Created the Lead Alchem dust and put it in the condenser with the fluid and got iron ingots out. Tried it again with stone instead of fluid and got an iron ore block.

Shut game down and reloaded, same issue recurring.

**Comment by TheLimePixel** [comment]
The iron you had in there previously isn't used up. The green bar symbolizes how much is left and you can use the dumb button to get rid of it.
