### ISSUE TITLE
unable to craft machine frames, binder composit, and many things outside of a vanilla crafting table!

### ISSUE THREAD

**Issue by frmrtxn** [TheLimePixel/Modern-Skyblock-3#660]
I've tried to craft tesla, thermal, ender io items via autocrafting with AE, and it won't even show as an option to autocraft in my system after I've entered the pattern into my ae system. Same thing with many other modded items.

**Comment by ecatherman** [comment]
Playing in Kitchen sink mode
I have it on a local network server so it is multiplayer mode

I am also having this issue. I believe in my case it does not allow me to autocraft any item that would have been locked in the quest mode. like hoppers or certus quartz seeds.

**Comment by frmrtxn** [comment]
i"m playing kitchen sink as well, should have noted that!

**Comment by ecatherman** [comment]
Could you please link to the duplicate you referenced? Does it have a solution or work around for this issue?

**Comment by ecatherman** [comment]
There is a work around listed on issue [636](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/636)

Original Report: [link](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/620)
