### ISSUE TITLE
AE2 cant craft staged items

### ISSUE THREAD

**Issue by playa2k** [TheLimePixel/Modern-Skyblock-3#662]
After updating my world to 3.4.1.4 AE2 isnt able to craft staged items anymore.
The crafting materials are placed in the crafting terminal but the table wont allow to drag out the crafting result.
Also the terminal wont show autocrafting reciped with staged items.
screenshots:
https://imgur.com/Lj3pe1T
https://imgur.com/jYJenqr

**Comment by LegendarySkar** [comment]
Came here to report the same problem.
Does anyone know a workaround to solve this?

**Comment by LegendarySkar** [comment]
@playa2k: Just as a quick info, version 3.4.1.2 works fine. I downgraded yesterday without much problems, just had to reconnect some cables and pipes.

**Comment by ecatherman** [comment]
There is a work around listed on issue [636](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/636)

Original Report: [link](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/620)
