### ISSUE TITLE
Can't place crop sticks.

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#663]
Hello, I wanted to say that I have been having a problem with Agricraft where I can't place crop sticks down on farmland by right clicking. I have tried everything but nothing has worked. I would really appreciate if this bug would be fixed. I also would like to mention that I am playing in a singelplayer world.

**Comment by kimcodekill** [comment]
will this agricraft update be part of a future pack update? in that case, when can we expect that pack update to be released? The whole basic farming questline is locked while agricraft is broken.
