### ISSUE TITLE
Applied Energistics 2 Unable to Craft Certain Recipes

### ISSUE THREAD

**Issue by ExplodingMonk** [TheLimePixel/Modern-Skyblock-3#664]
Version: 3.4.1.4 (Release) 
Playing Through the Twitch Launcher
There are a few recipes I've run into that I am unable to craft in the AE2 System. The number source I can site on this issue is with the ME Covered Cable - Fluix
Not only was the system unable to craft it, but it didn't even recognize the pattern and it did not come up in the AE2 system when searching for it. I did confirm both automated and manual crafting would work fine with the ME Glass Cable - Fluix.
I can also confirm the recipe works in a TCon Crafting Station.
From there, I downgraded the mod pack to 3.3.1.4 and was able to craft the Covered Cable in the AE system manually and automatically.

**Comment by kylev** [comment]
#636
