### ISSUE TITLE
Cannot create mirion in the Smeltery

### ISSUE THREAD

**Issue by TheJohnLong** [TheLimePixel/Modern-Skyblock-3#665]
When 1 of each Cobalt, Manasteel, Elementium, and Terrasteel are melted down in the smeltery along with a block of (vanilla) glass, creating the molten variants, no alloying occurs and all of the materials remain separate. 
This is on 3.4.1.4 on a dedicated multiplayer server.

**Comment by TheLimePixel** [comment]
It's just not hot enough.

**Comment by TheJohnLong** [comment]
The Smeltery only require a temperature to melt down materials, not to alloy them together. AFAIK.
using the exact same setup in single player, the alloying works. but it doesn't on the dedicated server, and I am using the fuel input machine which brings my furnace to a temperature of 21000 so that shouldn't be an issue anyways.
