### ISSUE TITLE
AE Crafting Terminal Not Crafting

### ISSUE THREAD

**Issue by lemonboyy** [TheLimePixel/Modern-Skyblock-3#666]
Some items won't craft in the crafting terminal which makes it very annoying to use. I've found that most modded items can't be crafted, even ones from AE2. The items will go in and the item looks like it's available to craft, but when you click it to craft, it won't.

**Comment by LegendarySkar** [comment]
Known issue, gated recipes are locked. Downgrade to 3.4.1.2 to get it working again.

**Comment by TheLimePixel** [comment]
No, that is not the solution, don't do that.

**Comment by lemonboyy** [comment]
Can I fix this problem?

**Comment by TheLimePixel** [comment]
#636
