### ISSUE TITLE
PneumatiCraft Causes Clay Buckets To Turn Into Iron Buckets When Picking Up Modded Fluids

### ISSUE THREAD

**Issue by Kittygan** [TheLimePixel/Modern-Skyblock-3#67]
if you use a clay bucket to pick up crystal fluid and place it in the world the clay bucket turns into a normal iron bucket

**Comment by TheLimePixel** [comment]
With there being 245 mods, I will not be able to find which mod is breaking the Clay Buckets by myself.

**Comment by TheLimePixel** [comment]
Ok, apparently PneumatiCraft causes this.

**Comment by desht** [comment]
Yep, will be fixed in the next PNC:R release (very soon).

**Comment by TheLimePixel** [comment]
Do you have Discord? If so, I'd like you to join my server: https://discord.gg/vypdbxy
