### ISSUE TITLE
Immersive Engineering crashing when assembling multiblocks

### ISSUE THREAD

**Issue by EricBuist** [TheLimePixel/Modern-Skyblock-3#674]
Hi,
The game now crashes when assembling certain multiblock structures of Immersive Engineering. It just happened with the advanced coke oven, but I suspect it could happen with some others. This is kind of a blocking issue as all the progression gets broken if Immersive Engineering is unstable. If the game crashes when assembling multiblocks, I cannot complete the chapter so no access to PneumatiCraft, Mekanism, etc., unless I start over in kithensick mode.

Modpack version: 3.3.1.4
Upgrading to 3.4 solves the issue but introduces severe lag making the game unplayable
Crash report: https://pastebin.com/y9BCRaFm

**Comment by TheLimePixel** [comment]
Don't report issues for older versions.
