### ISSUE TITLE
lost my island

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Modern-Skyblock-3#679]
visited friend’s island by using command **‘/island invite ~’ & ‘/island join’**.
And I was trying to go back to my island. But ‘/island home’ doesn’t work and some error message told me **‘you are too close to home! you must be at least 500 blocks away!**’
I think I lost my island because when I died I respawned at his island.
I also changed gamemode, searched for my lsland. I flied from his island to mine. And then change to survive mode, there was another error message. **‘you can't be away from your island or spawn that far away!’**.
(Backup is not my option. My friend had made so much progress.)

**Comment by TheLimePixel** [comment]
Yeah, you joined his island, there's no going back.
