### ISSUE TITLE
[Suggestion] Should be a simple way to oredict different ingots.

### ISSUE THREAD

**Issue by hqpwca** [TheLimePixel/Modern-Skyblock-3#68]
There exists several different kinds of ingot in the modpack, and the drawer system cannot oredict them properly. I'm sure the oredictionficator from mechanism does work, but in the early game, it was very annoying to have several different kinds of ingot in the inventory. A simple way to oredict items (like in drawers) will be very helpful.

**Comment by TheLimePixel** [comment]
There's an upgrade for that in 1.12+
