### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by bazinga789** [TheLimePixel/Modern-Skyblock-3#680]
My game closes when I get to the main menu with optifine installed. I need optifine or ill get 3 fps. Does someone know what I can do to fix this.

**Comment by TheLimePixel** [comment]
Try a different optifine version. However, the issue is probably due to the launcher update. Every time the MC launcher has an update, it makes OptiFine incompatible.

**Comment by TheLimePixel** [comment]
I'm guessing it's the same as #682
