### ISSUE TITLE
Game crash whilst loading

### ISSUE THREAD

**Issue by Lewis1206** [TheLimePixel/Modern-Skyblock-3#687]
as soon as i click play it gets to maybe stage 2 then crashes and says. The game crashed whilst there was a severe problem during mod loading that has caused the game to fail. heres the crash report for anyone who can maybe figure out whats wrong. https://pastebin.com/LWw9S069

**Comment by TheLimePixel** [comment]
Try restarting your PC.

**Comment by Lewis1206** [comment]
that was the first thing I tried and it didn't work
