### ISSUE TITLE
Quest book issue

### ISSUE THREAD

**Issue by ZachTGC** [TheLimePixel/Modern-Skyblock-3#688]
So, @EmosewaPixel I don't know what caused this, but somehow the NBT data from the quest book it completely removed. It's just the template right now, and all the quests are gone. I can't progress.

Casual info: Optifine installed, it happened after I closed and re-opened a world on the latest version (3.4.1.4), Using 6 GB of RAM. (BTW You might need to fix some stuff because 252 mods isn't a lot compared to most modpacks, and this takes so long to start and takes so much RAM to play. It's kinda insane.)

I tried going back to a different version to see if it works then, but it was still the template. I'm trying to see if I open the quest book with a different account to see if I can update the NBT data. UPDATE: No, it doesn't work. It is literally impossible to progress now. Restored backup, didn't work. I think I have to restart this game because of one glitch that I didn't even mean to cause.

**Comment by TheLimePixel** [comment]
1. Books don't have NBT, that would be horribly inefficient and buggy.
2. Do /bq_admin default load
3. Don't tag me
