### ISSUE TITLE
Error with party

### ISSUE THREAD

**Issue by alphas70** [TheLimePixel/Modern-Skyblock-3#69]
I am on a server and the parties do not work. The quests are not synchronizing

**Comment by alphas70** [comment]
I see the quest accomplished while it is not

**Comment by TheLimePixel** [comment]
Try /bq_user refresh

**Comment by apottere** [comment]
On our server running the latest modpack version, our quests are syncing in the party but anyone new that joins isn't getting the quest progress.

**Comment by apottere** [comment]
I used the following script to sync the quest progress of the newly added user: https://gist.github.com/apottere/5b9cf1608d64d73551a8d7b8efa929da

**Comment by TheLimePixel** [comment]
Ok, I'm pretty sure this is fixed now.
