### ISSUE TITLE
Stage TW not granted to KitchenSink mode players

### ISSUE THREAD

**Issue by Kzorith** [TheLimePixel/Modern-Skyblock-3#691]
A question was brought up on Discord why someone couldn't craft Salis Mundis from Thaumcraft while they were in Kitchensink mode.  They had the quest, but the recipe wasn't working.  For me, I couldn't even perform the initial quests to get the crystals.  They and their recipe weren't showing up for me in JEI.

Analyzing the problem, it seems that stage TW isn't granted to people in Kitchensink mode.  Executing /gamestage add {me} tw allowed me to access the stages and craft salis mundis.

**Comment by TheLimePixel** [comment]
Well, if you started playing before it was added, yes, you will have to execute the command. I usually mention it in changelogs for versions where I add new stages.

**Comment by Kzorith** [comment]
I believe I started this world after Thaumcraft was added.  I would have to check to be sure, but I'm fairly certain of that.
