### ISSUE TITLE
Bad FPS caused by Mekanism Universal cables

### ISSUE THREAD

**Issue by ManIkWeet** [TheLimePixel/Modern-Skyblock-3#694]
If you start a fresh world and place down an 8x8x8 cube of Mekanism Universal cables and power them, your FPS tanks from ~350FPS to ~30FPS.

The fix is simple:
In the mekanism.cfg file, set **B:OpaqueTransmitterRender** to **true** to disable their fancy rendering.

**Comment by DemonInTheCloset** [comment]
For those with this issue, the variable is on **line 12**
