### ISSUE TITLE
Can't craft upgrade kit after setting a recipe for crafter(enderio) even manually

### ISSUE THREAD

**Issue by DarkRecent** [TheLimePixel/Modern-Skyblock-3#696]
beacuse of the autocraft problem of AE2 I started using crafter for an altenete for auto craft then this thing is happend I can't craft upgrade kit right now and if you gonna ask I have quest2s and all kind of stuff the really odd thing about it my friend (we are playing on a server) can't carft that item too but after a server restart problem vanished but Im pretty sure it will happen again if I try to set a recipe for it again it's not hapening in singleplayer tho
![screenshot 141](https://user-images.githubusercontent.com/36361171/43671196-496f6a26-979e-11e8-8af9-36ca10ae9e15.png)
![screenshot 142](https://user-images.githubusercontent.com/36361171/43671197-49917a94-979e-11e8-80e2-1adb02fa913e.png)
![screenshot 143](https://user-images.githubusercontent.com/36361171/43671198-49b5c0f2-979e-11e8-9094-d32baba39a18.png)
![screenshot 144](https://user-images.githubusercontent.com/36361171/43671199-49d3d4fc-979e-11e8-93da-404b716da723.png)
![screenshot 145](https://user-images.githubusercontent.com/36361171/43671200-49f062fc-979e-11e8-8af9-a6db684b45b5.png)

**Comment by TheLimePixel** [comment]
You can't autocraft staged items.
