### ISSUE TITLE
Issues with crafting in AE

### ISSUE THREAD

**Issue by Scionoftruth** [TheLimePixel/Modern-Skyblock-3#697]
I have been having issues pulling items from AE crafting table, it shows the items are there and has the output, but it does not let me pull the item out with certain mods. Also if it doesn't let me pull the item out it also doesn't even show when the pattern is put in the system for auto crafting. I tried updating AE 2 to the newest version, but I am still having the same issue.

**Comment by RuinPrime** [comment]
Same here, I'm on version 3.4.1.4. 

Tried crafting Steel Casing from Mekanism, it shows up in the crafting terminal, I have all the pieces but I can't pull it out of the slot. 
![image](https://user-images.githubusercontent.com/42121163/43688935-7044bff4-98af-11e8-959a-23e393279c77.png)


Same with the Machine Frame from RFTools, Machine Chassis from EnderIO. 

A similar thing happens with the Thermal Expansion machine "centers/cores" (not sure what to call them, but it's all the core components in machines) in that all the pieces show up in the crafting grid but there's no output. 
![image](https://user-images.githubusercontent.com/42121163/43688954-d311de78-98af-11e8-8731-06c5b48fd8bc.png)

**Comment by Scionoftruth** [comment]
Crafting hoppers are also have the same problem, Seems like tile entities mainly. You cant autocraft either after putting the encoded patter in the interface, it shows in the interface screen, but to initiate crafting

**Comment by RuinPrime** [comment]
Same with the AE2 seeds, I can't autocraft Certus Quartz seeds.

**Comment by RuinPrime** [comment]
Did some digging around the closed issues and I found  #636 the solutions (both are the same thing) on there fixed the issue for me

**Comment by Scionoftruth** [comment]
Nice find, Ill close this and hope it worked
