### ISSUE TITLE
AE2 Crafting broken on locked recipes

### ISSUE THREAD

**Issue by DemonInTheCloset** [TheLimePixel/Modern-Skyblock-3#700]
All the recipes that are locked by the questbook can't be autocrafted or crafted normally on the AE2 terminal, they are unlocked on the normal crafting table and tinker's too. Patterns for autocrafting can be made, but the item won't be displayed.

Some recipes that don't work: Certus Quartz Seeds (and other AE2 seeds), Machine casings (Thermal and Mekanism), Thermal machine Upgrade Kits, I've tested more, but the common problem I found is that they are recipes unlocked by quests.

Using the Twitch Launcher, Modpack version 3.4.1.4, and the latest Java version (additional arguments: -version: 1.8+).

**Comment by RuinPrime** [comment]
#636 helped me with this.

**Comment by DemonInTheCloset** [comment]
#636 works on this issue
