### ISSUE TITLE
Minor recipe conflict - Tinker's Construct Item Rack

### ISSUE THREAD

**Issue by EvanBGood** [TheLimePixel/Modern-Skyblock-3#701]
The Tinker's Construct recipe for item racks is two wooden slabs, side by side. This conflicts with the shapeless recipe to make wooden slabs back into planks. I believe this is from Quark, but wasn't fixed by going into the Quark config and setting (block recipes remained):

    B:"Slabs to blocks recipe"=false

Could still craft the racks with a Forestry workshop, since it allows cycling through conflicting recipes.

**Comment by TheLimePixel** [comment]
Yeah, I don't plan on fixing this since the slab>plank recipe is really useful.
