### ISSUE TITLE
AE2 Terminal won't craft certain recipes or won't recognize certain patterns

### ISSUE THREAD

**Issue by noea4** [TheLimePixel/Modern-Skyblock-3#706]
The AE2 Crafting and Pattern Terminal won't craft certain recipes that can be made in the normal crafting bench. The mod the recipe is from seems to not matter as even certain recipes from AE2 itself can't be crafted through the terminal

**Comment by Frunblumglin** [comment]
This is an issue with staged crafting. The only known way i know to get rid of it is to delete or comment out a line of code. The issue has been reported (and fixed) in this post i linked below:

[https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/636#issuecomment-402718252](url)

**Comment by noea4** [comment]
Okay, good to know it's already known issue and fixed. Guess I'll have to wait for a pack update, which is fine. By the way, the link you posted doesn't seem to be redirecting to anything in particular.

**Comment by Frunblumglin** [comment]
it should be
#636 
.... wonder why the link didn't work XD

but uh...
"Here's the line in scripts/stages.zs that causes this error:
mods.ItemStages.addItemStage("abf", <factorytech:machinepart:*>);

Remove it or comment it out and this error goes away."

removing this line in the stages.zs file also fixes the AE2 problem
