### ISSUE TITLE
Awakened Draconium issues

### ISSUE THREAD

**Issue by tawraven** [TheLimePixel/Modern-Skyblock-3#709]
Something seems to be wrong with the recipe for awakened draconium.  

First of all, compacting drawers don't work properly with this material.  When you first place an item (nugget, ingot or block) into the drawer, it will very briefly show all 3 variants on the front of the drawer and then immediately changes to show only the variant that was inserted.  

Second, I've tried several auto crafters (RFTools, EU2) and none of them will convert awakened nuggets to ingots.  I can do essence -> nuggets and ingots -> blocks but not nuggets -> ingots.

Pack version: 3.3.1.4

**Comment by Ax1007** [comment]
Works correctly in 3.4.1.4, probably an issue with your version

**Comment by tawraven** [comment]
Thanks for checking.  I'm not upgrading because I had bad lag problems running the latest version.

**Comment by tawraven** [comment]
@Ax1007 Can you look in the scripts folder at the useful.zs file and see if there is an entry that fixes this?  If so, could you share it with me?  It may require the latest version of DE to fix but maybe a craft tweak recipe has been added as a workaround.

**Comment by Ax1007** [comment]
@tawraven No references to awakened Draconium sadly.

**Comment by tawraven** [comment]
This was caused by the stages file. I commented out the draconium entry and it works properly now. Apparently this staged item is not really needed anyways since the stage was added because of chickens, at least that is what I was told
