### ISSUE TITLE
I need more memeroy so i can actually play the modpack.

### ISSUE THREAD

**Issue by soccerboss908** [TheLimePixel/Modern-Skyblock-3#71]
How can i add memory for starting up the game.  i only get 2700 mb while other people get 7000+ please help.
![snipper](https://user-images.githubusercontent.com/36283588/36004212-49935514-0ce6-11e8-9c36-4cbceb199194.PNG)

**Comment by Fababfan** [comment]
In the twitch launcher go on the modpack profile, then click on the three dots to the top right and select profile options. Under memory settings untick "use system settings" and select your favourite memory.

**Comment by TheLimePixel** [comment]
Yet, since you only get 2 by default, I suspect you have only 4 on your PC which isn't enough.

**Comment by soccerboss908** [comment]
thank you fabafan it worked!

**Comment by soccerboss908** [comment]
@Fababfan it worked. Thanks for the help!
