### ISSUE TITLE
CraftingManager fallback every second

### ISSUE THREAD

**Issue by SuddenTurmoil** [TheLimePixel/Modern-Skyblock-3#712]
Server console receives a log of "Using CraftingManager fallback: Recipe <mekanism:basicblock2_3> for output <1xtile.BasicBlock2@3> rejected inputs [1xitem.OtherDust@4, 1xitem.EnergyTablet@0, 1xitem.OtherDust@4, 1xitem.EnergyTablet@0, 1xtile.EnergyCube@0, 1xitem.EnergyTablet@0, 1xitem.OtherDust@4, 1xitem.EnergyTablet@0, 1xitem.OtherDust@4]. NOT FOUND, please report." every second the server is booted. I think it is an AE2 log output saying that a Mekanism block has a bad recipe.

**Comment by TheLimePixel** [comment]
Related to #636
