### ISSUE TITLE
Gendustry causing crash on startup v3.4.1.4

### ISSUE THREAD

**Issue by NybbleLynx** [TheLimePixel/Modern-Skyblock-3#713]
The loading process gets to stage 2 and attempts to load gendustry then crashes. The crash report is located here: [https://pastebin.com/V3AH7H3D](url). I hope this can be solved :)

**Comment by ozzlik** [comment]
Me too was hoping to have some more fun today.

**Comment by jolvary** [comment]
Same here, waiting for a solution.

**Comment by catfinch** [comment]
Removing Gendustry causes an error in Extrautils, then factorytech. With those 3 removed, the game loads.

**Comment by ozzlik** [comment]
I did notice that the launcher downloaded something instead of just initializing the game. It seems to have affected the Sevtech ages mod pack aswell.

**Comment by ozzlik** [comment]
Yea but without factorytech you kinda kill the quest book a little bit. Same with extrautils.

**Comment by Vuker1** [comment]
Same here i got another pastebin if it helps https://pastebin.com/46Uc5eTY

**Comment by Alvarii5** [comment]
Me too, i'll try to downgrade Gendustry.

**Comment by catfinch** [comment]
Changing the launcher from native to jar fixes it
![image](https://user-images.githubusercontent.com/3758189/44219032-ff6f4680-a148-11e8-859e-5253f3849eed.png)

**Comment by Dr4cos** [comment]
catfinch fix is working at my end ^^.

**Comment by ozzlik** [comment]
It didn't on my end

**Comment by jolvary** [comment]
Now it reports me another error when launching from jar

https://pastebin.com/dvEedMNy

**Comment by alexsch01** [comment]
i think it is a mojang issue with lang files

**Comment by TheLimePixel** [comment]
It's just something you can get when installing the pack the first time and fixes itself when you restart your PC.
