### ISSUE TITLE
spawned on bedrock

### ISSUE THREAD

**Issue by meltz007** [TheLimePixel/Modern-Skyblock-3#715]
hello there.
when my world loaded i started on a bedrock island.   i tried the /island command to create an island but nothing happens. 
can you provide the specific commands to create a starting island.  i am understanding there are a few different ones you can end up with.

**Comment by ozzlik** [comment]
You need to type /island (island type be it sand, wood, etc)

**Comment by ozzlik** [comment]
Open the sky resources guide (might need to rebind the key)
