### ISSUE TITLE
Plastic mixer colour

### ISSUE THREAD

**Issue by pacroix** [TheLimePixel/Modern-Skyblock-3#716]
I can't select other colours in the plastic mixer. Everytime I select gray (for the quest) it switches back to black plastic.

**Comment by 00dennis** [comment]
Is this about the plastic mixer from Pneumaticraft? 
This block will only keep the color setting if you tick the Lock selection box.

**Comment by pacroix** [comment]
I have tried it again and found out, that I had the redstone behavior set to _Select Plastic on Signal_. My fault
