### ISSUE TITLE
Sky Resources 2 combusion heater multiblock bug

### ISSUE THREAD

**Issue by mroodadabooga666666666** [TheLimePixel/Modern-Skyblock-3#717]
The current modpack suffers from this bug, and it makes early game use of the combustion heater extremely annoying.

https://github.com/Bartz24/SkyResources/issues/140

I attempted to manually update the mod to 2.3.3 to 2.3.7 inclusive, 2.3.7 crashes, and the other versions do not crash, but when you attempt to activate the combustion heater multiblock, any unreacted items inside "jump out" of the multiblock.

thanks.

**Comment by TheLimePixel** [comment]
Spoiler alert: This isn't fixed in the latest version.
