### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by Crashula512** [TheLimePixel/Modern-Skyblock-3#718]
The game crashed whilst initializing game
Error: java.lang.OutOfMemoryError: GC overhead limit exceeded  
not sure what this all means.

PC Specs: 
Processor: AMD Ryzen 5 1500x
Memory: 16GB Ram
Graphics Card: GTX 1060 6GB 
[crash-2018-08-18_15.33.40-client.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/2299846/crash-2018-08-18_15.33.40-client.txt)

**Comment by 00dennis** [comment]
From your log I can see that 3 GB of memory can be used (-Xmx3072m option). That is not enough for this pack. It is recommended to assign 6 to 8 GB of memory for this pack.
