### ISSUE TITLE
Agricraft with mystical agriculture configs are broken.

### ISSUE THREAD

**Issue by Toshimonster** [TheLimePixel/Modern-Skyblock-3#721]
mysticalagriculture:inferium_essence
Is no longer an item, thus the crop sticks from the seeds fail. Change it to
mysticalaggriculture:crafting
.

**Comment by TheLimePixel** [comment]
Huh, you are the only person that managed to find where the issue was! We were having this issue for months, but no one managed to figure it out. Thanks!
