### ISSUE TITLE
Server "String too big" Issues

### ISSUE THREAD

**Issue by Leobold** [TheLimePixel/Modern-Skyblock-3#724]
Hello, I just tried to setup a server using the new 3.4.2 version and received the following error when trying to connect to the server: ( [Disconnect] User [minecraft/NetHandlerPlayServer]: Leobold has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: String too big (was 69306 bytes encoded, max 32767))  This error is repeatable and happens every time anyone tries to log onto the server.  I am not sure if this is an issue with the server files or the way I installed them, but I do know that the issue has something to do with handling the chat messages at the start of the server when a player joins.  The player is able to see the minecraft world for about a half of a second before it disconnects you with the previously mentioned error message.  I would appreciate any response to see if it is related to the pack or to my installation.  Thank you!

**Comment by TheLimePixel** [comment]
Oh, yeah, it's probably due to all the messages they get in chat.

**Comment by Leobold** [comment]
Is there anyway to reduce the amount of messages they receive then?

**Comment by Leobold** [comment]
after a fresh install, it seems it was caused by spawning in a void world and the chat constantly spamming that I was too far away from an island.  This time it worked for some reason and I was able to create an island.  Seems to be solved for now, will come back if anything else arises. :)
