### ISSUE TITLE
Mekanism cables are now opaque

### ISSUE THREAD

**Issue by SeooY** [TheLimePixel/Modern-Skyblock-3#728]
Version: 3.4.2
After updating to the latest version, all of Mekanism cables are now rendering opaque, while they were transparent in the previous version.

Screenshot of three diferent cables all opaque:
https://i.imgur.com/xVJm1g3.png

**Comment by TheLimePixel** [comment]
Yes, this was done as that caused fps issues for some.

**Comment by SeooY** [comment]
Well, is there some config I can change to have them be transparent again?
