### ISSUE TITLE
Crashing when opening unbarrel

### ISSUE THREAD

**Issue by wmssihaya** [TheLimePixel/Modern-Skyblock-3#732]
I updated to the newest version and whenever i try to access the antibarrel, my game freezes and the only way to get out of it is to close it. Here is a screenshot of what it looks like:
http://tinyurl.com/ycvwvcmv 
I can put things in with a hopper, but opening it no longer works.
I am playing on single player and I am running with 10GB ram allocated to the pack.

**Comment by TheLimePixel** [comment]
It's probably due to something you have in it.

**Comment by tawraven** [comment]
I think this occurs when you have too many unique items in it. Start removing items with conduits and eventually you’ll be able to open it. At least that is what I did.
