### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by Kzorith** [TheLimePixel/Modern-Skyblock-3#733]
The recipes for making a Calculator Reinforced Shovel (4808) and Axe (4799) are the same as the ones to make a Silent Gems Reinforced Stone Shovel (9584) and Reinforced Stone Axe (9585).  Attempting to craft the Calculator version gets you the Silent Gems version.  Unfortunately they won't work to craft the Sickle required for some recipes.

**Comment by TheLimePixel** [comment]
Use a Forestry Worktable.

**Comment by EmosewaPixel** [comment]
7
