### ISSUE TITLE
Better questing...kinda isn't.

### ISSUE THREAD

**Issue by Kalika-Hadake** [TheLimePixel/Modern-Skyblock-3#734]
So...After an update I want to get whatever quest changes there are. So I bq_admin reset all myself, reload the quest db with the quest in the book...and this happens. Every. Update. The solutions I've found thus far? Start a new world, or don't update. I have no idea if this is a BQ thing, a MS3 thing, or some weird interaction thing...but I'm perplexed. Off to start a new world again I guess.

![better questing](https://user-images.githubusercontent.com/5706492/44635241-cae16300-a970-11e8-84a0-357b0cd65618.png)

**Comment by TheLimePixel** [comment]
Just revert to a backup.

**Comment by Kalika-Hadake** [comment]
Alright. I'm sure you get this a lot 'cause BQ isn't really fit for use yet but there aren't any other options. So I'm gonna let the non-answer slide.

Here's a full steps to reproduce for you.
1. Have a MS3 3.4.1.4 profile with significant quest completion. (This previous version profile is my backup, I make one before every update of any pack, FYI)
2. Make a copy of the profile via the twitch launcher.
3. Update to 3.4.2 and launch.
4. Empty inventory of all items and equips except the BQ questbook.
5. Use the Questbook to Complete the Reload Questbook quest.
6. Check the questbook for any quests that have been completed that shouldn't have been.
7. bq_admin reset those quests.
8. Watch the questbook break in half.

![ms3 bq quest bugs](https://user-images.githubusercontent.com/5706492/44685472-85c53b80-aa19-11e8-963a-1dcd4334c2eb.gif)
