### ISSUE TITLE
invalid patterns of staged items in AE2 after update

### ISSUE THREAD

**Issue by RaveMaker** [TheLimePixel/Modern-Skyblock-3#735]
staged items patterns seems to be invalid.
the patterns are working and i can autocraft with them but i cant use the pattern terminal to create them.
pattern encoder works but it still appears as invalid.

![image](https://user-images.githubusercontent.com/3329748/44653725-315d9400-a9f8-11e8-83a3-548b1393e8d7.png)

![image](https://user-images.githubusercontent.com/3329748/44653746-3de1ec80-a9f8-11e8-9ee3-18f46b240f6f.png)

![image](https://user-images.githubusercontent.com/3329748/44653764-476b5480-a9f8-11e8-8f92-0cf883f52b79.png)

![image](https://user-images.githubusercontent.com/3329748/44653804-61a53280-a9f8-11e8-9953-475700b6656a.png)

**Comment by TheLimePixel** [comment]
So you're on the latest version and these are new patterns? That doesn't really make sense. This is an issue that was fixed on the latest version and is
