### ISSUE TITLE
Lite version possible?

### ISSUE THREAD

**Issue by ph1823** [TheLimePixel/Modern-Skyblock-3#737]
Hi ! Sorry for the inconvenience, but I have not seen any lite version available, and I do not know that mods are important, my MSI G62M does not support 278 mods, is it possible to provide a light version? (My configuration: Laptop MSI 8GB Ram i5 7300 QH, GTX 1050 Ti) Thank you for your reply! Sorry to have bothered you so much: /

**Comment by TheLimePixel** [comment]
No....
