### ISSUE TITLE
I have no clue what is causing this

### ISSUE THREAD

**Issue by Owis54** [TheLimePixel/Modern-Skyblock-3#74]
My arms and feet are continuously spinning (pictures 1-2), then whenever I touch the ground (pictures 3-5) happen.... and yes i am actually teleported away about 1500 blocks... The spinning arms and feet also happened to animals I had on the Island.
Also i figured out if I rotate my camera too far left or too far right it triggers it.
SINGLEPLAYER

Also tried on a different save so must be something with my instance

![how_moment 2](https://user-images.githubusercontent.com/36316083/36055195-b91dedbc-0dc8-11e8-906f-c20279002cdb.jpg)

![how_moment](https://user-images.githubusercontent.com/36316083/36055174-9592b1fc-0dc8-11e8-93db-912787a4b748.jpg)

![wtf_moment 2](https://user-images.githubusercontent.com/36316083/36055127-346b9600-0dc8-11e8-99d8-6ccf06223f98.jpg)

![wtf_moment 3](https://user-images.githubusercontent.com/36316083/36055128-34794020-0dc8-11e8-97a4-df34869adc9a.jpg)

![wtf_moment](https://user-images.githubusercontent.com/36316083/36055129-34896b6c-0dc8-11e8-8408-b8c327777b4b.jpg)

**Comment by TheLimePixel** [comment]
Yeah, neither do I. People have reported this in MSB2, so...

**Comment by DBArcAngel** [comment]
I know this is closed but I had this issue and resolved it so i thought I'd share my experience.  Betterfps, can't remember which of it's options it was. I changed it from the default, restarted and everything was like that, so i set it back to default and it was fine. Could be a GPU issue, i have a 2gb Radeon HD 7870.
