### ISSUE TITLE
Manual completion of quests breaks better questing.

### ISSUE THREAD

**Issue by Kalika-Hadake** [TheLimePixel/Modern-Skyblock-3#740]
After a few attempts at getting my backup to update per #734 I decided to just make a new world, in a clean instance, and start again.

Steps to reproduce.

1. Start a new world, in a new MS3 3.4.2 instance.
2. Use /bq_admin complete 580 to complete the dirt quest.
3. Claim staged mode, as well as Basic Resources and Basic Tinkering.
4. Use /bq_admin complete to complete the main quests in a given quest page to unlock the next ones. Claim the stages themselves (the questbook quests) normally (not using /bq admin complete) as you go along.
5. Here's the inconsistent part. At some point a quest with a number other than the one you put in with /bq_admin complete will complete. It may take a few, or a bunch to happen.
6. Feel free to wait a while, the completion tones will go on for a very, long, time.
7. Exit the world, and start a new one.
8. Observe that even in a new world, better questing is trying to complete these quests.

Here's a gif of me doing exactly this. Some editing has been done to reduce the filesize to under 10MB and speed things up a bit.

![ms3 bq quest bugs 2v](https://user-images.githubusercontent.com/5706492/44695548-b4efa300-aa41-11e8-9304-0fdb9e05f906.gif)

**Comment by TheLimePixel** [comment]
Doing any BQM command too many times eventually causes the quest book to corrupt.
