### ISSUE TITLE
some crafting recipes using AE system crafting grids wont give you output item

### ISSUE THREAD

**Issue by WRFleete** [TheLimePixel/Modern-Skyblock-3#741]
I have had some issues with some crafting recipes not giving you the output item when using an AE crafting grid or wireless crafting grid, EG the thermal servos used on the portable tank and I think some machine cases etc, works ok on the vanilla and tinker crafting benches

**Comment by TheLimePixel** [comment]
Does not sound like you're on the latest version.

**Comment by WRFleete** [comment]
release forge-14.23.4.2712
