### ISSUE TITLE
Agricraft breeding issue

### ISSUE THREAD

**Issue by AngryAlbino** [TheLimePixel/Modern-Skyblock-3#743]
Was trying to double crop stick but it just keeps popping off (as seen in video) Not sure if I'm doing something wrong, modpack issue or if it could be the server I'm playing on. All help is appreciated 

https://www.youtube.com/watch?v=7JqZ2dGhSj0&feature=youtu.be

**Comment by AngryAlbino** [comment]
Server issue

**Comment by ghost** [comment]
What did u do for the fix?

**Comment by AngryAlbino** [comment]
Shift when placing the first middle crop stick, it places both at once

**Comment by ghost** [comment]
that works fine ty x3
