### ISSUE TITLE
Wood Pile - Recipe confilct (???)

### ISSUE THREAD

**Issue by LemonZawodowiec** [TheLimePixel/Modern-Skyblock-3#745]
I play "Gated Mode", cleared "Basic Resources" and "Basic Tinkering".
I wanted to create big number of Charcoal in a fast way - I think "Wood Piles".
I check that best available way for me was Wood Piles in Clay.
Created Clay and now ant to make Wood Piles 
AND all what i get from 4 Wood Logs of ANY type is 4 "Any wood type BARK"
===
Is it working as intended or is it "Undocumented Pack Feature"?
Will it work correctly if i clear "Basic Automation"?
===
I'm going to try and check the answer for the second question myself - 1h-2h grinding

**Comment by TheLimePixel** [comment]
The Wood Pile recipe is shapeless so just don't put them in a square pattern.
