### ISSUE TITLE
no crafting recipes for energy cells in JEI

### ISSUE THREAD

**Issue by WRFleete** [TheLimePixel/Modern-Skyblock-3#747]
been trying to craft the jet plate (kitchen sink mode) and making the flux packs, the crafting recipes for the energy cells aren't showing in JEI, I can get the recipe for the basic one but none of the higher tiers 

version 14.23.4.2749 (3.4.2)

additionally the wireless crafting terminal has the item.wct.name item label and its crafting recipe is not directly shown in JEI, the recipe shows when clicking the item in another crafting recipe 

![image](https://user-images.githubusercontent.com/32031159/44956552-ce995a80-af19-11e8-887c-23e3018670f2.png)

**Comment by Peca21** [comment]
You need to upgrade cells just like you would upgrade machines. Use upgrade and conversion kits.

**Comment by WRFleete** [comment]
Ah ok I’ll try that next time I load the pack,
