### ISSUE TITLE
Embers missing textures

### ISSUE THREAD

**Issue by nightshard** [TheLimePixel/Modern-Skyblock-3#750]
After the switch fron Embers to Embers rekindled there are some missing textures, alchemy pedestals, stamper and maybe others.

**Comment by Pultex** [comment]
I looked at embers and they update a lot the one in my pack is 1.4 there is a 1.8 now

**Comment by 00dennis** [comment]
I had a similar issue but in my world I was able to fix it by hitting the blocks with a hammer
