### ISSUE TITLE
Gated mode, ThaumCraft unlocks with no items

### ISSUE THREAD

**Issue by ahtohio** [TheLimePixel/Modern-Skyblock-3#752]
Just unlocked Embers (Astral Sorcery was unlocked before) and I got message that ThaumCraft is also unlocked
![2018-09-08_14 27 53](https://user-images.githubusercontent.com/22412757/45253683-d9b61580-b373-11e8-84a2-d117acd18f71.png)

**Comment by TheLimePixel** [comment]
Well, either you were playing the pack before TC was added or the questbook bugged out.
