### ISSUE TITLE
Gated mode, no craft for Golden Lasso

### ISSUE THREAD

**Issue by ahtohio** [TheLimePixel/Modern-Skyblock-3#755]
Just opened Extra Utilities, everything else seems fine.
Version - 3.4.2
![2018-09-09_17 23 16](https://user-images.githubusercontent.com/22412757/45265549-48b76b00-b455-11e8-8a37-ae1749a460ea.png)

**Comment by TheLimePixel** [comment]
It works, it's just not displayed correctly.
