### ISSUE TITLE
Embers start-up artificially gated behind Dawnstone

### ISSUE THREAD

**Issue by PaulD61** [TheLimePixel/Modern-Skyblock-3#770]
The user guide for Embers Rekindled (Ancient Codex) is artificially gated behind the ability to produce Dawnstone and therefore any clues on how to start with this mod are not available until you have already figured out how to start with the mod. We need either a new recipe for the codex or an easier way to obtain it (a reward maybe?).

**Comment by TheLimePixel** [comment]
It should already be a part of the Akashic Tome reward and you can just follow the quest descriptions.
