### ISSUE TITLE
Extra Utils 2 Analog Crafter not recognising recipe for FactoryTech Mesh

### ISSUE THREAD

**Issue by PaulD61** [TheLimePixel/Modern-Skyblock-3#771]
The Extra Utils 2 Analog Crafter fails to identify the recipes for all sorts of items such as Oak Slabs and Crafting Tables in that it fails to display the crafting results but it still crafts them. This is irritating but not a major problem.
The Analog Crafter fails to recognise and fails to craft the FactoryTech mesh. This seems odd as it can handle many far more complex recipes. This is more annoying as there are almost no mid-game auto crafting alternatives.

**Comment by TheLimePixel** [comment]
Are you on the latest version?

**Comment by TheLimePixel** [comment]
That's because to get to it you don't need to go through ABF.

**Comment by PaulD61** [comment]
Yes I'm on the latest version.
Not sure what your response means. What's ABF?

**Comment by TheLimePixel** [comment]
The stage that FactoryTech is in.
