### ISSUE TITLE
Crashing during load - 3.4.2

### ISSUE THREAD

**Issue by vonriel** [TheLimePixel/Modern-Skyblock-3#773]
Just downloaded Modern Skyblock 3 Departed version 3.4.2 from the Twitch launcher, and every time I try to run it, it crashes at the same spot.

Pastebin: https://pastebin.com/YUpgc1JD

I'm not sure if it's something on my end or the pack's end, but it's happening every single time it gets to pre-initialization of the carryon mod.

Should I report this to them, instead? Or is it my own fault?

**Comment by vonriel** [comment]
Update: I rolled carryon back a version, still crashed. Rolled it back to a much older version, ran into a conflict somewhere else. When I removed it altogether, it crashed again at chancecubes.

Rolling back to 3.4.1.4 sees the same crash issues. 

I guess at this point I don't get to play this modpack.

**Comment by TheLimePixel** [comment]
Just restart your PC.

**Comment by vonriel** [comment]
That was the first thing I tried, since it was the only solution to come up when I went looking for it. Went ahead and restarted twice more just to see when I got this response, it's still crashing at the same spot.
