### ISSUE TITLE
astral sorcery - finding good place to put altar (fosic resonator, etc)

### ISSUE THREAD

**Issue by DoomSquirter** [TheLimePixel/Modern-Skyblock-3#78]
pretty new to astral sorcery but followed the steps and to find a place to place down ur altar and get enough light coming in, you need to use the fosic resonator to highlight land and wait for sparkles, etc.  but if you're on a skyblock, you can't really do that.  

did you have some way in mind to get around this?  I've tried to find a good spot within a 9x9 chunk radius around my base and I can't seem to build much of the mid tier stuff.  bad luck I know but that means my base is totally in the wrong place then and really confused how you're supposed to find these areas in a skyblock.

edit: oh yeah, and I'm building high up at y140 as they told me to in discord, but again, still not helping a whole lot.

**Comment by TheLimePixel** [comment]
You can link a Floating Crystal to your aktar to fill it up.

**Comment by DoomSquirter** [comment]
that's well and good.  didn't see mention of that anywhere in quest book.

was told by mod author that the blue shadow shows up at Y 0 even w/o blocks down there as long as ur using night vision to look for them.  that led me to one near my base luckily.
