### ISSUE TITLE
Adding pack to MultiMC using .zip file does not work

### ISSUE THREAD

**Issue by lesdmark** [TheLimePixel/Modern-Skyblock-3#782]
**Describe the bug**
When you try to create the instance in MultiMC it fails with an "Unable to Resolve Mod ID error"

**To Reproduce**
Attempt to create instance using MultiMC

**Crash Reports**
The problem is that the EXu2 mod is no longer on curse and the error occurs when you try to download it.

**Pack Information**
 - Pack version: 3.4.2
 - Pack Mode: N/A
 - SP or MP: SP
 - Added Mods: None

**Screenshots**

**Additional context**
I am going to remove the reference in the modlist.html file, edit the manifest.json file and then manually add the mod back in once it creates the instance to resolve the issue for myself. Just giving you a heads up that it is occurring.

**Comment by benten2000** [comment]
Must be the same problem when trying to download it from the Twitch App:

Cannot find child addon: 262691.

**Comment by MrNoodle1** [comment]
Has anyone found a solution to this? I'm unable to down Modern Skyblock 3. It says, "Cannot find child addon: 262691".

**Comment by ghost** [comment]
same...
