### ISSUE TITLE
Download won't complete, missing addon 262691

### ISSUE THREAD

**Issue by Fezraptor** [TheLimePixel/Modern-Skyblock-3#784]
When dowloading through the twitch launcher the error code " Cannot find child addon: 262691 " pops up and cancels the download. 262691 appears to be referring to the mod ExU2 - Cursed Earth Ritual, which doesn't seem to have a curseforge page

Tested on pack versions 3.4.2   3.4.14

**Comment by henkaa** [comment]
Did you solve the problem? I get the same issue.

**Comment by Fezraptor** [comment]
I realized there was already an open thread for the issue
https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/782

**Comment by henkaa** [comment]
Tnx. I will read up that :)

**Comment by MrNoodle1** [comment]
Has anyone found a solution to this? I'm unable to down Modern Skyblock 3. It says, "Cannot find child addon: 262691".

**Comment by ghost** [comment]
same...
