### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Jiriki79** [TheLimePixel/Modern-Skyblock-3#785]
**Describe the bug**
When i try to install the modpack i get a error message about a certain file

**To Reproduce**
it just happens to me when i try to install the latest release

**Crash Reports**
none bc it's first install

**Pack Information**
 - Pack version:3.4.2,3.4.1.4,3.3.1.4 all releases

**Screenshots**

![capture](https://user-images.githubusercontent.com/43390202/46842422-16ba6100-cd93-11e8-85ba-e42b7cf113d4.PNG)

**Comment by AusPakeha** [comment]
I have this error too. 
Tried to install 3 times. 
Watching the downloader on the last install, it will cancel the download just after starting the download of Integration Foregoing

**Comment by Tkdriverx** [comment]
The mod in question that appears to just disappeared off the Curse mod portal was **ExU2 - Cursed Earth Ritual (by voxatu)** (the id 262691)

**Comment by Jiriki79** [comment]
for me it gets to like mod 180 on install and then i get that message

**Comment by Keepo84** [comment]
I have the exact same problem. The client can not find some mod and refuses to install the pack.

**Comment by Highlighted-dev** [comment]
This same problem ;/

**Comment by PhoenixtheII** [comment]
*Joins the club*

**Comment by Jumper91305** [comment]
Same problem

**Comment by MrNoodle1** [comment]
Same, and I have no clue how to get around it.

**Comment by Keepo84** [comment]
A temporary workaround is possible: Download the server files from the curse page and then create a custom profile in the twitch launcher. select minecraft version 1.12.2 and forge build 2749. 

Copy the contents of the server to the folder of your new instance and you should be able to play the pack.

**Comment by Highlighted-dev** [comment]
@Acnologia- Thanks, working for me.

**Comment by AsaanJayah** [comment]
Same error for me, i tried it more than 10 times. Even tried different versions a upgrade it.

**Comment by AsaanJayah** [comment]
When it comes to Industrial Foregoing it says "error child addon: 262691"

**Comment by Tkdriverx** [comment]
![image](https://user-images.githubusercontent.com/9004164/46906583-c4cd2480-ced3-11e8-9324-444c12dea70a.png)
This is another error that seems to occur.

Also, it is not Industrial Foregoing that is the missing mod, it's some other mod that was removed from the curse mod directory: ExU2 - Cursed Earth Ritual

**Comment by Rabrennie** [comment]
Got a workaround:

1. Download https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2607165
2. Extract the zip Modern+Skyblock-3.4.2
3. Download https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2607201
4. In the server files zip locate /mods/exu2cer-1.12-1.0.jar and copy it into the extracted Modern+Skyblock-3.4.2 folder/
overrides/mods/
5. Edit the manifest.json, removing lines matching `{
      "projectID": 262691,
      "fileID": 2450585,
      "required": true
    },`
6. Zip Modern+Skyblock-3.4.2 back up, making sure overrides, manifest.json is at the root of the zip file
7. Go into twitch > mods > minecraft. Click Create Custom Profile, and click Import at the top. 
8. Select the zip file you just created, twitch should now download the required mods successfully

**Comment by Tkdriverx** [comment]
@Rabrennie That's literally what I was about to post about, you beat me to it. 

For those who don't want to do all that manual work, here's the edited zip file:

[Modern+Skyblock-3.4.2.zip](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/2476581/Modern%2BSkyblock-3.4.2.zip)

**Comment by AsaanJayah** [comment]
Another way is to put modern skyblock to download, wait until it starters to download the mods, copy the whole thing and past it in a folder then install the modern skyblock server file and copy only the mods and past is on that folder mods folder then run it.
It worked for me.

**Comment by Firesniper2002** [comment]
Is there also a way to do so for Modern Skyblock 2?
