### ISSUE TITLE
Unable to download pack

### ISSUE THREAD

**Issue by UnhallowedDeath** [TheLimePixel/Modern-Skyblock-3#788]
**Describe the bug**
I am unable to download the pack on the twitch launcher

**To Reproduce**
1.)Delete pack
2.)Try to install
3.) around trying to install mod 226 it crashes

**Crash Reports**
A link to a crash report. (it needs to be on pastebin or a similar site. If it's an attached file or copy-pasted in the issue, it will be closed).

Error:
Cannot find child addon: 262691

**Comment by Nomless** [comment]
#785, #782, and #784 are also addressing this problem. I don't believe there is a fix that works so far. You could try using the server files to replace the deleted mod that is addressed in #785.
