### ISSUE TITLE
log chicken won't detect

### ISSUE THREAD

**Issue by hossumquat** [TheLimePixel/Modern-Skyblock-3#79]
I've gotten log chickens to spawn and got them with the chicken catcher, but the quest book fails to detect that I got one.  Flint chicken and nether chicken worked fine.  Not sure about sand chicken yet as I haven't gotten one to spawn yet.  Playing the latest (3.1.2) version.

**Comment by joakime** [comment]
I had this problem too.

**Note:** The following is for the developer @EmosewaPixel

I fixed it in the `QuestDatabase.json`

Original entry for `chickens:logchicken`:

``` json
      "properties:10": {
        "betterquesting:10": {
          "issilent:1": 0,
          "snd_complete:8": "minecraft:entity.player.levelup",
          "lockedprogress:1": 1,
          "tasklogic:8": "AND",
          "repeattime:3": -1,
          "visibility:8": "ALWAYS",
          "simultaneous:1": 0,
          "icon:10": {
            "id:8": "roost:chicken",
            "Count:3": 1,
            "tag:10": {
              "SGProperties:10": {},
              "Growth:3": 1,
              "Chicken:8": "chickens:logchicken",
              "Gain:3": 1,
              "Strength:3": 1
            },
            "Damage:2": 0,
            "OreDict:8": ""
          },
          "globalshare:1": 0,
          "questlogic:8": "AND",
          "partysinglereward:1": 0,
          "snd_update:8": "minecraft:entity.player.levelup",
          "autoclaim:1": 0,
          "ismain:1": 0,
          "name:8": "Basic Chickens",
          "desc:8": "No Description"
        }
      },
```

The various problematic entries for chickens have an extra `tag:10` for `"SGProperties:10": {},` which seems to prevent its detection by better questing. (I don't know what this tag is for).

Once I removed that entry from the quests for "Log Chicken" and "Glowstone Chicken" (only) they started to be detected by my questbook.

**Comment by joakime** [comment]
Ah. `SGProperties` is from Silent Gems.

See: https://github.com/SilentChaos512/SilentGems/search?utf8=%E2%9C%93&q=SGProperties&type=

I would say that any quest that isn't specific for Silent Gems, should not have that requirement in the `QuestDatabase.json`

**Comment by TheLimePixel** [comment]
Yeah, an item gets that tag when held.

**Comment by joakime** [comment]
Would getting rid of the "Growth:3", "Gain:3", and "Strength:3" entries make the chickens quests trigger on any growth/gain/strength chicken?  (I personally think that would make for a more consistent user experience on KitchenSink mode, where the progression isn't as linear.)

**Comment by TheLimePixel** [comment]
It wouldn't make a difference.
