### ISSUE TITLE
ME Universal Terminal won't let me pull or insert items in "crafting" mode

### ISSUE THREAD

**Issue by pkpn** [TheLimePixel/Modern-Skyblock-3#797]
After having updated my dedicated server from 3.42 to 3.50 the AE2 Wireless Universal Terminal won't let me pull items or put items back in the system when the terminal is in crafting mode. When in item mode I can pull/push items normally. (Right clicking on an item let's me pull the normal half stack though)
When trying to do this the server console outputs an error: Error executing task (Server thread/FATAL)

1. Shift + right clicking with the terminal in hand changes the modes (item/gas/fluid/crafting).
2. When in crafting mode it won't accept items or let me pull out items.
3. It gives an error in the server console.

Link to the error in the console here: https://pastebin.com/uVi1qWim

**Pack Information**
3.5 (updated from 3.42, only copied over the world folder and the banned players and whitelist)
Gated mode
Multiplayer
No added mods

**Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/7557704/47610011-171d5200-da4b-11e8-9009-d4b404bbd7af.png)
![screenshot_2](https://user-images.githubusercontent.com/7557704/47610023-4d5ad180-da4b-11e8-9d52-c6e4a0b96c9b.png)

**Additional context**
The other player on my server has the same problem. We have tried recoding the terminals in the security terminal to no avail. We have tried cheating in new ones, same problem.

**Comment by Craken761** [comment]
Also experiencing this issue. The issue also persists if you use the standalone wireless crafting terminal.

**Comment by BrockWS** [comment]
Wireless Crafting Terminal needs to be updated to 3.10.82.

**Comment by pkpn** [comment]
> Wireless Crafting Terminal needs to be updated to 3.10.82.

It worked, thank you! :)
