### ISSUE TITLE
BuildCraft got removed in 3.5?

### ISSUE THREAD

**Issue by Zrashin** [TheLimePixel/Modern-Skyblock-3#804]
I downloaded the Server for 3.5 and also downloaded 3.5 through Twitch Client, seems that all buildcraft mods got removed?

Is buildcraft not included anymore?

**Comment by shadus** [comment]
Wow, good timing.  I was just coming here to comment and ask the same question on this, configs appears to be in place for buildcraft, no mention of its removal in general and its still referenced in the quests so appears like it *should* be here.  Is it intentionally removed?  If so what are we supposed to be using around the time we would start using buildcraft transport in replacement of it?  Quest lines not giving any real suggestions and the other active mods at the time (in gated mode) like actually additions have transport options disabled until after (TPOD) the power of dragons.

**Comment by TheLimePixel** [comment]
Intended. Since Conveyors in FactoryTech don't move items as actual items i.e. don't cause as many server issues, there is no need for BC Transport.

**Comment by Zrashin** [comment]
Is there an alternative to the Apiarist Pipe used in BC Transport for Forestry Bees?
