### ISSUE TITLE
Twilight Portal Opens with Diamond and not Dragonstone

### ISSUE THREAD

**Issue by Traster101** [TheLimePixel/Modern-Skyblock-3#808]
**The Bug**
The portal for the Twilight Forest only opens with a diamond, and will not open by throwing a dragonstone into it.

This is not necessarily an issue that I need fixed for myself (I can just change the pack config if I wanted to), but I felt that it was important to bring this to somebody's attention if anybody else is having a similar issue.

**Set up**
Create Twilight Forest portal as usual
  - 2x2 water
  - surrounded with grass
  - with flowers on it
Then throw the item in (Diamond or Dragonstone)

**Pack info:**
-Version 3.5.0
-SP
-Gated and Kitchensink (have not tested staged)
-Appears in Creative and Survival mode
-No Added Mods

**Screenshots:**
N/A

**Comment by TheVekter** [comment]
This is the original behavior for the mod, seems more like a typo in the quest book or Pixel intended it to be gated behind Botania progression and never actually switched it as such.

Seeing as how the pack isn't being supported any longer, doubt this will get a fix.
