### ISSUE TITLE
Unable to craft Infinity Catalyst

### ISSUE THREAD

**Issue by Degenerecy** [TheLimePixel/Modern-Skyblock-3#817]
**Describe the bug**
Recently gathered all the materials to craft the Infinity Catalyst from Avarita.  When placing them the + shows up saying I have all the meterials and when placing them in proper spots, no item is recognized to be crafted.

**To Reproduce**
1. Place items in Avaritia Crafting Table, Also removing items and selecting the + adds them back.
2. Nothing.

**Crash Reports**
N/A

**Pack Information**
 - Pack version: 3.5
 - Pack Mode: Staged Mode
 - SP or MP: SP
 - Added Mods: Not Enough Wands, LagGoggles

**Screenshots**
![image](https://user-images.githubusercontent.com/28640345/50052177-fed5c500-00d4-11e9-9b41-d81b20574a75.png)

**Additional context**
Using Post [https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/799](issues #799) doesn't solve the issue.  

Same issue with the creative capacitors, both Thermal and Draconic ones.
Also Creative RF Source

**Comment by FruityPewps** [comment]
Hey, so here is the thing. I contacted the mod author of JAOPCA singularities as I am personally updating this pack fixing stuff etc etc as practice for when I decide to make my own if I do... He is going to push an update that fixes the crash that happens if you remove the catalyst recipe. He is also going to add a config option to not auto populate singularities into the crafting recipe which is what is happening, hence the over ingredients rendering the recipe uncraftable. 

I have modified the recipe and removed the Pile Of Neutrons and Neutronium Nuggets. I believe these 2 items being present in the recipe in the first place are unnecessary as the ingot is included. This better follows in line with the matrix ingot. Doing so moved the 2 conflicting singularities into the grid, enabling the ability to craft the catalyst.
```javascript
//Better Catalyst recipe
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);
mods.avaritia.ExtremeCrafting.addShapeless("catalyst",<avaritia:resource:5>,[<avaritia:resource>,<avaritia:resource:1>,<avaritia:resource:4>,<avaritia:endest_pearl>,<avaritia:ultimate_stew>,<avaritia:cosmic_meatballs>,<avaritia:resource:7>,<avaritia:singularity>,<avaritia:singularity:1>,<avaritia:singularity:2>,<avaritia:singularity:3>,<avaritia:singularity:4>,<avaritia:singularity:5>,<avaritia:singularity:6>,<avaritia:singularity:7>,<avaritia:singularity:8>,<avaritia:singularity:9>,<avaritia:singularity:10>,<avaritia:singularity:11>,<avaritia:singularity:12>,<avaritia:singularity:13>,<avaritia:singularity:14>,<skyresources:darkmatterblock>,<skyresources:lightmatterblock>,<draconicevolution:chaotic_core>,<mysticalagradditions:stuff:69>]);
```
Replace the current recipe in creative.zs with the above. That should resolve the conflict.

EDIT: 28DEC18 - Fixed syntax issue with posted code

**Comment by Degenerecy** [comment]
Will look into it when I can get to it. for the moment I will do as Direwolf20 did and cheat them in.

**Comment by FruityPewps** [comment]
No worries. Just wanted to change the recipe like this rather than have someone need to install things as a workaround. 

Let me know if it works for you.

**Comment by Degenerecy** [comment]
Additional Comments Added

**Comment by FruityPewps** [comment]
I'll take a look. Please let me know if the Infinity change at least worked for you. 

EDIT: Update to the most recent Avaritia. If on Twitch Launcher simply unlock your Modern Skyblock 3 profile and update there, or go here: https://minecraft.curseforge.com/projects/avaritia-1-10/files/2648800 and place that file into your mods folder and remove the previous Avaritia version.

Please update the recipe I modified for you for the Infinity Catalyst in the Creative.zs script in the scripts folder.

This should resolve both issues.

**Comment by ManIkWeet** [comment]
There seems to be some issues with the given syntax, the fixed syntax is:

```
//Better Catalyst recipe
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);
mods.avaritia.ExtremeCrafting.addShapeless("catalyst",<avaritia:resource:5>,[<avaritia:resource>,<avaritia:resource:1>,<avaritia:resource:4>,<avaritia:endest_pearl>,<avaritia:ultimate_stew>,<avaritia:cosmic_meatballs>,<avaritia:resource:7>,<avaritia:singularity>,<avaritia:singularity:1>,<avaritia:singularity:2>,<avaritia:singularity:3>,<avaritia:singularity:4>,<avaritia:singularity:5>,<avaritia:singularity:6>,<avaritia:singularity:7>,<avaritia:singularity:8>,<avaritia:singularity:9>,<avaritia:singularity:10>,<avaritia:singularity:11>,<avaritia:singularity:12>,<avaritia:singularity:13>,<avaritia:singularity:14>,<skyresources:darkmatterblock>,<skyresources:lightmatterblock>,<draconicevolution:chaotic_core>,<mysticalagradditions:stuff:69>]);
```

**Comment by FruityPewps** [comment]
I think I used quote instead of code block hence the syntax issue. Ooops. Thanks for fixing.
