### ISSUE TITLE
Challenges are complete but items are still gated

### ISSUE THREAD

**Issue by dcat2095** [TheLimePixel/Modern-Skyblock-3#818]

**Comment by dcat2095** [comment]
[SSP] I logged off with a bloodpearl in my inventory and logged back in a few hours later with my inventory clear and i cant use most of the mods like silent gems, AgriCraft, EU2 and most of the others.
Version 3.5.0

**Comment by FruityPewps** [comment]
Try loading a backup. Can be found in your instance folder. Not sure what would cause that kind of issue and on holiday so cannot figure it out for ya.
