### ISSUE TITLE
Crash during preinit

### ISSUE THREAD

**Issue by inf1425** [TheLimePixel/Modern-Skyblock-3#819]
AE2 crashes during preinit.
I tried updating AE2 but it didn't do anything.
https://pastebin.com/g2M0bmzK

**Comment by FruityPewps** [comment]
How much ram are you dedicating to the pack? Preinit crashes are likely end user.

**Comment by inf1425** [comment]
I removed AE2 for debugging, but it still crashed and showed that ctm bugged out. I removed ctm, added AE2 to the pack again and now it works.
