### ISSUE TITLE
What is the mod that highlights blocks with Shift+Rightclick?

### ISSUE THREAD

**Issue by Traster101** [TheLimePixel/Modern-Skyblock-3#824]
Not really a bug, but every time I Shift+Rightclick on a block with an empty hand it highlights it so that I can see it through walls, but it conflicts with everything else (Carry on, some Botania, etc). I can't find it in the controls menu, and I really want it disabled

**To Reproduce**
1. If I knew, I wouldn't really have this problem...

**Pack Information**
 - 3.5.0
 - Gated
 - SP
 - No Added Mods

**Screenshot**
![2018-12-29_19 52 44](https://user-images.githubusercontent.com/45136416/50543653-9e01be80-0ba3-11e9-8fa9-2bb7497da2fc.png)

**Comment by FruityPewps** [comment]
Probably a bauble you have doing it. But if I were you I'd sort by key in the controls menu... Shift or something and 1 by 1 see which might do it. Then check that mods config.

**Comment by Traster101** [comment]
Yup, it was one of the weird Botania baubles doing it, the Ring of Loki specifically. I'm annoyed that it doesn't have a control bounded to it, but at least that's done finally.
