### ISSUE TITLE
Questbox Non-existent item

### ISSUE THREAD

**Issue by computer2467** [TheLimePixel/Modern-Skyblock-3#826]
I know this isn't probably very important, but i received four void pipes from a quest box which are from buildcraft which doesn't appear to be in the pack.

**Comment by FruityPewps** [comment]
Yeah since the pack dev removed BC he forgot to edit the loot tables. Unfortunately a pack update beyond 3.5.0 is unlikely. I have been fixin up stuff, so maybe in the future we can get a small update that will address all of these issues.
