### ISSUE TITLE
All blocks change in latest update?

### ISSUE THREAD

**Issue by ronaldburns** [TheLimePixel/Modern-Skyblock-3#84]
Updated from 3.1.1.1 to 3.1.2 and my island has become this mess.
![island](https://media.discordapp.net/attachments/364965554248876042/412323186257166347/unknown.png)

**Comment by ronaldburns** [comment]
level_sponge got corrupted. Recovered and server world is good now

**Comment by TheLimePixel** [comment]
Ok, glad that you got your world back.
