### ISSUE TITLE
Only potato seeds with bonemeal on grass

### ISSUE THREAD

**Issue by samccoelho** [TheLimePixel/Modern-Skyblock-3#884]
Hi, i'm trying to complete the seed quest by using bonemeal on grass; but it seems like i'm getting only potato seeds, which isn't letting me complete the quests. (Which I have to complete because I'm on gated mode)

I'm not sure if this is the wrong place or if I should just fix this myself instead of submitting a report. 

Thanks

**Comment by dakre18** [comment]
It's actually a very low drop rate for everything but potato seeds. Plant matter was easier to get.

Just plant matter grass, then vein mine the grass. Took almost 2 stacks for me to get all of them.

It would be nice if it were easier though.

**Comment by samccoelho** [comment]
Okay noted. Thank you
