### ISSUE TITLE
Botania Alter Ticking Block Entity Crash

### ISSUE THREAD

**Issue by aultra** [TheLimePixel/Modern-Skyblock-3#94]
I just started receiving the attached crash tonight on my existing world, which I updated to 3.1.3 tonight.  Seems to be Botania related from what little I understand of the (attached) crash log.  If more information is needed from me, I will be happy to assist.  The game is multiplayer, hosted.  I did reinstall the client from scratch, and continued to receive the crash.

[crash-2018-02-13_02.21.46-client.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/1719181/crash-2018-02-13_02.21.46-client.txt)

**Comment by TheLimePixel** [comment]
What do you have around your Petal Apothecar?

**Comment by aultra** [comment]
I am remembering off the top of my head, but I am pretty sure it is in the corner of my platform, lower half slabs would be on 2 of the sides, full blocks on 2 sides, and air above and below.

**Comment by aultra** [comment]
This probably doesn't mean much, but it only crashes the client.  The server remains fine with no errors.

**Comment by TheLimePixel** [comment]
Do you have a crafting station next to it (as that is a known issue)?

**Comment by aultra** [comment]
I'm having a hard time remembering if I moved it.  But I just might have moved it and placed it between my wash station and my worbench/crafting station, since it is closer to my water.  Is there any work around to get back in either by removing the block via command line or something? I apologize that my memory is terrible on details like this.

**Comment by aultra** [comment]
I used the debug output to /setblock the block to air, and found out that it was next to my crafting station.  This can be closed, if it is already a known issue.
