### ISSUE TITLE
again Stage 

### ISSUE THREAD

**Issue by EvoTheOne** [TheLimePixel/Modern-Skyblock-3#95]
Hello all,
first i have bad english sorry for that.
I need help i play on Kitxhensink mode but after update i cant craft Elevator from Open Computer
its teels me i need Stage OA first, my question now how i can get this stages?
i deactivate /gamode etc... so i need a other way! 

Thanks for helping!

**Comment by Fababfan** [comment]
If you have cheats deactivated, just select "Open to LAN" in your minecraft settings and you can type commands.

**Comment by EvoTheOne** [comment]
nice thanks =)
