### ISSUE TITLE
can not craft bronze dust

### ISSUE THREAD

**Issue by syrun97** [TheLimePixel/Modern-Skyblock-3#97]
i need bronze for forestry machines and i cant make bronze dust 
does bronze is gated on immersive engineering or ember?
![2018-02-14_01 26 46](https://user-images.githubusercontent.com/19798397/36161438-0787613e-1127-11e8-83ad-222305f18552.png)

**Comment by mckulich** [comment]
I just check all possible ways, and i think that Embers is only way how to obtain bronze at this moment. All machines which are needed for this process are avaible. (stamper, melter, crystal, etc.. they are possible to make, even if you dont have open Embers chapter in quest book

**Comment by TheLimePixel** [comment]
You can make it in an Alloy Kiln
