### ISSUE TITLE
A Master Chief requiments (gated)

### ISSUE THREAD

**Issue by mckulich** [TheLimePixel/Modern-Skyblock-3#98]
I am not sure if its intentional or not, but after update there is requiment 640 dense stone storage insteadl of 64 and i didnt find nothing about it in changelog so i guess its a mistake or is it really new requiment ?

**Comment by TheLimePixel** [comment]
It's a new requirement, but I think I went too far there.

**Comment by mckulich** [comment]
Ahhh maybe a little bit :D Its 7680 stone + 2560 glass + 320 charcoal to burn it + 2560 cobble to make that glass :D it is hell of grind :D i am glad i already did this one, i think that 128 or 196 could be fine, if you want to make it longer :)
